### ISSUE TITLE
Get "Query root type must be provided." error when query type

### ISSUE THREAD

**Issue by xjiangiao** [dotansimha/graphql-code-generator#3268] opened 2020-01-10 07:15 UTC
**Describe the bug**
Get error when schema's query root type's name isn't "Query".

The code will generate without error when the Query root type name is "Query"

**To Reproduce**
https://codesandbox.io/s/festive-firefly-vle63?fontsize=14&hidenavigation=1&theme=dark
just generate the code

1. My GraphQL schema:

```graphql
type QueryRoot {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}

schema {
  query: QueryRoot
  # query: Query
}

```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}

```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "./schema.graphql"
documents: "src/**/*.graphql"
generates:
  src/app/graphql/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
```

**Expected behavior**

Generate query code of apollo angular.
**Environment:**

- OS: Window 10
- `@graphql-codegen/...`: 1.11.2
- NodeJS: 12

**Additional context**

**Comment by wassim-k** [comment] 2020-01-13 00:05
I've come across the same issue and I have narrowed it down to this line, which strips out the custom schema definition.

_packages\graphql-codegen-cli\src\codegen.ts_
```typescript
outputSchema = parse(printSchemaWithDirectives(outputSchemaAst));
```

* `apollo-angular-plugin` implements `addToSchema`, which sets `schemaChanged` flag to true (_packages\graphql-codegen-core\src\codegen.ts_)
* `schemaChanged` executes `options.schemaAst = buildASTSchema(schema, ...)`
* new `options.schemaAst` has `astNode` set to undefined, since it was stripped out earlier.

This is a test which reproduces the error:

_codegen.spec.ts_
```typescript
    it('Should allow plugins to extend schema with custom root', async () => {
      try {
        const output = await executeCodegen({
          schema: `schema { query: RootQuery } type MyType { f: String } type RootQuery { f: String }`,
          documents: `query root { f }`,
          generates: {
            'out1.ts': ['./tests/custom-plugins/extends-schema.js', './tests/custom-plugins/checks-extended-schema.js'],
          },
        });
        expect(output.length).toBe(1);
      } catch (e) {
        expect(e.errors[0].message).not.toBe('Query root type must be provided.');
      }
    });
```

I hope this helps.

**Comment by ardatan** [comment] 2020-01-21 01:29
Fix available in `1.11.3-alpha-99a57a5b.45` and your test case passes :)

**Comment by priley86** [comment] 2020-01-22 03:53
hi, believe I am hitting the same issue here. And this fix seems to work for my query root, however it does not work for my Mutation root. Can a similar fix also be applied for mutations? Would be yuge for me and maybe some others...

**Comment by priley86** [comment] 2020-01-22 04:06
was actually merging schemas in my case:
```
schema:
  - './src/graphql/schema.json'
  - './src/graphql/localSchema.graphql'
```

My introspected schema had:
```
schema {
  query: QueriesHolder
  mutation: MutationsHolder
}
```

whereas my localSchema was defining `Query` and `Mutation` type. My current workaround is to just use the same name and things check out OK i guess. Not sure if this is anticipated or not though... 

afterward:
```
type User {
  id: ID!
  name: String!
}

type QueriesHolder {
  me: User
  users: [User!]!
}

type SignInResponse {
  id: ID
  authToken: String
}

type MutationsHolder {
  signIn(username: String!, password: String!): SignInResponse
}

schema {
  query: QueriesHolder
  mutation: MutationsHolder
}

```

**Comment by dotansimha** [comment] 2020-01-28 09:44
@priley86 can you please share a reproduction in a new issue?

**Comment by dotansimha** [comment] 2020-01-28 15:36
Fixed in `v1.12.0`

**Closed by dotansimha** 2020-01-28 15:36 UTC
Labels: bug, core, waiting-for-release

**Comment by CarlosGines** [comment] 2020-02-05 21:43
Hi! I think I am hitting the same problem about merging schemas that @priley86 mentions in their second comment.

If I merge 2 schemas:
```yml
schema:
  - schema.graphql
  - schema2.graphql
```

With different query roots types:
```graphql
schema {
    query: RootQuery
}
```
\+
```graphql
schema {
    query: Query # default root query, same as not providing any `schema` definition
}
```

Only one of the query root types prevails, so queries of the overwritten query root type fail.

**To Reproduce**
https://codesandbox.io/s/mergingschemaswithdifferentroots-3honc
Go to `codegen.yml` and uncomment the `document` line to see how it fail.

**Comment by ardatan** [comment] 2020-02-05 23:03
@CarlosGines I think the behavior is correct because you have one schema definition which is 
```gql
schema {
    query: RootQuery
}
```
and codegen takes `RootQuery` as `query` type.

**Comment by CarlosGines** [comment] 2020-02-06 09:46
@ardatan I will slightly update the codesandbox to better demonstrate the issue: if we use 2 different `schema` definitions, there is not way to properly merge the schemas.

**Comment by Katona** [comment] 2022-11-02 13:50
I have the same issue like @CarlosGines, having two graphql schema and only one root query type is working.

**Comment by ardatan** [comment] 2022-11-02 14:39
This issue is from 2020. Could you please create a new one with a reproduction?
