### ISSUE TITLE
More verbose error messages.

### ISSUE THREAD

**Issue by wesselvdv** [dotansimha/graphql-code-generator#925] opened 2018-11-26 13:30 UTC
**Is your feature request related to a problem? Please describe.**
Currently it's quite difficult to discern what exactly is going wrong if there's an error. Error messages are simply along the lines of: `An error has occurred in one of your documents.`

**Describe the solution you'd like**
I'd prefer the ability to either set a flag that makes it more verbose, or simply enable it by default to include the exact file and lines that are erroneous.

**Comment by thekevinbrown** [comment] 2018-11-29 08:00
I'm having trouble with the download of a remote schema failing, and I don't know exactly what it's trying to download, nor do I know what the server is saying back. It'd be awesome if there was a --debug flag or something so I could see what it's doing to help me troubleshoot.

**Comment by dotansimha** [comment] 2018-12-04 00:39
In https://github.com/dotansimha/graphql-code-generator/issues/953, @kroeder mentioned that it works fine with PowerShell instead of CMD, so I guess this issue is related only to Windows. 
@wesselvdv @thekevinbrown do you use Windows as well?

**Comment by kroeder** [comment] 2018-12-04 05:50
*it works with power shell, not with git bash, using it as webstorm terminal (but on windows)

Just do be 100% exact :)

**Comment by thekevinbrown** [comment] 2018-12-04 10:18
@dotansimha No, I'm on OS X.

The request is for a way to see what the tool is doing under the hood in the form of logs via some kind of `--debug` flag though, so I don't know what about that need is platform dependent.

**Comment by wesselvdv** [comment] 2018-12-04 11:00
@dotansimha Nope, i'm on macOS Mojave, and using PHPStorm terminal. I had to manually place some console.log statements to figure out where stuff was going awry. I almost seems as if the logging is cutoff at a newline, because only the start of an error message is shown.

**Comment by dotansimha** [comment] 2018-12-05 01:03
@thekevinbrown makes sense, we had it before v0.14 and I think we need to add it back. 

@wesselvdv @thekevinbrown which shell do you use? I'm also using Mac OS Mojave and I can see the errors using https://github.com/robbyrussell/oh-my-zsh shell.

**Comment by wesselvdv** [comment] 2018-12-05 06:59
@dotansimha I’m using bash

**Comment by colinfindlay-nz** [comment] 2018-12-06 01:21
I'm on Windows - and the most I can get out of it is: `Found 2 errors in your documents`
I can see that the validator throws a `DetailedError` which the actual detail - but I can't gql-gen to actually log it. (unless I hack the source)

**Comment by dotansimha** [comment] 2018-12-13 10:13
Fixed in 0.15. Please re-open if the issue persist.

**Comment by valerybugakov** [comment] 2018-12-21 15:09
@dotansimha got the same issue on 0.15.1, output just says: `→ Found 2 errors in your documents`

I'm on Mojave with `on-my-zsh` shell. Any suggestions?

**Comment by valerybugakov** [comment] 2018-12-21 15:12
@dotansimha update: we use `concurrently` package to run `gql-gen` and a couple of other tasks in parallel. It's not working with it, but a standalone command works fine.

**Comment by jagregory** [comment] 2018-12-21 18:58
Same situation here. Running in Concurrently hides the error details.

From a brief bit of investigation I think it’s when there’s no TTY to the process, the listr renderer behaves differently.

**Comment by statico** [comment] 2019-02-04 20:56
I don't think this issue is closed. If there's no TTY, the output remains unhelpful.

I'm using v0.16:

```
〉yarn list --pattern code-gen
yarn list v1.13.0
└─ graphql-code-generator@0.16.1
✨  Done in 0.49s.
```

Running the generator gives me:

```
〉./node_modules/.bin/gql-gen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./generated/types.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Found 1 error in your documents!


  Found 1 error

   ✖ ./generated/types.ts
    Error: Found 1 error in your documents!


Something went wrong
```

And removing the TTY doesn't tell me much else:

```
〉./node_modules/.bin/gql-gen | cat
[12:54:24] Parse configuration [started]
[12:54:24] Parse configuration [completed]
[12:54:24] Generate outputs [started]
[12:54:24] Generate ./generated/types.ts [started]
[12:54:24] Load GraphQL schemas [started]
[12:54:24] Load GraphQL schemas [completed]
[12:54:24] Load GraphQL documents [started]
[12:54:25] Load GraphQL documents [completed]
[12:54:25] Generate [started]
[12:54:25] Generate [failed]
[12:54:25] → Found 1 error in your documents!
[12:54:25] Generate ./generated/types.ts [failed]
[12:54:25] → Found 1 error in your documents!
[12:54:25] Generate outputs [failed]
Something went wrong
```

And my types file is never generated:

```
〉ls generated/types.ts
ls: generated/types.ts: No such file or directory
```

**Comment by statico** [comment] 2019-02-04 21:41
FWIW, I was able to figure out my bug by editing `node_modules/graphql-code-generator/dist/execute-plugin.js` and adding a `console.log()`:

![image](https://user-images.githubusercontent.com/137158/52238929-0ff3b480-2882-11e9-9718-71ab9af35923.png)

Then I was able to see:

```[ { filePath: '../frontend/lib/queries.ts',
    errors: [ [GraphQLError] ] } ]
  ✔ Parse configuration
  ❯ Generate outputs
```

The file is currently this:

```import { gql } from 'apollo-boost'
import { USER_PARTS } from './fragments'

export const WHO_AM_I = gql`
  query WhoAmI {
    me {
      ...UserParts
      verified
    }
  }
  ${USER_PARTS}
`
```

The error was due to my adding a `verified` property to my GraphQL query. Removing that property in the query makes the code generator work. I would expect to see such an explanation in the error output.

I hope this is useful.

The code generator is awesome. Keep up the great work!

**Comment by seamusv** [comment] 2019-02-05 00:02
> FWIW, I was able to figure out my bug by editing `node_modules/graphql-code-generator/dist/execute-plugin.js` and adding a `console.log()`:

I changed your code to be `console.log(JSON.stringify(errors));` so that I could see the expanded error messages.

**Comment by wesselvdv** [comment] 2019-02-05 06:42
@dotansimha You can actually easily reproduce this by executing this without attaching an tty and then attaching to the output.
 
I am running gql-gen inside a alpine docker container so I had to manuslly designate a pseudo-tty to get logging output, not sure how to this in the terminal. Maybe running it in background? (&)

**Comment by dotomaz** [comment] 2019-02-06 13:14
I Have the same issue. I've tracked the problem to [checkValidationErrors in graphql-toolkit](https://github.com/dotansimha/graphql-toolkit/blob/47a76be7c4eb85f092928b8a15c85f07fa9d0fe6/src/utils/validate-documents.ts#L35)

Problem is in `throw new Error("Found " + errorCount + " error" + (errorCount > 1 ? 's' : '') + " in your documents!");`. The function collects the errors but does not pass them to the exception.

This did the trick for me: 
`throw new Error("Found " + errorCount + " error" + (errorCount > 1 ? 's' : '') + " in your documents!" + errors.join());`

**Comment by SimenB** [comment] 2019-02-06 13:19
Should probably use https://github.com/sindresorhus/aggregate-error or something similar

**Comment by williamluke4** [comment] 2019-02-10 11:21
```
errors.map(error => {
                            console.error(`Error in: ${error.filePath}`);
                            error.errors.map(e => {
                                console.error(`- ${e.message}`);
                            })
                        })
```

**Comment by jrr** [comment] 2019-02-13 16:37
I wound up writing something like @williamluke4:

```js
errors.forEach(file => {
    console.warn(`${file.filePath}:`);
    file.errors.forEach(e =>{
        const locs = e.locations.map(l => `${l.line}:${l.column}`).join(", ")
        console.warn(`  ${e.message} (line ${locs})`);
    })
})
```

Running with e.g. `./node_modules/.bin/gql-gen |less`, this will present errors like this:

```
modules/client/graphql/queries/FooBar.graphql:
  Variable "$baz is not defined by operation "FooBar". (line 2:15, 1:1)
```

Hopefully this helps others get unstuck, but for graphql-code-generator we should figure out how to present errors nicely both with and without a TTY.

For now, a quick and easy way to get _something_ in both scenarios is to catch the exception from graphql-toolkit's  `checkValidationErrors()` and rethrow with more detail:

```js
try {
    graphql_toolkit_1.checkValidationErrors(errors);
} catch (e) {
    const errorsString = errors.map(file => {
        return `  ${file.filePath}:\n` +
            file.errors.map(err => {
                const locs = err.locations.map(l => `${l.line}:${l.column}`).join(", ")
                    return `  ${err.message} (line ${locs})`
            }).join("\n")
    }).join("\n")
    throw new Error(errorsString)
}
```

**Comment by leonardorb** [comment] 2019-02-16 18:45
This will be a nice addition. Thanks everyone for pointing solutions. This saved me. 😃

**Comment by cgatian** [comment] 2019-02-22 15:31
Good god please fix this. I love you guys but this makes be cry.

**Comment by dotansimha** [comment] 2019-02-27 08:48
Thank you all and sorry for the inconvenience. @DAB0mB is working on a fix now :)

**Comment by dotansimha** [comment] 2019-02-28 07:06
Fixed in `graphql-toolkit`, PR here: https://github.com/dotansimha/graphql-code-generator/pull/1370

**Comment by DAB0mB** [comment] 2019-02-28 08:56
I'm adding tests to codegen and then we can release

**Comment by dotansimha** [comment] 2019-03-01 10:27
Fixed in 0.18.0 🎉

**Closed by dotansimha** 2019-03-01 10:27 UTC
Labels: bug, core

**Comment by wesselvdv** [comment] 2021-02-11 19:11
This seems to be an issue again, :-( Not sure when it was re-introduced but running gql-gen in a docker container without a pseudo-tty will no longer provide meaningfull error messages.

**Comment by dotansimha** [comment] 2021-03-07 17:38
@wesselvdv Any chance you can share more info? Which version are you using, and what is the cause for the error you had? It will really help us to improve and fix that!

**Comment by jokerosky** [comment] 2023-02-13 09:38
Have the same problem.

  "@graphql-codegen/cli": "3.0.0",
  "@graphql-codegen/typescript": "3.0.0",
  "@graphql-codegen/typescript-document-nodes": "3.0.0",
  "@graphql-codegen/typescript-operations": "3.0.0",
  
 Windows 11, Node v18.1.0

output looks like this:
  
```
yarn run regenerate-schema
yarn run v1.22.18
$ graphql-codegen --config graphql-codegen.yml
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to src/shared/graphql.ts
    ✔ Load GraphQL schemas
    ✔ Load GraphQL documents
    ✖ GraphQL Document Validation failed with 1 errors;
      Error 0: Fields "identifier" confli…
error Command failed with exit code 1.
```
  
Not much info... 
"Solved" as described above, with adding console.log to **\node_modules\@graphql-codegen\core\cjs\codegen.js**

**Comment by afestbaum** [comment] 2023-03-09 16:17
> Have the same problem.
> 
> "@graphql-codegen/cli": "3.0.0", "@graphql-codegen/typescript": "3.0.0", "@graphql-codegen/typescript-document-nodes": "3.0.0", "@graphql-codegen/typescript-operations": "3.0.0",
> 
> Windows 11, Node v18.1.0
> 
> output looks like this:
> 
> ```
> yarn run regenerate-schema
> yarn run v1.22.18
> $ graphql-codegen --config graphql-codegen.yml
> ✔ Parse Configuration
> ⚠ Generate outputs
>   ❯ Generate to src/shared/graphql.ts
>     ✔ Load GraphQL schemas
>     ✔ Load GraphQL documents
>     ✖ GraphQL Document Validation failed with 1 errors;
>       Error 0: Fields "identifier" confli…
> error Command failed with exit code 1.
> ```
> 
> Not much info... "Solved" as described above, with adding console.log to **\node_modules@graphql-codegen\core\cjs\codegen.js**

We've encountered the same issue in our team and traced it down to a downstream change. codegen-cli makes use of the listr2 package to render the console output. Listr2 made in change beginning with v3.3.0 introducing the "formatOutput" render-parameter on its DefaultRenderer with the default option of "truncate". This truncates any output that exceeds the current console width...
2 possible solutions here...

- quick user side fix: configure your codegen session with "verbose: true" as this uses some unformatted console output
- fix for the developers: set the formatOutput to "wrap" on the renderOptions in the codegen.ts file

Cheers
Alex

**Comment by XxQuickSilverZz** [comment] 2023-05-23 16:20
Fixed it with 

 if (errors.length > 0) {
       console.log(errors)
       throw new Error(`GraphQL Document Validation failed with ${errors.length} errors;`)
}

# LINE 82
in ...node_modules\@graphql-codegen\core\cjs\codegen.js

**Comment by hamedtahmasebi** [comment] 2023-07-30 09:35
Setting `verbose:true` in config file fixed this for me

**Comment by johnknoop** [comment] 2023-10-23 14:55
> * fix for the developers: set the formatOutput to "wrap" on the renderOptions in the codegen.ts file

Is anyone working on this?
