### ISSUE TITLE
What's the difference between this library and Apollo Code Generator?

### ISSUE THREAD

**Issue by bhaidar** [dotansimha/graphql-code-generator#1324] opened 2019-02-21 11:17 UTC
Hello,
I am interested to know the difference between this library and Apollo Code Generator. 

Thanks

**Comment by dotansimha** [comment] 2019-02-21 17:07
Duplicate of https://github.com/dotansimha/graphql-code-generator/issues/118

**Closed by dotansimha** 2019-02-21 17:07 UTC
