### ISSUE TITLE
Quickstart needs ts-node

### ISSUE THREAD

**Issue by brandon-leapyear** [dotansimha/graphql-code-generator#8685] opened 2022-12-02 20:43 UTC
### Describe the bug

The quickstart in the README + website are both missing `yarn add -D ts-node`, which is needed as a peer dependency of `@graphql-codegen/cli`.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. `yarn set version stable`
2. `yarn add graphql && yarn add -D typescript && yarn add -D @graphql-codegen/cli`
3. `yarn graphql-codegen init`

```
Error: cosmiconfig-typescript-loader tried to access ts-node (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: ts-node
Required by: cosmiconfig-typescript-loader@virtual:c2008e4899b4ad3fb5e4082351d2290b40b46638c098d3b98067292e092b49aedc20e75b2d0d7299469f1f327eadef39c959b82821fc471e0d7c154a6d82f2ad#npm:4.1.1 (via /Users/bchinn/Desktop/foo/.yarn/__virtual__/cosmiconfig-typescript-loader-virtual-33f90becc5/0/cache/cosmiconfig-typescript-loader-npm-4.1.1-77b25222d1-a774961868.zip/node_modules/cosmiconfig-typescript-loader/dist/cjs/)

Ancestor breaking the chain: @graphql-codegen/cli@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:2.15.0
```

### Expected behavior

Should work

### Platform

- OS: macOS
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by saihaj** [comment] 2022-12-02 20:47
There is nothing in CLI that uses `ts-node`. I build and run it with just `node` and works fine. Only `peerDep` we have is `graphql`

https://github.com/dotansimha/graphql-code-generator/blob/224a5362ca26952aeab6947db18623efa69eb96e/packages/graphql-codegen-cli/package.json#L42-L94

**Comment by brandon-leapyear** [comment] 2022-12-02 20:51
The CLI uses `cosmiconfig-typescript-loader` which uses `ts-node`:
https://github.com/dotansimha/graphql-code-generator/blob/224a5362ca26952aeab6947db18623efa69eb96e/packages/graphql-codegen-cli/src/config.ts#L77-L79

It fails on Yarn because Yarn uses PnP and errors if packages try to access a package they don't mention in their dependencies:
https://yarnpkg.com/getting-started/migration#fix-dependencies-with-packageextensions

Did you try running through the repro steps I had in the issue?

**Comment by sjdemartini** [comment] 2022-12-13 01:19
I'm also experiencing this, and it appears to be a duplicate of this slightly older open issue https://github.com/dotansimha/graphql-code-generator/issues/8462.

Per https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency, this is a problem that should be fixed by `@graphq-codegen/cli` to resolve the various missing peer deps requested by its dependencies, so that the manual `packageExtensions` workaround in yarn isn't needed to patch it. 

Here's the `yarn install` output with yarn 2+:

```
➤ YN0002: │ @graphql-codegen/cli@npm:2.16.1 [d9650] doesn't provide @types/node (p8dcee), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-codegen/cli@npm:2.16.1 [d9650] doesn't provide ts-node (p32fa9), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-codegen/cli@npm:2.16.1 [d9650] doesn't provide typescript (p51647), requested by cosmiconfig-typescript-loader
```

**Comment by louisscruz** [comment] 2022-12-30 22:29
I'm also hitting this issue in a fresh project on Yarn 3.

The workaround listed above should be:

```yml
packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "ts-node": "*"
```

The above should be added to your `.yarnrc.yml` and run `yarn` for the extension to kick in.

**Comment by louisscruz** [comment] 2022-12-30 22:59
PR for a fix over here: https://github.com/dotansimha/graphql-code-generator/pull/8779

**Comment by saihaj** [comment] 2023-01-04 16:40
https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1672850402615

**Closed by saihaj** 2023-01-04 16:40 UTC
Labels: core, stage/0-issue-prerequisites
