### ISSUE TITLE
Support new mutation hook interface once it's released

### ISSUE THREAD

**Issue by kirill-konshin** [dotansimha/graphql-code-generator#1736] opened 2019-04-17 23:54 UTC
https://github.com/trojanowski/react-apollo-hooks/pull/93

This is a very much needed functionality... hope codegen package will adopt it.

**Comment by ardatan** [comment] 2019-04-18 10:42
I believe it will work correctly because we don't redefine complete signature of hook function. Let's keep it open until it's released and confirmed.

**Comment by kirill-konshin** [comment] 2019-05-03 22:08
It seems to be working fine with latest alpha.

**Comment by dotansimha** [comment] 2019-05-07 07:45
Awesome! Thank you @kirill-konshin , I guess we can close it for now. Feel free to open a new issue if something changes.

**Closed by dotansimha** 2019-05-07 07:45 UTC
Labels: enhancement, templates
