### ISSUE TITLE
[near-operations-file] Import of main types sometimes added to queries where it isn't needed

### ISSUE THREAD

**Issue by mvestergaard** [dotansimha/graphql-code-generator#2729] opened 2019-10-10 18:20 UTC
Relates to #2137
This problem seems to be back in `1.8.1`, or at least something related.

```
query {
  user {
    ...UserFragment
  }
}
```
Results in the `Types` import being added, even though it isn't used.
```
query {
  user {
    id
    ...UserFragment
  }
}
```
Also adds the `Types` import, but uses it.

This is problematic when typescript is configured to error on unused imports.

**Comment by SimenB** [comment] 2020-05-28 09:56
Would love to see this solved, as we cannot use this preset with `noUnusedLocals: true` in `tsconfig.json`. Removing `preResolveTypes: true` also works.

Workaround I landed on (inspired by OP) is to duplicate a field from the fragment that uses `Types` (something optional, meaning `Types.Maybe` is used).

**Comment by dotansimha** [comment] 2020-05-31 08:56
It's a bit tricky because it effects other use-cases. We are trying to find the actual specific use-cases that causes that. 
@SimenB @mvestergaard can you please share a reproduction?

**Comment by SimenB** [comment] 2020-06-18 12:14
This was "fixed" for us by #4194 injecting usage of `Types.Exact`

**Closed** 2020-11-05 08:32 UTC
Labels: bug, needs reproduction, plugins

**Comment by SimenB** [comment] 2020-11-05 08:52
This resurfaced for us, btw. Weære back to adding dummy queries to work around it. I'll try to put together a reproduction

**Comment by dotansimha** [comment] 2020-11-05 09:06
@SimenB sure, waiting for a reproduction. Thanks!

**Comment by SimenB** [comment] 2020-11-05 09:42
@dotansimha https://github.com/SimenB/codegen-extra-imports

**Comment by SimenB** [comment] 2020-11-09 14:33
@dotansimha reopen this, or should I file a new issue?

**Comment by dotansimha** [comment] 2020-11-16 21:12
> @dotansimha reopen this, or should I file a new issue?

New issue :)

**Comment by SimenB** [comment] 2020-11-17 11:12
#5094
