### ISSUE TITLE
Add a --dry-run option

### ISSUE THREAD

**Issue by justinwaite** [dotansimha/graphql-code-generator#4725] opened 2020-09-09 22:26 UTC
**Is your feature request related to a problem? Please describe.**

The problem is that a developer could forget to run the code generator, or forget to keep it in watch mode, and then commit operations to master that don't have associated types with them. Then another developer comes along and wonders why their PR has a bunch of types generated that are unrelated to the work they were doing. 

**Describe the solution you'd like**

This _could_ be handled using lint-staged if there was a way to possibly do a dry-run and a non-zero exit if there are types that need to be generated. Then in a pre-commit hook, the developer would be warned that there are types that must be generated. This could also be used in a CI/CD environment and fail if necessary.

**Describe alternatives you've considered**

I tried using lint-staged and just automatically add the generated files with git, but that could lead to unforeseen issues, and quite frankly I couldn't get it to work.

**Additional context**

**Comment by dotansimha** [comment] 2020-09-28 08:29
Thank you for this suggestion @justinwaite . 
In most setups, I think it's better to avoid committing generated files to git. But regardless of that, I think adding this kind of flag could help.

**Comment by nandorojo** [comment] 2022-07-19 17:59
I'd love to `--dry-run` so from my CI, just to confirm that the app's schema is valid, without generating any actual files.

**Comment by charlypoly** [comment] 2022-07-27 08:11
Duplicate of https://github.com/dotansimha/graphql-code-generator/issues/2872

Merging the issues together

**Closed by charlypoly** 2022-07-27 08:11 UTC
Labels: core, kind/enhancement

**Comment by charlypoly** [comment] 2022-07-27 13:13
The dry-run mode is now available via the `--check` CLI flag, from `@graphql-codegen/cli@2.11.0` 📦
