### ISSUE TITLE
Property 'X' does not exist on type 'ResolverTypeWrapper<Y>'

### ISSUE THREAD

**Issue by janhartmann** [dotansimha/graphql-code-generator#2124] opened 2019-07-08 07:27 UTC
**Describe the bug**
After upgrading to:

```
"@graphql-codegen/cli": "^1.3.1",
"@graphql-codegen/fragment-matcher": "^1.3.1",
"@graphql-codegen/typescript-operations": "^1.3.1",
"@graphql-codegen/typescript-resolvers": "^1.3.1",
```

I am experiencing errors in my unit tests where an array is used:

```ts
describe("connection.outputs", () => {
    it("returns the outputs from the response", async () => {
      const unitApiResponse: IUnitApiResponse = {
        id: 1,
        outputs: [
          {
            field: "FakeField1",
            label: "FakeLabel1",
            value: "FakeValue1"
          }
        ]
      };
      const resolver = mockResolver(unitConnectionsResolver.outputs);
      const result = await resolver(unitApiResponse);
      expect(result[0].field).toEqual("FakeField1"); //
      expect(result[0].label).toEqual("FakeLabel1");
      expect(result[0].value).toEqual("FakeValue1");
    });
  });
```

When accessing the `result[0]` i am getting: 

```
Property 'field' does not exist on type 'ResolverTypeWrapper<UnitConnection>'.
  Property 'field' does not exist on type 'Promise<UnitConnection>'.
```

The result of `result` is:

```
ResolverTypeWrapper<UnitConnection>[]
```

Where I believe it should be:

```
ResolverTypeWrapper<UnitConnection[]>
```

My implementation of `mockResolver` is the following:

```ts
import {
  Resolver,
  StitchingResolver
} from "../../src/resolvers/generated-types";

type MockResolverFn<TResult, TParent, TArgs, TCtx> = (
  parent?: TParent,
  args?: TArgs,
  context?: TCtx,
  info?: any
) => Promise<TResult> | TResult;

interface IMockStitchingResolver<TResult, TParent, TArgs, TCtx> {
  fragment: string;
  resolve: MockResolverFn<TResult, TParent, TArgs, TCtx>;
}

export function mockResolver<TResult, TParent, TContext, TArgs>(
  resolver: Resolver<TResult, TParent, TContext, TArgs>
): MockResolverFn<TResult, TParent, TArgs, TContext>;

export function mockResolver<TResult, TParent, TContext, TArgs>(
  resolver: Resolver<TResult, TParent, TContext, TArgs>,
  isStitching: boolean
): IMockStitchingResolver<TResult, TParent, TArgs, TContext>;

export function mockResolver<TResult, TParent, TContext, TArgs>(
  resolver: Resolver<TResult, TParent, TContext, TArgs>,
  useStitching?: boolean
):
  | MockResolverFn<TResult, TParent, TArgs, TContext>
  | IMockStitchingResolver<TResult, TParent, TArgs, TContext> {
  if (
    isStitching<StitchingResolver<TResult, TParent, TContext, TArgs>>(
      resolver,
      useStitching
    )
  ) {
    return {
      fragment: resolver.fragment,
      resolve: (parent, args, context, info) =>
        resolver.resolve(parent, args, context, info)
    };
  }

  return (parent, args, context, info) => resolver(parent, args, context, info);
}

function isStitching<T>(resolver: any, useStitching: boolean): resolver is T {
  return useStitching === true;
}
```

**Comment by dotansimha** [comment] 2019-07-31 10:14
@kamilkisiela can you please take a look? I think it should be easy to reproduce.

**Comment by kamilkisiela** [comment] 2019-08-01 09:42
```ts
namespace resolverTypeWrapper {
  type TypeOfWrappedResolver<T extends ResolverTypeWrapper<any>> = T extends ResolverTypeWrapper<infer R> ? R : T;
  type FromMaybe<T> = T extends Maybe<ResolverTypeWrapper<infer R>> ? Maybe<R> : TypeOfWrappedResolver<T>;
  type FromArray<T> = T extends Array<ResolverTypeWrapper<infer R>> ? Array<R> : FromMaybe<T>;
  type FromArrayOfMaybe<T> = T extends Array<Maybe<ResolverTypeWrapper<infer R>>> ? Array<Maybe<R>> : FromArray<T>;
  type FromMaybeOfArrayOfMaybe<T> = T extends Maybe<Array<Maybe<ResolverTypeWrapper<infer R>>>> ? Maybe<Array<Maybe<R>>> : FromArrayOfMaybe<T>;

  export type Remove<T> = FromMaybeOfArrayOfMaybe<T>;
}

export function removeResolverTypeWrapper<T>(result: T): resolverTypeWrapper.Remove<T> {
  return result as resolverTypeWrapper.Remove<T>;
}
```

and then

```ts
const result = removeResolverTypeWrapper(await resolver(unitApiResponse));

expect(result[0].field).toEqual("FakeField1"); // should be fine
```

**Comment by kamilkisiela** [comment] 2019-08-01 10:08
Let me explain why it's `ResolverTypeWrapper<UnitConnection>[]` and not `ResolverTypeWrapper<UnitConnection[]>`.


`ResolverTypeWrapper<T>` turns `T` into `Promise<T>` or `T` and that's because GraphQL's resolver can return: 
 - Promise of an array
 - array
 - array of Promises

and also:

 - Promise of an object/primitive value
 - primitive value / object


Because `T` represents an object, a primitive value or even an array in some cases we need to make sure it also supports promises.

That's why the possible results of `type Query { posts: [Post] }` are:
- `Array<Post>`
- `Promise<Array<Post>>`
- `Array<Promise<Post>>`
- `Promise<Array<Promise<Post>>>`

Here's a proof:

https://stackblitz.com/edit/graphql-i-promise?file=index.ts

**Comment by dotansimha** [comment] 2019-08-01 11:33
Thanks @kamilkisiela . Closing for now, @janhartmann feel free to re-open if it's still relevant.

**Closed by dotansimha** 2019-08-01 11:33 UTC
Labels: bug, templates
