### ISSUE TITLE
`pluckConfig` doesn't seem to work for multiple output files

### ISSUE THREAD

**Issue by davidleger95** [dotansimha/graphql-code-generator#3855] opened 2020-04-10 22:04 UTC
**Describe the bug**
 
`pluckConfig` works at the root config, but when placed in the config for an individual output file, it doesn't seem to work.

**To Reproduce**

1. Create a `codegen.yml` with multiple output files for generating TS types.
2. Set the `pluckConfig` for an output file to only look for `gql` tags.
3. Run `graphql-codegen` on a project with both `graphql` and `gql` tags.

Result: Queries with `graphql` tags are not excluded in the generated types.

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

Here's my Code Sandbox of the issue:

[![Edit graphql-codegen-issue-template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template/tree/master/?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

Only queries tagged with `gql` should be analyzed.

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by ardatan** [comment] 2020-04-11 19:03
```yml
schema: schema.graphql
documents: document.js
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
pluckConfig:
  modules:
    - name: ./foo
```
`pluckConfig` should be on root. It is listed together with `schema` and `documents` here;
https://graphql-code-generator.com/docs/getting-started/codegen-config
And `identifier` means export name.
https://codesandbox.io/s/goofy-https-vefyz?file=/codegen.yml:0-173

**Comment by ardatan** [comment] 2020-04-11 19:05
Could you check the sandbox because I don't see anything related to tag pluck in that sandbox?

**Comment by dotansimha** [comment] 2020-05-03 07:23
Closing. @davidleger95 please check reproduction if the issue still persists.

**Closed by dotansimha** 2020-05-03 07:23 UTC
Labels: question, waiting-for-answer

**Comment by saiichihashimoto** [comment] 2022-03-22 05:06
This issue still exists. The issue is that `pluckConfig` must be at the root level, but can't be at the output level. Meaning, if I want a `pluckConfig` for a specific output, then I have to make a new `yml` file and run codegen for that separately. In my case, I want to pull an external schema to make typed queries against, but of course the `gql` tags between the two cause issues.

**Comment by Urigo** [comment] 2022-03-24 19:15
@saiichihashimoto could you open a new issue with a reproduction?
thanks!
