### ISSUE TITLE
Gatsbyjs with Apollo

### ISSUE THREAD

**Issue by endigo** [dotansimha/graphql-code-generator#2092] opened 2019-07-02 07:47 UTC
There are 2 types of queries, mutations, and subscription.

How to generate types not depending on each other.

```yml
overwrite: true
generates:
 # for Gatsby.js
  src/generated/graphqlTypes.ts:
    schema: http://localhost:8000/__graphql
    documents:
      - ./src/**/*.{ts,tsx}
      - ./node_modules/gatsby-*/**/*.js
    plugins:
      - "typescript"
    config:
      gqlImport: gatsby#graphql
   # for react-apollo
  src/generated/types.ts:
    schema:
      - http://graphql.example.com/graphql:
    documents: ./src/**/*.{ts,tsx}
    plugins:
      - "typescript"
      - "typescript-operations"

```
```js
// gatsby-config.js
{
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "hasura",
        fieldName: "hasura",
        createLink: () => {
          return createHttpLink({
            uri: process.env.GATSBY_BACKEND_ENDPOINT + "/v1/graphql",
          });
        }
      }
    },
```

```ts
// apollo mutation
const mutation = gql`
  mutation CREATE_ORGANIZATION_REQUEST($data: organizations_insert_input!) {
    insert_organizations(objects: [$data]) {
      returning {
        id
        name
      }
    }
  }
`;
```
Error is
``` bash
GraphQLDocumentError: Unknown type "organizations_insert_input". Did you m
ean "hasura_organizations_insert_input", "hasura_files_insert_input", "hasura_orga
nizations_set_input", "hasura_authors_insert_input", or "hasura_roles_insert_input
"?
```
```

**Comment by dotansimha** [comment] 2019-07-03 10:39
Hi @endigo 
Are you sure your schema contains the `input organizations_insert_input`? It seems like it doesn't getting loaded from your schema. Can you find it in GraphiQL/Playground docs?

**Comment by endigo** [comment] 2019-07-05 00:52
Sure, my schema contains the input.

I used ```gatsby-source-graphql``` with gatsby config.
And I use ```apollo-graphql``` with clientside. So 2 different access to my graphql endpoint.

Queries, mutations are 2 different rootType.
```ts
// with-gatsby
query {
  hasura {
    products {
....
```

```ts
// with-apollo
// there is no hasura type
query {
  products {
....
```

**Comment by dotansimha** [comment] 2019-07-05 07:55
I understand, but note that the Codegen only loads the schema you provide, and then run `validate` (or `graphql`) with your documents. It means that there is a document in your code that uses types that does not exists in your schema. 
Can you please create a repo/sandbox with reproduction?

**Comment by endigo** [comment] 2019-07-06 02:37
Here is the repo
```
https://github.com/endigo/gatsby-apollo-demo
```

**Comment by dotansimha** [comment] 2019-07-06 08:03
@endigo I think your client side is doing some transformations and manipulations to your documents, and create a different query in runtime. 
I tried to run your example locally, and I opened `/__graphql` and searched for this input type: `organizations_insert_input` - it does not exists. 
The codegen only consumes the final GraphQL schema, and your operations as you provide them. If your client consumer code does manipulations to the query before running it - it might not work with the codegen. 

I even tried to run your exact operation, and got the same error as the codegen:

![image](https://user-images.githubusercontent.com/3680083/60753598-9e10ca00-9fdd-11e9-895b-5f950283a4dd.png)

**Comment by endigo** [comment] 2019-07-06 10:07
Yes, there is no ```organizations_insert_input``` type because that's a demo. You should find ```products_insert_input```.

**Comment by endigo** [comment] 2019-07-06 10:13
I need to generate type for hasura and apollo.

There is 2 endpoint.
```https://gatsby-apollo-demo.herokuapp.com/v1/graphql```
```http://localhost:8000/___graphql```

**Comment by endigo** [comment] 2019-07-06 10:16
```graphql``` is imported from ```gatsby```

```gql``` is imported from ```graphql-tag```

**Comment by endigo** [comment] 2019-07-06 10:17
You can access hasura console with this address
https://gatsby-apollo-demo.herokuapp.com/console

**Comment by dotansimha** [comment] 2019-07-06 10:34
Ok, so you have 2 different schemas that doesn't have anything to do with each other? And you want to merge them before or not? 
Do you consume them as 2 separate endpoints, or as one? 
I'm not really sure, but it seems like you are mixing a few things here.
If you wish to have 2 output files, that are not depending on each other, just specify `schema` and `documents` in each one of them.

The codegen can't separate the files found with `./src/**/*.{ts,tsx}`. You tried to specify the same glob so it collects all documents.
You should tell the codegen which documents belong to which endpoint schema.

```yml
  src/generated/graphqlTypes.ts:
    schema: http://localhost:8000/__graphql
    documents:
      - ./src/gatsby-operations/**/*.{ts,tsx}
      - ./node_modules/gatsby-*/**/*.js
    plugins:
      - "typescript"
    config:
      gqlImport: gatsby#graphql
   # for react-apollo
  src/generated/types.ts:
    schema:
      - http://graphql.example.com/graphql:
    documents: ./src/hasura-operations/**/*.{ts,tsx}
    plugins:
      - "typescript"
      - "typescript-operations"
```

**Comment by tbrannam** [comment] 2019-07-25 23:03
I'm looking at something similar - and the inline graphql queries in JS/TS files are tagged with different gql tags, depending on which schema they are working against,  as @endigo mentions.

Is it the case that a gql tag is used to identify what is actually should be evaluated?

**Comment by tbrannam** [comment] 2019-07-25 23:34
Reading the codegen lib it appears that the entire tsx file is passed in for evaluation to graphql validate - It would be nice if a plugin could be used exclude files from evaluation - or perhaps filter the contents of the file down to just the `tag`.  I'd think that the rest of the TS code isn't really evaluated?

**Comment by tbrannam** [comment] 2019-07-26 02:51
Looks like the plugins aren't invoked until files are parsed - so that's not a viable path forward.   

Apollo codegen expresses the idea @endigo is trying to put forward.  `--tag-name`
https://www.apollographql.com/docs/react/features/developer-tooling/#gql-template-support

**Comment by dotansimha** [comment] 2019-07-31 10:04
@tbrannam I'm not sure if I understood, but if you need to customize the tag name and it's package, you can use `pluckConfig`, see: https://github.com/dotansimha/graphql-code-generator/issues/1555#issuecomment-476212983

**Comment by tbrannam** [comment] 2019-08-05 01:51
I'm working on a TS plugin for Gatsby's StaticQuery and useStaticQuery generation - based on a limited subset of the apollo plugin.   One thing that Gatsby doesn't want is to have string templates inside `graphql` tagged data.   It appears that Gatsby doesn't even want Fragments to be inlined into a query.  Would it make sense for the Gatsby plugin to strip all string templates from the output, or should there be a lower-level option in the client-base-visitor to skip adding fragment references into the QueryDocs?

**Comment by tbrannam** [comment] 2019-08-05 14:24
Filtering it out in a post processing on visitor and visitorResults seems to give me what I want - but seems a little goofy.

example: `const filteredFragments = visitor.fragments.replace(/\$\{[\w]+\}/g, '');`

**Comment by dotansimha** [comment] 2019-10-02 05:16
Closing this for now. If there are other issues, please open new issues for each one, with as much info as possible and a reproduction.

Gatsby is doing some changes during runtime for schemas, so I can only recommend the following at the moment:

- For your schema, use the GraphQL endpoint that Gatsby creates for you, it will include all the relevant types.
- For your documents, start with specific files and not with a broad glob expression, because scanning files without knowing that they contain might cause issues (because Gatsby source code contains documents that might not match the schema you have).
- Set `gqlImport: gatsby#graphql` in your config to have a valid documents that matches Gatsby needs. 
- If you are building your GraphQL operations using `gql` tag from a library different from `graphql-tag` - make sure to set `pluckConfig` (see https://github.com/dotansimha/graphql-code-generator/issues/1555#issuecomment-476212983)

**Closed by dotansimha** 2019-10-02 05:16 UTC
Labels: waiting-for-answer
