### ISSUE TITLE
Generate react-apollo components from operations in .tsx files

### ISSUE THREAD

**Issue by JAFong** [dotansimha/graphql-code-generator#1661] opened 2019-04-06 07:05 UTC
I'd like to colocate my GraphQL operations with my React components.  So instead of defining a query in a corresponding `.graphql` file, I would like to use `graphql-tag` to define the same query within a `.tsx` file instead.

I receive the following error
```
  ✖ src/generated/graphql.tsx
    SyntaxError: Unexpected token (1:1)
```

Using this config:
```
overwrite: true
schema: 'http://localhost:3000/graphql'
documents: '**/*.tsx'
generates:
  src/generated/graphql.tsx:
    plugins:
       - add: "/**\n * THIS IS A GENERATED FILE, DO NOT MODIFY DIRECTLY\n */\n"
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'

```

**Comment by dotansimha** [comment] 2019-04-07 08:41
@DAB0mB , can you please take a look? I think it's related to `graphql-tag-pluck`.

**Comment by DAB0mB** [comment] 2019-04-08 03:41
I can't reproduce it and I'm not sure I even understand what your'e trying to do. So basically I setup the same config as you showed and I created the following `.tsx` files with a React.Component a a GraphQL document:

```jsx
const messagesQuery = gql `
  query GetMessages {
    messages {
      ...Message
    }
  }
  ${fragments.message}
`

const MessagesList = () => {
  const { data: { messages } } = useGetMessages()

  // ...
}

export default MessagesList
```

This is not the first time we do that, we also do it with the WhatsApp-Clone. I would need you to elaborate please or write a code snippet that reproduces the issue.

**Comment by dotansimha** [comment] 2019-04-08 05:45
Also, @JAFong , please let us know where do you import `gql` from, and which version of the codegen do you use.

**Comment by dotansimha** [comment] 2019-04-22 08:22
@JAFong I'm closing, please re-open if you're still having issues.

**Closed by dotansimha** 2019-04-22 08:22 UTC
Labels: waiting-for-answer
