### ISSUE TITLE
[cli] can't send custom http headers to server during introspection

### ISSUE THREAD

**Issue by mscharley** [dotansimha/graphql-code-generator#5655] opened 2021-03-04 23:35 UTC
**Describe the bug**
 

After updating to 1.21.1, from 1.20.1. The only version that is changing in this upgrade is for `@graphql-codegen/cli`.

When generating an API client, the introspection step fails. The messages are reminiscent of when I first setup this codegen when I didn't include the custom headers. The other servers I use codegen against that do not have custom HTTP headers are working fine.

The only error message I've been able to get out of the CLI, even with `DEBUG=1` and `VERBOSE=1` is:

```
Failed to find any GraphQL type definitions in: https://api.newrelic.com/graphql - Invalid MIME type
[12:25:45] Load GraphQL schemas [failed]
[12:25:45] → Failed to load schema
[12:25:45] Generate ./src/app/graphql/requests/newrelic.ts [failed]
[12:25:45] → Failed to load schema
```

**To Reproduce**

I can't include my live API credentials but you should be able to reproduce this with any server that only allows introspection when certain HTTP headers are included.

1. My GraphQL schema:

```graphql
# N/A
```

2. My GraphQL operations:

```graphql
fragment entity on Entity {
  __typename
  name
  guid
  entityType
  tags {
    key
    values
  }
  ... on SyntheticMonitorEntity {
    monitorType
    monitorId
    monitoredUrl
    period
  }
}
fragment entityOutline on EntityOutline {
  __typename
  name
  guid
  entityType
  tags {
    key
    values
  }
  ... on SyntheticMonitorEntityOutline {
    monitorType
    monitorId
    monitoredUrl
    period
  }
}
query entitySearch($query: EntitySearchQueryBuilder!) {
  actor {
    entitySearch(queryBuilder: $query) {
      results {
        entities {
          ...entityOutline
        }
        nextCursor
      }
    }
  }
}
query getEntity($id: EntityGuid!) {
  actor {
    entity(guid: $id) {
      ...entity
    }
  }
}
mutation tagEntity ($guid: EntityGuid!, $tags: [TaggingTagInput!]!){
  taggingAddTagsToEntity(guid: $guid, tags: $tags) {
    errors {
      message
      type
    }
  }
}
mutation untagEntity ($guid: EntityGuid!, $tags: [String!]!) {
  taggingDeleteTagFromEntity(guid: $guid, tagKeys: $tags) {
    errors {
      message
      type
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
documents: []

generates:
  ./src/app/graphql/requests/newrelic.ts:
    schema:
      - "https://api.newrelic.com/graphql":
          headers:
            API-Key: ${NEWRELIC_PERSONAL_TOKEN}
            Content-Type: application/json
    documents: "./src/app/graphql/requests/newrelic/*.graphql"
    config:
      avoidOptionals: true
      constEnums: true
      enumsAsTypes: true
      noSchemaStitching: true
      immutableTypes: true
    plugins:
      - typescript
      - typescript-operations
      - "@graphql-codegen/typescript-graphql-request"
require: []
```

**Expected behavior**

For the headers to be included and the graphql introspection to happen successfully.

**Environment:**

- OS: OSX 10.15
- `@graphql-codegen/cli`: "^1.21.1"
- `@graphql-codegen/typescript`: "^1.21.0"
- `@graphql-codegen/typescript-graphql-request`: "^3.0.2"
- `@graphql-codegen/typescript-operations`: "^1.17.14"
- `@graphql-codegen/typescript-resolvers`: "^1.18.2"
- NodeJS: 12.x

**Additional context**

**Comment by dotansimha** [comment] 2021-03-07 14:54
Thank you for reporting it @mscharley ,
I'm not sure how to address this issue, since I think you are the only person who reported it, and we don't have a reproduction we can try to run locally.
Can you please make sure that you are using the latest CLI, and also the latest version of `@graphql-tools/` dependencies?

**Comment by mscharley** [comment] 2021-03-08 00:25
Versions are now this:

```
    "@graphql-codegen/cli": "^1.21.2",
    "@graphql-codegen/typescript": "^1.21.1",
    "@graphql-codegen/typescript-graphql-request": "^3.1.0",
    "@graphql-codegen/typescript-operations": "^1.17.15",
    "@graphql-codegen/typescript-resolvers": "^1.19.0",
```

I did `ls node_modules/@graphql-tools` and then ran `npm update --depth 20 @graphql-tools/apollo-engine-loader @graphql-tools/batch-execute @graphql-tools/code-file-loader @graphql-tools/delegate @graphql-tools/git-loader @graphql-tools/github-loader @graphql-tools/graphql-file-loader @graphql-tools/graphql-tag-pluck @graphql-tools/import @graphql-tools/json-file-loader @graphql-tools/load @graphql-tools/merge @graphql-tools/optimize @graphql-tools/prisma-loader @graphql-tools/relay-operation-optimizer @graphql-tools/schema @graphql-tools/url-loader @graphql-tools/utils @graphql-tools/wrap` to try to update all the transitive dependencies as well but that didn't do anything so I can only assume I'm on the latest allowed versions of all of those tools.

I'll look into seeing if I can spin up a public-facing repro case in the next few days, we don't have a seperate staging account with NewRelic so it's hard for me to give a repro there directly.

**Comment by mscharley** [comment] 2021-03-08 23:51
Heres a simple reproduction: https://github.com/mscharley/codegen-5655-repro

The exact error message is slightly different, but the root cause is the same. Environment variables aren't being passed through properly into the API-Key header. If you use a different API client and set the headers properly then it works.

**Comment by ardatan** [comment] 2021-05-11 05:02
After some fixes in the code, it seems working fine;
https://codesandbox.io/s/smoosh-firefly-wephi?file=/src/index.js
- Changed the endpoint URL (`/graphql` path was missing)
- Fixed dotenv integration in package.json
  - `"codegen": "graphql-codegen --require dotenv/config",`
- Changed the way you return errors
Closing this issue for now. If you still have the same problem, feel free to create a new issue with a new reproduction.

**Closed by ardatan** 2021-05-11 05:02 UTC
Labels: needs reproduction
