### ISSUE TITLE
Invalid documents errors are swallowed and not reported 

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#7323] opened 2022-01-05 13:53 UTC
Context: https://twitter.com/agarithm/status/1478725479678898177

Seems like invalid syntax queries are not being reported.

```graphql
query {
   ...
}
```

![image](https://user-images.githubusercontent.com/3680083/148228642-19678801-03b3-4fe3-add6-7aa8d806fe49.png)

![image](https://user-images.githubusercontent.com/3680083/148228653-b77f430b-529a-475f-91a7-07c31b160d59.png)

![image](https://user-images.githubusercontent.com/3680083/148228671-0527d192-3b43-4d13-ac7f-a0108850c2a5.png)

**Comment by n1ru4l** [comment] 2022-01-31 11:40
As a reference for those who want to see the errors currently:

```bash
DEBUG=1 VERBOSE=1
```

**Comment by n1ru4l** [comment] 2022-01-31 11:42
Expected behaviors:

On CI: Error
Locally Single run: Error
Locally Watch mode: warning

**Comment by Slessi** [comment] 2022-10-25 08:40
I used to be satisfied with the `DEBUG=1` workaround, but since a recent update, the CLI prints a lot of information with `DEBUG=1` which masks errors for me regardless.

Would be nice to get error output for syntax errors without needing to specify `DEBUG=1`

**Comment by charlypoly** [comment] 2022-10-25 12:39
Merged with https://github.com/dotansimha/graphql-code-generator/issues/7323

**Closed by charlypoly** 2022-10-25 12:39 UTC
Labels: stage/0-issue-prerequisites

**Comment by Slessi** [comment] 2022-10-25 13:57
@charlypoly I dont think thats the same issue.

The linked issue is about truncated error messages, but this issue is about syntax errors not being printed at all, unless you specify `DEBUG=1`.

**Comment by charlypoly** [comment] 2022-10-25 14:23
I've merged it with the other issue bc they share the same root cause, cf: https://github.com/dotansimha/graphql-code-generator/issues/8366#issuecomment-1288661709
