### ISSUE TITLE
typed-document-node with typescript-react-query produces clashing exports

### ISSUE THREAD

**Issue by lynxtaa** [dotansimha/graphql-code-generator#5876] opened 2021-04-20 19:32 UTC
Using `typed-document-node` with `typescript-react-query` produces clashing exports

**To Reproduce**

See https://codesandbox.io/s/graphql-codegen-export-clash-n4m75?file=/query-types.ts

![Снимок экрана 2021-04-20 223135](https://user-images.githubusercontent.com/22496946/115453361-37978300-a228-11eb-9f84-0667f5e8cee2.png)

**Comment by Urigo** [comment] 2021-04-21 08:43
Thanks for opening @lynxtaa (and thanks again for your previous PR!)

Sorry for not adding a solution here but commenting that we've tagged this issue with [our new labeling system](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

So thanks for advancing this issue already into `stage 1`.

If anyone wants to help, for `stage 2`, we'll need a failing test that demonstrates this exact behavior (and what would we wish to generate in that case).

Sorry for not commenting with a full solution (yet)...

**Comment by dotansimha** [comment] 2021-06-20 16:38
Duplicate of https://github.com/dotansimha/graphql-code-generator/issues/5333

**Closed by dotansimha** 2021-06-20 16:38 UTC
Labels: bug/1-repro-available, stage/1-reproduction
