### ISSUE TITLE
`...Query` and `...QueryVariables` types not generated

### ISSUE THREAD

**Issue by SimonCockx** [dotansimha/graphql-code-generator#8775] opened 2022-12-28 23:36 UTC
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Running `graphql-codegen` on a trivial example generates invalid TypeScript code. I'm not sure how this should be working, but there are types missing that should be generated.

In the following example, the types `DoLoginQuery` and `DoLoginQueryVariables` are missing from the generated code.

Schema:
```
type Query {
  loginPasswordBased(email: String!, password: String!): Boolean!
}
```

Query:
```
query doLogin($email: String!, $password: String!) {
  loginPasswordBased(email: $email, password: $password)
}
```

Generated code:
```
import { gql } from 'apollo-angular';
import { Injectable } from '@angular/core';
import * as Apollo from 'apollo-angular';
export const DoLoginDocument = gql`
    query doLogin($email: String!, $password: String!) {
  loginPasswordBased(email: $email, password: $password)
}
    `;

  @Injectable({
    providedIn: 'root'
  })
  export class DoLoginGQL extends Apollo.Query<DoLoginQuery, DoLoginQueryVariables> {
    document = DoLoginDocument;
    
    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
```

### Your Example Website or App

 https://github.com/SimonCockx/graphql-codegen-bug

### Steps to Reproduce the Bug or Issue

1. Clone https://github.com/SimonCockx/graphql-codegen-bug
2. Run `npm install`
3. Run `npm run gql-service-codegen`
4. Inspect the `graphql/generated/graphql.ts` file

### Expected behavior

I would expect `DoLoginQuery` and `DoLoginQueryVariables` types to be generated.

### Platform

- OS: Windows 11
- NodeJS: 19.0.0
- `@graphql-codegen/cli`: 2.16.2
- `@graphql-codegen/typescript-apollo-angular`: 3.5.6

### Codegen Config File

```
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: "graphql/schema.graphql",
  documents: "graphql/operations.graphql",
  generates: {
    "graphql/generated/graphql.ts": {
      plugins: ["typescript-apollo-angular"]
    }
  }
};

export default config;
```

**Comment by saihaj** [comment] 2023-01-04 15:40
can you try adding `typescript-operations` and `typescript` plugin?

**Comment by saihaj** [comment] 2023-01-05 20:41
duplicate of https://github.com/dotansimha/graphql-code-generator-community/issues/42

**Closed by saihaj** 2023-01-05 20:41 UTC
