### ISSUE TITLE
Incorrect no-variables type

### ISSUE THREAD

**Issue by oceandrama** [dotansimha/graphql-code-generator#4120] opened 2020-05-28 10:32 UTC
**Describe the bug**
If query takes no arguments, its variables generates as `{}`, which means `any non-nullish value`
So we can use it like this
```
useQueryWithoutVariables({variables: "any value"})
```

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**
No variables allowed, type should be `never`

**Comment by ardatan** [comment] 2020-05-28 12:09
Where do you have this function? `useQueryWithoutVariables`
Those two plugins don't generate this kind of functions;
```
      - typescript
      - typescript-operations
```

**Comment by oceandrama** [comment] 2020-05-28 12:15
It's from `typescript-react-apollo`
By the way, I can use `useQuery` hook from `@apollo/client` without other plugins like this
```
useQuery<UserQuery, UserQueryVariables>(gql`...`, { variables: 1 })
```

**Comment by dotansimha** [comment] 2020-05-31 07:38
You are right @oceandrama . And suggestion for a solution for that? 
I was thinking about [doing something like that](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogHgQwMbADwBUA0UBKA+KAXinSgjmAgDsATAZ1wCgooB+XMi6+k5lt3vygAuKFQgA3CACc+o8VNmMAZgFcqKAJYB7KlAQY8ACgBGrUfGRosUAN4BfPAEpRCKiDuNG9rwiMOnAG4oAHoQqG0Aa0Y-WygTUQBGKHsnUPCZaW1ZPypVABt8oPSyaSycozSwiMigA) to make sure no additional keys are being added, and this way we can really validate the exact shape of the variables type.

**Comment by oceandrama** [comment] 2020-06-08 21:48
@dotansimha LGTM

**Comment by dotansimha** [comment] 2020-06-09 08:30
I'm not sure where to apply it, because we can't use `Exact` (`type Exact<T, R> = T extends R ? R extends T ? T : never : never`) over the original variables type, since it requires the function call to get the `T` (the actual passes variables).

In this case I guess we'll need to modify it on the level of the function call (hooks/hoc/components, and in each plugin - react / apollo / others).

@kamilkisiela @ardatan what do you think?

**Comment by kamilkisiela** [comment] 2020-06-09 08:52
@dotansimha or [like this](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=27&pc=10#code/C4TwDgpgBAogtmU9EgOoEtgAsCyEDO+AhgObQC8UA3gFBRQDaA1hCAFxT7ABO6AdiQC6HAHIB7AGpEANgFdoAHyh8IANwjcA3DQC+2mhAAeYMd2BQAxmL5dlkmfLyFSFOlADkAd2hHIF83xiUKoO0FgaEACEkQCM7tqgkFDiUnIUUIkQYgBmdqmOBMRk+tmyfP7o1lBEABQARgD8HMhICKAY2E5FEACUHER8INQ6NDS1VDo9mlAA9DNQYkxjNVRQdRxlACYQ2fwQmwA0UABMHDHHUJOz8xrcpst8stLSU9dQt-e1PW+Lo3ML3CgnkwWDEsnMMG4d0BXRco0ysDaQ0otHozFYHC4vAEwmUag02j0o1K5WAlT4a3qTURKD61UGw1GdRWk2m-1+zNW6ygWx2e0OJzOFyu-w+3BozMez1eoqh92Z33ZTCAA)

**Comment by dotansimha** [comment] 2020-06-09 15:01
Thanks @kamilkisiela . I created a PR for wrapping all variables in `Exact` type:
https://github.com/dotansimha/graphql-code-generator/pull/4194 

@oceandrama can you please try the alpha version? `1.15.2-alpha-0b6c3cb0.0`

**Comment by oceandrama** [comment] 2020-06-09 19:36
@dotansimha I've tried both `alpha-0b6c3cb0.0` and `alpha-a841e8b0.0` and saw no changes
```
"devDependencies": {
    "@graphql-codegen/cli": "^1.15.2-alpha-0b6c3cb0.0",
    "@graphql-codegen/typescript": "^1.15.2-alpha-0b6c3cb0.0",
    "@graphql-codegen/typescript-operations": "^1.15.2-alpha-0b6c3cb0.0",
    "@graphql-codegen/typescript-react-apollo": "^1.15.2-alpha-0b6c3cb0.0",
```

**Comment by oceandrama** [comment] 2020-06-09 19:42
```
"@graphql-codegen/cli": "canary"
```
works, but I still have
```
export type MeQueryVariables = {};
```
all other variables type with some fields wrapped by `Exact`

**Comment by dotansimha** [comment] 2020-06-10 06:54
@oceandrama all your `@graphql-codegen/...` packages should use the same version. 

Btw, we released a stable version with this fix - it's `v1.15.2`. If you are still having issues, please let us know, and please share a reproduction.

**Comment by oceandrama** [comment] 2020-06-10 07:19
@dotansimha wait, wait, wait. It doesn't work. I've tested alpha-version and wrote that `Exact` is wrapping only types with some fields. I still have just `{}` in query without variables. Why did you release that?

**Comment by dotansimha** [comment] 2020-06-10 07:32
@oceandrama I thought you had a missmatch with versions, didn't notice that `{}` it not being wrapped (in case there are no vars at all).
Will fix and release again 👍

**Comment by oceandrama** [comment] 2020-06-10 07:35
Thank you

**Comment by dotansimha** [comment] 2020-06-10 07:49
We changed `{}` to be `Exact<{ [key: string]: never; }>`, this will make sure that no other fields are being used, and also gives a nice TS error when field isn't known.

https://github.com/dotansimha/graphql-code-generator/pull/4201

**Comment by dotansimha** [comment] 2020-06-10 07:53
@oceandrama can you please try `1.15.3-alpha-a0eddf41.0`?

**Comment by dotansimha** [comment] 2020-06-11 14:21
Fixed in `v1.15.3`.

**Closed by dotansimha** 2020-06-11 14:21 UTC
Labels: enhancement, plugins, waiting-for-release

**Comment by lewebsimple** [comment] 2020-06-11 14:58
How long does it take to get the latest release published on NPM ?

**Comment by dotansimha** [comment] 2020-06-11 15:04
@lewebsimple It should be available now (`v1.15.3`), sorry for the delay, we had a minor bug in our CI :D

**Comment by lewebsimple** [comment] 2020-06-11 15:14
Don't know if it's related to this issue, but I'm still getting TS `@typescript-eslint/ban-types` errors like in the following:
```
export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | StitchingResolver<TResult, TParent, TContext, TArgs>;
```
Can I safely ignore that ?

**Comment by dotansimha** [comment] 2020-06-11 15:17
@lewebsimple no need to run lint rules on generates files. It's endless :) 

I recommend you to use `@graphql-codegen/add` plugin and do something like that:

```yaml
generates:
  my-types.ts:
    plugins:
      - add: '/* eslint-disable */'
      - typescript
      - typescript-resolvers
```

And btw, if you are not using schema-stitching resolvers, you can turn it off by adding:

```yaml
generates:
  my-types.ts:
    config:
      noSchemaStitching: true
    plugins:
      - add: '/* eslint-disable */'
      - typescript
      - typescript-resolvers
```

**Comment by vegerot** [comment] 2021-09-23 21:05
@dotansimha I'm not sure this should be disregarded.  

`: {}` means "any non-nullish value".  This is likely NOT what the authors of this package intended.  This goes beyond "everyone prefers something else".  I believe `@typescript-eslint` is exposing a real bug here.

I believe you should take a similar approach to [before](https://github.com/dotansimha/graphql-code-generator/issues/4120#issuecomment-641804789) and replace

```ts
export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | StitchingResolver<TResult, TParent, TContext, TArgs>;
```

with 
```ts
type Empty = Exact<{ [key: string]: never; }>
export type Resolver<TResult, TParent = Empty, TContext = Empty, TArgs = Empty> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | StitchingResolver<TResult, TParent, TContext, TArgs>;
```
