### ISSUE TITLE
Underscores gets converted to PascalCase graphql-codegen-typescript-template

### ISSUE THREAD

**Issue by Jontem** [dotansimha/graphql-code-generator#605] opened 2018-09-14 14:09 UTC
I don't know which version this is introduced in  but today i upgraded(both codegen and template) from version ^0.9.0 to ^0.12.0 and every type or fragment that has an underscore gets convertet to PascalCase. 

ex:
before: __typename: "My_Type" created an interface named My_Type
now: __typename: "My_Type" creates an interface named MyType

After looking further its not just underscores:
__typename: "MY_type" gets converted to an interface named MYType and when referenced in other places converted to MyType

**Comment by kamilkisiela** [comment] 2018-09-14 14:32
I don't think it's a bug. We decided to PascalCase everything to have naming strategy consistent.

**Comment by dotansimha** [comment] 2018-09-14 14:38
@kamilkisiela Yeah you are right, I'm just not sure if we need to keep and handle `_` in a special case.
In pascal-case, `_` is not valid, but it usually has a special meaning (private member), so I'm not sure what we should do with it.

**Comment by kamilkisiela** [comment] 2018-09-14 14:39
I mean, the library we use to PascalCase things, doesn't emit `_` so we don't have them

**Comment by kamilkisiela** [comment] 2018-09-14 14:40
Let's handle that after the weekend, I'm going offline :)

**Comment by Jontem** [comment] 2018-09-14 14:40
But my generated types.ts file doesn't even compile ? I don't care what the interfaces are named

**Comment by dotansimha** [comment] 2018-09-14 14:41
@Jontem can you please provide an example? why it's not compiling? do you have an error?

**Comment by Jontem** [comment] 2018-09-14 14:42
Yes i'll make an repro

**Comment by Jontem** [comment] 2018-09-14 15:41
Repro: https://github.com/Jontem/graphql-codegen-repro

Background for using strange names is that we're auto generating our graphql schema server side from  a sql database tables which has some historic names

**Comment by dotansimha** [comment] 2018-09-14 16:09
I can see it now, added it as failing test here: https://github.com/dotansimha/graphql-code-generator/pull/607 , not it will be easier to work on a fix for it :) 

Thanks @Jontem .

**Comment by dotansimha** [comment] 2018-09-14 17:48
@Jontem the issue is fixed and merge in #607, I'll release a new version very soon :)

**Comment by dotansimha** [comment] 2018-09-14 17:54
@Jontem fixed and release 0.12.2, can you please test it?

**Comment by Jontem** [comment] 2018-09-14 19:37
@dotansimha I've manage to reproduce it. I've updated the repro.

**Comment by Jontem** [comment] 2018-09-17 05:29
@dotansimha The problem is that the generated file doesn't compile. In the repro the type "_User" is declared twice

**Comment by dotansimha** [comment] 2018-09-17 08:40
@Jontem fixed in: https://github.com/dotansimha/graphql-code-generator/pull/616 :)

**Comment by dotansimha** [comment] 2018-09-17 09:50
Fixed in 0.12.3 :)

**Closed by dotansimha** 2018-09-17 09:50 UTC
Labels: bug, waiting-for-release

**Comment by Jontem** [comment] 2018-09-17 10:48
@dotansimha thank you! Everything is working now!
