### ISSUE TITLE
schema-ast produces empty GraphQL docblock comments

### ISSUE THREAD

**Issue by toverux** [dotansimha/graphql-code-generator#4393] opened 2020-07-19 12:52 UTC
**Describe the bug**

For some of my types, the ast-schema plugin generates docblocks comments that are empty: 
![image](https://user-images.githubusercontent.com/1343250/87874971-4d90c280-c9ce-11ea-9ec4-30ca55aec4e2.png)

Some types that do not have a description do not have those empty comments.

That wouldn't be much annoying if they didn't make the parser of the JS GraphQL WebStorm plugin fail the parsing (to workaround, I am now using `commentDescriptions: true` and everything is fine).

3. My `codegen.yml` config file:

```yml
schema: "http://localhost:3001/graphql"

generates:
  schema.graphql:
    plugins:
      - schema-ast
```

**Expected behavior**

I guess the generator does not put a comment block if it receives null for the comment from the introspection query.
It should also do the same for empty strings.

**Environment:**

- `@graphql-codegen/...`: everything in version `1.17.0`

**Comment by dotansimha** [comment] 2020-07-19 13:41
@ardatan I think maybe it's related to graphql-tools?

**Comment by ardatan** [comment] 2020-07-19 15:04
I couldn't reproduce it. Could you reproduce rhe issue using CodeSandbox? @toverux

**Comment by danielrearden** [comment] 2020-07-20 02:15
> It should also do the same for empty strings.

If the introspection query is returning an empty string instead of null for a description, then the issue is with the schema itself and not with codegen or graphql-tools. An empty string is not the same as "no description" and the expected behavior when printing a schema with such a description would be to print the provided value.

[Example](https://runkit.com/danielrearden/5f14fbf23a8b8100130e45b0)

**Comment by dotansimha** [comment] 2020-07-20 05:19
@danielrearden is right. @toverux can you please share a reproduction of the issue? How do you fetch your schema? can you please share your `codegen.yml` file?

**Comment by Eddman** [comment] 2020-08-03 16:00
I can see there is difference between my code generated with `"graphql": "^14.7.0",` and `"graphql": "^15.3.0",`. Since I've upgraded my project GQL Schema is completely reshuffled and comments are suddenly not `null`, but `""`.

When I downgrade back to `"graphql": "^14.7.0",` the generated schema is fixed again :man_shrugging: 

So my suspicion is that the problem is in `graphql` itself.

**Comment by Zn4rK** [comment] 2020-08-04 09:12
I'm seeing the same thing as @Eddman described. I've tested this with two different GraphQL-implementations. One is based on https://github.com/99designs/gqlgen and one on https://graphene-python.org/.

Both produce the same thing when using `graphql@15.3.0`, but it looks normal when `graphql@14.7.0` is used.

**Comment by dotansimha** [comment] 2020-08-11 13:23
@Eddman  and @Zn4rK  are right. I think it's coming from `graphql` itself. Note that one of the changes related to it is comments implementation. In v14 it was done with `#` and then it was changed to `"` and the old method is not deprecated, but still can be turned on (for printing only) using `commentDescriptions`. 

I just pushed a fix for graphql-tools to support `commentDescriptions` also while parsing, to make sure comments are being converted into descriptions during the `parse` flow. Not sure if it will effect your issue, but it worth a try. 

@Zn4rK how does it work without `commentDescriptions: true` ?

**Comment by dotansimha** [comment] 2020-08-11 15:22
I managed to reproduce it 🎉 working on a fix :)

**Comment by dotansimha** [comment] 2020-09-28 08:45
Closing. If someone is still having this issue with graphql@15, please let me know.

**Closed by dotansimha** 2020-09-28 08:45 UTC
Labels: waiting-for-answer

**Comment by dan-j** [comment] 2020-10-06 19:19
I'm having this problem with graphql@15, here's my package.json `dependencies`:

```
{
    "@graphql-cli/codegen": "^1.17.10",
    "@graphql-codegen/schema-ast": "^1.17.8",
    "graphql": "^15.3.0",
    "graphql-cli": "^4.0.0"
  }
```

Brand new project, no other dependencies, any ideas?

**Comment by dotansimha** [comment] 2020-10-07 05:19
@dan-j please share a reproduction

**Comment by Eddman** [comment] 2020-10-08 14:03
@dotansimha I'm wondering why is this one closed when there was no new `graphql` released, nor any fixed introduced in `graphql-code-generator`?

BTW with `graphql@14` I have `"description": null,` with `graphql@15` it is `"description": "",` 

Direct introspection query execution against our endpoint returns `"description": "",` so `""` is replaced with `null` in `@14`.

**Comment by Eddman** [comment] 2020-10-16 11:12
@dotansimha Any news here?

**Comment by ardatan** [comment] 2020-10-16 11:16
@Eddman Could you create a new issue with a reproduction?

**Comment by Eddman** [comment] 2020-10-16 14:16
@ardatan #4920
