### ISSUE TITLE
Unable to use mongo-db directives along with other code-generator template.

### ISSUE THREAD

**Issue by ganeshpms** [dotansimha/graphql-code-generator#985] opened 2018-12-04 20:17 UTC
**Describe the bug**
When I try to have the `typescript-Mongodb` code generated, I had to add the Mongo DB directives. I am using the same schema to generate the other typescript types like `typescript-common`, `typescript-server` I am getting error `Unknown directive "entity"`.

**To Reproduce**

```yml
schema: libs/schema/src/graphs/**/*.gql
generates:
    libs/mongodb-client/src/lib/types.ts:

    config:
      enumsAsTypes: true
    plugins:
      - add: // Auto Generated. Please don't edit, the changes will be overwritten
      - time: 
      - typescript-mongodb

    libs/schema/src/lib/types.ts:

    config:
      enumsAsTypes: true
    plugins:
      - add: // Auto Generated. Please don't edit, the changes will be overwritten
      - time: 
      - typescript-common
```

where the '**/*.gql` files are having the mongo db directives.

**Expected behavior**
it should create two output files with mongodb typescript template and common typescript template.

**Schema/Documents**
`type DBObject @entity {
    id: String @id
    name: String @column
}`

**Environment:**
 - OS: Windows 10
 - Codegen:  0.14.5
 - Node: 10.13.0

**Comment by dotansimha** [comment] 2018-12-05 00:53
Hi @ganeshpms 

You no longer have to add the directives manually, because now they are declarative only, and added by the codegen before building the schema.

I managed to reproduce the issue you described here, and it happens because we are building the schema per output file, and that might cause this issue.

Is there a reason to separate `typescript-common` and `typescript-mongodb`? they should go together in the same file, because the `typescript-common` generates enums that are in use by `typescript-mongodb`.

**Comment by dotansimha** [comment] 2019-03-18 08:20
Closing for now, we fixed in the recent release.

**Closed by dotansimha** 2019-03-18 08:20 UTC
Labels: bug, core
