### ISSUE TITLE
Sort the output?

### ISSUE THREAD

**Issue by tremby** [dotansimha/graphql-code-generator#214] opened 2018-03-19 22:32 UTC
Every time I run this I get huge diffs even where things haven't changed (as far as I know) in the schema. It looks in a lot of cases like things have just changed order.

Perhaps there's some way to sort the output to minimize this? Or is it not as simple as that?

**Comment by dotansimha** [comment] 2018-04-29 06:43
@tremby any idea how to sort it? 
Also, do you generate Typings for server side only or client side as well?

**Comment by tremby** [comment] 2018-04-29 23:56
No, no idea.

I'm generating typings for the GraphQL API Gatsby gives me at development/build time.

**Comment by dotansimha** [comment] 2018-04-30 10:17
@tremby 
I see. 
The issue is that the order is defined by the GraphQL schema for the server side, and by the result of `glob` for the client side... 

I guess that sorting it in alphabetical order will be a good idea, but it might be an overhead for this package at the moment.

**Comment by micimize** [comment] 2018-06-18 23:13
@tremby you probably shouldn't be version controlling the generated output anyways. That aside, one possible solution would be to have an optional `sort` custom helper, so users could fine-tune things like this. I don't see any reason to sort alphabetically by default, and I wonder if it would break "dependency ordering" for targets where that's applicable (like with #384)

**Comment by tremby** [comment] 2018-06-18 23:16
You're right -- it's only helpful at dev time, isn't it...

I think this is moot in light of that. Close at will.

**Comment by dotansimha** [comment] 2018-06-19 05:51
@tremby can I close this one?

**Comment by tremby** [comment] 2018-06-19 05:52
Absolutely, if you agree that there's no benefit to checking in the
generated types file to version control and as such this issue bring moot.

**Comment by dotansimha** [comment] 2018-06-19 05:54
Yeah I think it’s should be in ‘.gitignore’ :)

**Closed by dotansimha** 2018-06-19 05:54 UTC
Labels: enhancement
