### ISSUE TITLE
Failed to load schema - TypeError: crossUndiciFetch.fetch is not a function

### ISSUE THREAD

**Issue by doron-cohen** [dotansimha/graphql-code-generator#7388] opened 2022-01-23 21:54 UTC
**Describe the bug**
 
When running the generate command I get this error:

```
 Found 1 error

  ✖ ./src/user.tsx
    Failed to load schema from http://localhost:8080/v1/graphql:

        crossUndiciFetch.fetch is not a function
        TypeError: crossUndiciFetch.fetch is not a function
    at defaultAsyncFetch (/home/doron/dev/supplize/application/application/node_modul
es/@graphql-tools/url-loader/index.js:44:29)
    at /home/doron/dev/supplize/application/application/node_modules/@graphql-tools/u
rl-loader/index.js:474:36
    at new ValueOrPromise (/home/doron/dev/supplize/application/application/node_modu
les/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at executor (/home/doron/dev/supplize/application/application/node_modules/@graph
ql-tools/url-loader/index.js:442:20)
    at /home/doron/dev/supplize/application/application/node_modules/@graphql-tools/u
rl-loader/index.js:646:20
    at /home/doron/dev/supplize/application/application/node_modules/@graphql-tools/w
rap/index.js:1697:52
    at new ValueOrPromise (/home/doron/dev/supplize/application/application/node_modu
les/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at Object.introspectSchema (/home/doron/dev/supplize/application/application/node
_modules/@graphql-tools/wrap/index.js:1697:12)
    at UrlLoader.load (/home/doron/dev/supplize/application/application/node_modules/
@graphql-tools/url-loader/index.js:687:40)
    at async /home/doron/dev/supplize/application/application/node_modules/@graphql-t
ools/load/index.js:75:39

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schem
a")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
    Error: Failed to load schema
        at loadSchema (/home/doron/dev/supplize/application/application/node_modules/
@graphql-codegen/cli/bin.js:503:15)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /home/doron/dev/supplize/application/application/node_modules/@graph
ql-codegen/cli/bin.js:857:33
        at async /home/doron/dev/supplize/application/application/node_modules/@graph
ql-codegen/cli/bin.js:972:52
        at async Task.task (/home/doron/dev/supplize/application/application/node_mod
ules/@graphql-codegen/cli/bin.js:811:17)
    Error: Failed to load schema
        at loadSchema (/home/doron/dev/supplize/application/application/node_modules/
@graphql-codegen/cli/bin.js:503:15)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /home/doron/dev/supplize/application/application/node_modules/@graph
ql-codegen/cli/bin.js:857:33
        at async /home/doron/dev/supplize/application/application/node_modules/@graph
ql-codegen/cli/bin.js:972:52
        at async Task.task (/home/doron/dev/supplize/application/application/node_mod
ules/@graphql-codegen/cli/bin.js:811:17)
```

Running this command works so I believe it's a dependency issue:

```
curl -X POST -H "Content-Type: application/json" -H "x-hasura-role: user" -H "x-hasura-admin-secret: secret" --data '{"query": "query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }"}' "http://localhost:8080/v1/graphql"
```

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->


3. My `codegen.yml` config file:

```json
{
  "overwrite": true,
  "generates": {
    "./src/user.tsx": {
      "schema": [
        {
          "http://localhost:8080/v1/graphql": {
            "headers": {
              "x-hasura-role": "user",
              "x-hasura-admin-secret": "secret"
            }
          }
        }
      ],
      "documents": ["./src/user/**/*.graphql"],
      "plugins": ["typescript", "typescript-operations", "typescript-react-apollo"],
      "config": {
        "preResolveTypes": true,
        "skipTypename": false,
        "withHooks": true,
        "withHOC": false,
        "withComponent": false,
        "enumsAsTypes": true,
        "constEnums": true,
        "reactApolloVersion": 3
      }
    }
  }
}

```

**Environment:**
OS: linux
React
```
    "@graphql-codegen/cli": "^2.4.0",
    "@graphql-codegen/introspection": "^2.1.1",
    "@graphql-codegen/typescript": "^2.4.2",
    "@graphql-codegen/typescript-operations": "^2.2.2",
    "@graphql-codegen/typescript-react-apollo": "^3.2.4",
```
**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by dodiameer** [comment] 2022-01-23 22:14
Running into this same issue on a new project, strange thing is it worked with a dummy project I created about 3 hours ago that still works but I can't get it to work on a new project

**Comment by ardatan** [comment] 2022-01-24 02:04
Could you delete your lock file and try again? Sorry for inconvenience.

**Comment by naquiroz** [comment] 2022-01-24 04:52
I'm having the same error, and deleted the lock file. Doesn't work.

**Comment by ardatan** [comment] 2022-01-24 07:44
@naquiroz Could you share a reproduction on CodeSandbox?

**Comment by smeevil** [comment] 2022-01-24 09:29
Same issue, keeping an eye on this.

**Comment by starfish719** [comment] 2022-01-24 09:51
I got a similar error.

Environment: 
OS: MacOS
React

```
"@graphql-codegen/cli": "~2.4.0",
"@graphql-codegen/near-operation-file-preset": "~2.2.0",
"@graphql-codegen/typescript": "~2.4.0",
"@graphql-codegen/typescript-operations": "~2.2.0",
"@graphql-codegen/typescript-react-apollo": "~3.2.0",
```

```
(node:46265) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate to apps/project/src/ (using EXPERIMENTAL preset "near-operation-file")
      ✖ Load GraphQL schemas
        → crossUndiciFetch.AbortController is not a constructor
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ apps/project/src/
    TypeError: crossUndiciFetch.AbortController is not a constructor
        at executor (/Users/admin/project/github/project/node_modules/@graphql-tools/url-loader/index.js:417:32)
        at /Users/admin/project/github/project/node_modules/@graphql-tools/url-loader/index.js:646:20
        at /Users/admin/project/github/project/node_modules/@graphql-tools/wrap/index.js:1697:52
        at new ValueOrPromise (/Users/admin/project/github/project/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
        at Object.introspectSchema (/Users/admin/project/github/project/node_modules/@graphql-tools/wrap/index.js:1697:12)
        at UrlLoader.load (/Users/admin/project/github/project/node_modules/@graphql-tools/url-loader/index.js:687:40)
        at async /Users/admin/project/github/project/node_modules/@graphql-tools/load/index.js:75:39
        at async Promise.all (index 1)
        at async loadFile (/Users/admin/project/github/project/node_modules/@graphql-tools/load/index.js:73:9)
        at async /Users/admin/project/github/project/node_modules/@graphql-tools/load/index.js:386:25
    TypeError: crossUndiciFetch.AbortController is not a constructor
        at executor (/Users/admin/project/github/project/node_modules/@graphql-tools/url-loader/index.js:417:32)
        at /Users/admin/project/github/project/node_modules/@graphql-tools/url-loader/index.js:646:20
        at /Users/admin/project/github/project/node_modules/@graphql-tools/wrap/index.js:1697:52
        at new ValueOrPromise (/Users/admin/project/github/project/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
        at Object.introspectSchema (/Users/admin/project/github/project/node_modules/@graphql-tools/wrap/index.js:1697:12)
        at UrlLoader.load (/Users/admin/project/github/project/node_modules/@graphql-tools/url-loader/index.js:687:40)
        at async /Users/admin/project/github/project/node_modules/@graphql-tools/load/index.js:75:39
        at async Promise.all (index 1)
        at async loadFile (/Users/admin/project/github/project/node_modules/@graphql-tools/load/index.js:73:9)
        at async /Users/admin/project/github/project/node_modules/@graphql-tools/load/index.js:386:25
```

**Comment by dodiameer** [comment] 2022-01-24 11:29
I couldn't get a reproduction — Deleting `yarn.lock` and `mode_modules` and reinstalling didn't work but strangely making a new repo and installing there worked without any problem

**Comment by smeevil** [comment] 2022-01-24 12:04
I've been trying to isolate the issue, as this happened after a yarn.lock update.
Alas, I have not been successful with this but might have some pointers on what changed in our lock file that might point someone in the right direction:

- cross-fetch from 3.1.4 to 3.1.5
- cross-undici-fetch from 0.1.15 to 0.1.17 and node fetch from 2.6.5 to 2.6.7
- node-fetch from 2.6.6 to 2.6.7

**Comment by ardatan** [comment] 2022-01-24 12:23
Closing this issue then. Please create a reproduction if you have this issue again

**Closed by ardatan** 2022-01-24 12:23 UTC

**Comment by dotansimha** [comment] 2022-01-26 12:51
Just to make it more clear. It's either pinning all share dependencies to a specific version (and then we might hit duplications - big node_modules payload, and also issues with multiple versions), or, we use ranged dependencies (that allow us to gradually improve libs, but makes it more difficult to force specific versions). 

We used the 1st approach for a few years, and it didn't work well, and we had a lot of issues. Moving to the 2nd approach makes it simpler to maintain shared dependencies, but sometimes we have those issues, that depends on the way the dependency manager resolves dependencies. 

We don't have a way to force your dependency manager to download a new version, without updating all other libraries that might need the same shared dependencies. 
Since most dependencies managers resolve and lock the version when you install it and don't update the child dependencies if you don't ask explicitly. In more extreme cases, there are even duplications within a single lock file, that cause similar issues. 

As @ardatan suggested, you should either modify the lock file manually, use `npx yarn-deduplicate`, or delete your lock file and regenerate it. You can also try to add the shared dependencies like `@graphql-tools/...` libs or `cross-undici-fetch` directly to your project, and this will make sure that **you** control the dependencies versions (or even through Yarn `resolutions`).
