### ISSUE TITLE
Syntax error when installing graphiql package

### ISSUE THREAD

**Issue by sanalpanicker** [dotansimha/graphql-code-generator#9755] opened 2023-11-09 22:34 UTC
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Running yarn codegen after installing graphiql package throws  syntax error:

`Expected Name, found "}".`

if graphiql package is removed, everything works fine.

![Screenshot 2023-11-09 at 2 27 07 PM](https://github.com/dotansimha/graphql-code-generator/assets/123005072/1d3bb7b2-a401-49e1-b325-d7bbf1109dc9)

#### codegen.ts file
![Screenshot 2023-11-09 at 2 29 10 PM](https://github.com/dotansimha/graphql-code-generator/assets/123005072/1c75c567-24f5-4f6f-b470-7bb3a0048c6b)

I can't figure out what is causing this. Probably some nested dependency issues?

### Your Example Website or App

codesandbox : [here]([codesandbox.io/p/sandbox/fragrant-bird-6n72vc](https://codesandbox.io/p/sandbox/fragrant-bird-6n72vc)) might have to fork it to try the terminal

### Steps to Reproduce the Bug or Issue

open terminal
Run yarn codegen

### Expected behavior

I expect it to throw no issues

### Platform

- OS: masOS
- NodeJS: 20
- `graphql` version: 16.8.1
- `@graphql-codegen/*` version(s): 5.0.0

### Codegen Config File

const config: CodegenConfig = {
  schema: {
    '':
      {
        headers: {
          authorization: token ? `Bearer ${token}` : '',
        },
      },
  },
  documents: '**/*.graphql',
  config: {
    skipDocumentsValidation: true,
  },
  generates: {
    './src/types/graphql.ts': {
      plugins: ['typescript', 'typescript-operations', 'typed-document-node'],
      config: {
        documentMode: 'documentNode',
      },
    },
  },
};

**Comment by Urigo** [comment] 2023-11-19 14:46
I think the link to the reproduction doesn't work, can you fix it?

**Comment by sanalpanicker** [comment] 2024-02-06 23:10
> I think the link to the reproduction doesn't work, can you fix it?

@Urigo  can you try this https://codesandbox.io/p/devbox/fragrant-bird-6n72vc

**Comment by eddeee888** [comment] 2024-09-27 08:45
Hi @sanalpanicker ,

Using your provided sandbox, I was able to make it work by narrowing the `document` config to `src/**/*.graphql`:

![Screenshot 2024-09-27 at 6 41 54 PM](https://github.com/user-attachments/assets/0d71b839-6ff8-408d-abef-fbcee008fde0)

My guess is by using `**/*.graphql`, it may have parsed other GraphQL files unncessarily.

Apart from that, looks like your sandbox are missing the following packages:

- `"@graphql-codegen/typed-document-node": "5.0.9"`
- "@graphql-codegen/typescript-operations": "4.2.3"`

The above fixes result in codegen running successfully now:

![Screenshot 2024-09-27 at 6 44 40 PM](https://github.com/user-attachments/assets/e05fc982-db30-4034-81b7-fd5058975682)

Closing this as it seems a config issue. Please let me know if it's not the case.

**Closed by eddeee888** 2024-09-27 08:45 UTC
