### ISSUE TITLE
incorrect types on fragments

### ISSUE THREAD

**Issue by bwiklund** [dotansimha/graphql-code-generator#2436] opened 2019-08-23 20:47 UTC
we're getting incorrect types on some generated types, see below. I commented on the final snippet in the generated code where the types are seemingly wrong

```
type DashboardTileChartDetails {
  tileId: String!
  wsId: UUID!
  chartId: String!
  md: TileChartMetadata # null if we error out
}

type TileChartMetadata {
  connection: Connection!
  viz: JsonBlob!
  columnInfo: JsonBlob! # the ColumnInfo type;
}

type DashboardTileFilterDetails {
  tileId: String!
  md: TileFilterMetadata
}
```

```
const DashboardVersionFragment = gql`
  fragment DashboardVersionFragment on DashboardVersion {
    ...DocumentVersionFragment
    tiles {
      ... on DashboardTileChartDetails {
        tileId
        wsId
        chartId
        md {
          viz
          columnInfo
          connection {
            ...ConnectionFragment
          }
        }
      }
      ... on DashboardTileFilterDetails {
        tileId
        md {
          columnType
          connection {
            ...ConnectionFragment
          }
        }
      }
      ... on DashboardTileParameterDetails {
        tileId
        md {
          parameterConstraint
          parameterLabel
        }
      }
    }
  }
  ${DocumentVersionFragment}
  ${ConnectionFragment}
`;
```

```
export type DashboardVersionFragmentFragment = (
  { __typename?: 'DashboardVersion' }
  & { tiles: Array<(
    { __typename?: 'DashboardTileChartDetails' }
    & Pick<DashboardTileChartDetails, 'tileId' | 'wsId' | 'chartId'>
    & { md: Maybe<(
      { __typename?: 'TileChartMetadata' }
      & Pick<TileChartMetadata, 'viz' | 'columnInfo'>
      & { connection: { __typename?: 'Connection' }
        & ConnectionFragmentFragment
       }
    )> }
  ) | (
    { __typename?: 'DashboardTileFilterDetails' }
    & Pick<DashboardTileFilterDetails, 'tileId'>
    & { md: Maybe<(
      { __typename?: 'TileChartMetadata' }
      & Pick<TileChartMetadata, 'columnType'> // should pick TileFilterMetadata
      & { connection: { __typename?: 'Connection' }
        & ConnectionFragmentFragment
       }
    )> }
  ) | { __typename?: 'DashboardTileTextDetails' } | (
    { __typename?: 'DashboardTileParameterDetails' }
    & Pick<DashboardTileParameterDetails, 'tileId'>
    & { md: Maybe<(
      { __typename?: 'TileChartMetadata' }
      & Pick<TileChartMetadata, 'parameterConstraint' | 'parameterLabel'> // should pick TileParameterMetadata
    )> }
  )> }
)
  & DocumentVersionFragmentFragment
;
;
```

**Comment by n1ru4l** [comment] 2019-08-23 22:15
Is the field tiles a union or interface?

**Comment by bwiklund** [comment] 2019-08-23 22:36
sure here's some more context:

```
type DashboardVersion implements DocumentVersionInterface {
  version: Int!
  document: JsonBlob!
  description: String

  createdBy: OrgMember!
  updatedBy: OrgMember!

  createdAt: DateTime!
  updatedAt: DateTime!

  tiles: [DashboardTile!]!
}

```

```

union DashboardTile =
    DashboardTileChartDetails
  | DashboardTileFilterDetails
  | DashboardTileTextDetails
  | DashboardTileParameterDetails


```

**Comment by n1ru4l** [comment] 2019-08-23 22:42
I also created a reproduction using interfaces instead of unions (see https://github.com/dotansimha/graphql-code-generator/pull/2437)

**Comment by bwiklund** [comment] 2019-08-23 22:56
so this is confirmed to be a bug? i wanted to be sure we weren't discovering some issue with our schema through the type generation

**Comment by n1ru4l** [comment] 2019-08-23 23:25
Yes it is caused by some code that I did not delete when fixing union/interface types 😅

I fixed it in https://github.com/dotansimha/graphql-code-generator/pull/2437

I added tests for both unions and interfaces to ensure there will be no regression!

**Comment by tanguyantoine** [comment] 2019-08-30 15:12
I'm experiencing this issue as well, thank you to have fixed it 👍

**Comment by dotansimha** [comment] 2019-08-31 09:05
Fixed in 1.7.0
thanks @n1ru4l

**Closed by dotansimha** 2019-08-31 09:05 UTC
Labels: bug, templates, waiting-for-release

**Comment by bwiklund** [comment] 2019-10-28 21:44
fwiw this is still broken in 1.8.2

**Comment by n1ru4l** [comment] 2019-10-29 06:14
@bwiklund Could you please provide a code sandbox example or a failing test?

**Comment by dotansimha** [comment] 2019-10-29 09:32
Just as @n1ru4l said, can you please share a reproduction of this? @bwiklund ?

**Comment by bwiklund** [comment] 2019-10-29 20:49
sorry, i dont have the bandwidth to recreate this entire environment for a repro. it's the same bug as original reported
