### ISSUE TITLE
Plugin typescript does not export a valid JS object with "plugin" function.

### ISSUE THREAD

**Issue by ashubham** [dotansimha/graphql-code-generator#3275] opened 2020-01-10 22:15 UTC
**Describe the bug**
 
When I try to follow the getting started from the docs, I get the error:
`Plugin typescript does not export a valid JS object with "plugin" function.`

**To Reproduce**
1. My codegen.yml
```
overwrite: true
schema: "./schema.graphql"
documents: null
generates:
  ./types.ts:
    plugins:
      - "typescript"
```
1. My GraphQL schema:

```graphql
type Query {
  resultSet(searchText: String!): ResultSet
  board(id: ID!): Board
}

type Mutation {
  createBoard: Board
  addPhotosToBoard(input: AddPhotosToBoardInput!): AddPhotosToBoardPayload
  updateBoardLayout(input: UpdateBoardLayoutInput!): UpdateBoardLayoutPayload
}

type ResultSet {
  photos: [Photo]!
}

type Photo {
  id: ID!
  owner: String!
  secret: String!
  server: Int!
  farm: Int!
  title: String!
  ispublic: Int!
  isfriend: Int!
  isfamily: Int!
}

enum TileSize {
  SMALL
  MEDIUM
  LARGE
}

type Tile {
  photo: Photo!
  size: TileSize!
}

type Board {
  id: ID!
  tiles: [Tile!]!
}

input AddPhotosToBoardInput {
  id: ID!
  photos: [PhotoInput!]!
}

input PhotoInput {
  id: ID!
  owner: String!
  secret: String!
  server: Int!
  farm: Int!
  title: String!
}

type AddPhotosToBoardPayload {
  board: Board
}

input UpdateBoardLayoutInput {
  id: ID!
  tileChanges: [TileChange!]!
}

input TileChange {
  id: ID!
  size: TileSize
}

type UpdateBoardLayoutPayload {
  board: Board
}
```

**Expected behavior**

Types should be generated.

**Environment:**

- OS: Mac OSX 
- `@graphql-codegen/...`: 1.11.2
- NodeJS: 10.11.0

This is related to #1703 which was closed without a solution.

**Comment by dotansimha** [comment] 2020-01-22 13:31
@ashubham can you please provide a reproduction in codesandbox/repo? We couldn't reproduce this issue. 

Please make sure you have `@graphql-codegen/typescript` installed.

**Comment by doronnac** [comment] 2020-01-26 11:29
Had the same issue, this was because the quick start section did not mention `@graphql-codegen/typescript` installation. I can contribute to the docs if you'd like.

**Comment by dotansimha** [comment] 2020-01-26 14:56
@doronnac Thank, this could help. The current documentation is not focused in TypeScript because we support multiple platforms and environments, not only typescript. 
The basic instruction is to install the plugins you are using under `plugins: ` section. 

Closing for now. @ashubham If you have a reproduction, please share with us and we'll re-open this issue.

**Closed by dotansimha** 2020-01-26 14:56 UTC
Labels: waiting-for-answer

**Comment by pak11273** [comment] 2020-05-14 04:27
I'm still getting this error even after `yarn add -D @graphql-codegen/typescript`

**Comment by krainboltgreene** [comment] 2021-09-07 08:44
Hi, I'm having this issue, but I *do* have the plugin installed. I have a branch that should reproduce this, shall I make another issue or continue in this one?

**Comment by krainboltgreene** [comment] 2023-10-26 00:28
@amirrezaDev1378 Yes, I switched to not using graphql.
