### ISSUE TITLE
[typescript-operations] preResolveTypes generate incorrect optional types

### ISSUE THREAD

**Issue by standy** [dotansimha/graphql-code-generator#3638] opened 2020-03-14 22:11 UTC
**Describe the bug**

Optional types should be marked with `?`

Current behavior:
```ts
export type CommentQuery = {
  __typename?: 'Query';
  currentUser: Maybe<{ __typename?: 'User'; login: string; html_url: string }>;
  entry: Maybe<{
    __typename?: 'Entry';
    id: number;
    createdAt: number;
    commentCount: number;
    postedBy: { __typename?: 'User'; login: string; html_url: string };
    comments: Array<Maybe<{ __typename?: 'Comment' } & CommentsPageCommentFragment>>;
    repository: { __typename?: 'Repository'; description: Maybe<string>; open_issues_count: Maybe<number>; stargazers_count: number; full_name: string; html_url: string };
  }>;
};
```

Expected behavior:
```ts
export type CommentQuery = {
  __typename?: 'Query';
  currentUser?: Maybe<{ __typename?: 'User'; login: string; html_url: string }>;
  entry?: Maybe<{
    __typename?: 'Entry';
    id: number;
    createdAt: number;
    commentCount: number;
    postedBy: { __typename?: 'User'; login: string; html_url: string };
    comments: Array<Maybe<{ __typename?: 'Comment' } & CommentsPageCommentFragment>>;
    repository: { __typename?: 'Repository'; description?: Maybe<string>; open_issues_count?: Maybe<number>; stargazers_count: number; full_name: string; html_url: string };
  }>;
};
```

**To Reproduce**
There is an example in `dev-test` folder:
https://github.com/dotansimha/graphql-code-generator/blob/master/dev-test/githunt/types.preResolveTypes.ts#L177

**Comment by dotansimha** [comment] 2020-03-17 16:12
Fixed in `v1.13.1` 🎉

**Closed by dotansimha** 2020-03-17 16:12 UTC
Labels: bug, templates, waiting-for-release

**Comment by ekfn** [comment] 2020-03-25 16:52
Hi there. Are this optional? Or why this expected behavior? @dotansimha

**Comment by ekfn** [comment] 2020-03-25 17:06
i can opt out this behavior via `avoidOptionals: true`, but i'm using this syntax:
```
avoidOptionals:
  inputValue: false
  object: true
```
and it seems like i can't opt out this behavior via this syntax

**Comment by ekfn** [comment] 2020-03-25 17:55
answer is here https://github.com/dotansimha/graphql-code-generator/pull/3657
so this is works for me:
```
avoidOptionals:
  object: true
  field: true
```
