### ISSUE TITLE
Mappers are not used for union types

### ISSUE THREAD

**Issue by darkbasic** [dotansimha/graphql-code-generator#3979] opened 2020-05-05 13:29 UTC
GraphQL schema:
```graphql
type A {
  id: ID!
  a: Int!
}

type B {
  id: ID!
  b: Int!
}

union AOrB = A | B
```

codegen config:
```yml
mappers:
  A: ./types#MyA
  B: ./types#MyB
```

**Expected behavior**

The union `AOrB` type should be automatically mapped to `MyA | MyB`, but it doesn't.
A quick workaround is to manually map it like this:

```yml
mappers:
  A: ./types#MyA
  B: ./types#MyB
  AOrB: ./types#MyAOrB
```

where `MyAOrB` is simply `MyA | MyB`.

**Comment by dotansimha** [comment] 2020-05-06 09:28
I see, so what you are asking for is a way to have a `mapper` for the entire union? For a use case where you have a third custom type, that represents the possible implementation of A and B?

**Comment by darkbasic** [comment] 2020-05-06 14:21
Not exactly, it's already possible to have a custom mapper for a union type:
```yml
  AOrB: ./types#MyAOrB
```
The previous snipped declares a custom mapper for the `AOrB` union type and works fine.

The issue is that if **don't** declare mappers for each and every union the codegen won't automatically use their base type mappers when it generates the typings for the unions.
In short without the previous snippet `AOrB` would be just `A | B` instead of `MyA | MyB`, while if I specify mappers for the base types of a union those should be automatically used for the union itself.

**Comment by darkbasic** [comment] 2020-06-11 08:34
@dotansimha it looks like it works if you return a union on the top level of a query, but if you return a type which returns a union (like for example a paginated list) it won't

```
union AOrB = A | B

type Connection {
  count: Int!
  edges: [Edge!]!
  pageInfo: PageInfo!
}

type Edge {
  cursor: DateTime!
  node: AOrB!
}

type PageInfo {
  startCursor: DateTime
  endCursor: DateTime
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

extend type Query {
  simple: AOrB!
  paginated(
    first: Int
    last: Int
    after: DateTime
    before: DateTime
  ): Connection!
}
```

In the previous example `simple` will work, but `paginated` won't.

**Comment by dotansimha** [comment] 2020-06-11 08:42
I think maybe `Omit` is missing there? I'll add a test to make sure. Thanks @darkbasic

**Comment by dotansimha** [comment] 2020-06-11 09:02
@darkbasic still not able to reproduce.... 

I have this schema, with an explicit usage of the union, but also a proxied one:

```
        type Query {
          explicitUnion: U!
          proxyToUnion: UnionProxy!
        }

        union U = A | B

        type UnionProxy {
          u: U
        }

        type A {
          a: String
        }

        type B {
          b: String
        }
```

I created mappers for the types only:

```js
      const config = {
        noSchemaStitching: true,
        mappers: {
          A: 'number',
          B: 'number',
        },
      };
```

The output code is:

```
export type ResolversTypes = {
  String: ResolverTypeWrapper<Scalars['String']>;
  Boolean: ResolverTypeWrapper<Scalars['Boolean']>;
  Query: ResolverTypeWrapper<{}>;
  U: ResolversTypes['A'] | ResolversTypes['B'];
  UnionProxy: ResolverTypeWrapper<Omit<UnionProxy, 'u'> & { u?: Maybe<ResolversTypes['U']> }>;
  A: ResolverTypeWrapper<number>;
  B: ResolverTypeWrapper<number>;
};

```

And the resolvers code is using `Omit` correctly to replace all usages of the union original type, and replace it with the resolvers relevant types (see `UnionProxy`).


Also, the `Query` type is using it correctly:

```ts
export type QueryResolvers<ContextType = any, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  explicitUnion?: Resolver<ResolversTypes['U'], ParentType, ContextType>;
  proxyToUnion?: Resolver<ResolversTypes['UnionProxy'], ParentType, ContextType>;
};
```

I tried to create a code that replicates that exact usage, and return the mapped values in all possible forms, it always works when I returns the mapped value:

```ts
const resolvers: Resolvers = {
  Query: {
    explicitUnion: () => {
      return 10; // works
    },
    proxyToUnion: () => {
      return {
        u: 10 // works
      }; 
    }
  },
  UnionProxy: {
    u: () => {
      return 10; // works
    },
  }
}
```

[You can find a working output here in TS Playground](https://www.typescriptlang.org/play/?ssl=175&ssc=2&pln=159&pc=1#code/KYDwDg9gTgLgBDAnmYcCyBDRAjYAeAFQD44BeOAuAHzgDsBXAG0YG4AoASwFtJY4BvOAHEoGMAAsAigBkASsADOERgDdgASVoAzCHAC+cLVAhc4AcgDmoiQEdGZ9qF7wkKOAHkuHGIQA0cAGk4UBhgWgATBTgAa2BECC0KEnIABQ4AY2i-OABREHTGenD8WPjEgn8AoiJ2AHoAKnq4AEFmOGx6DkYYAFoOWjgMCLh0+gUYEzgFdIxGDCgFfy4xFHCEXRhxYA4oQfSYelm4FVn6RTh62rYnaBdkVABlGbmFsgE2ODh1ABEALimYFB+hZ2J8HoDgf9xkDaCCPnAAEIQZTAIb-bDIxio2igr60GD-BhcXBQXEAMUYEAwBLo9GJwFJbD07Gu4FuCHucEkZygiDe-HhAH1Ba4whguMAAPz-MzchmIBzwpyMDLeACqtA4EFo-zVuLAxhAiAIEA1Wp1cDN2pShsQ7GZbFZzg5bjVb2a1ERLJufFFls11tt-KFIvutHFUplVtoNogRsVn3o0vQWFweDVNSZ3rZvs5HvIAs+wtF4YlybMzQTg2TmBw+Ces3mCgA2mZwTCLGYALqZh1O9l+hHBouhlClyPmBFV7A11P155N1vt4Hd3ss-u5tzyJSqBkEe4AdWsKCghGScFjXgU+GInoI2edfu3yjUp4I26YMH8BBS8zC8ALPRvwAYW1UIQAAgQgIoZooAsKJAPPZ9dygMlaEID9um-X8oH-ECwJCb9YPgzMNzuLdFBfBk0IwxRP2wv98Xw-FCJguCFHPAAKeEwEYmkfz43x4XmeD-gIYjFnhdICIgsTQJYiChM+fodH+EQxCkORKN3TQdDYABKMgSEvDhr1ohRPxIGh3zo7oHwHTkHnobBpiBMAYHNJyXPSIFcBomyLKwigcLwih5PAr82JIt5uM+XjcPxMSQqY4T2LEiSlJGGT+PCwj4RUiA1OsTTkLUXSIAMoyWgURBaHSdRQlECY30wmArIvYwr3wZoarqhqGWpaBzMs0ifXIx5nNcjh3PNUrgH81qGISyKCFyxSoo4mKeL4pLBNS0SNsy6SFJy7LMoKoqNJkObysq0gSACz9PRMszHu6Uac3gfpGq0DB0gm7y3I87UvKmkl3GwAArYB9mGoKCACOJgggsJIgBDsltC1azo2khCymSafI4XB-lBomZpBwnfPm9DBGbUo4H6ChEcQLsxNa-RMaYsKcfE9jM0+XCdzUZMyaB2btLUBbbMiumGaZhG4jZigOeg7GTqI-n7UdMbGZYqBfv+uAxem4HaDmqAIeh2G3pW5KVrWlaJLx+ELMB4ngFJqnTc872-PQoZEC5h3eed3Ehaor33Yp83JZpuHIsD5iIs1kjtbIl0AammOrZhnxbe-FnkdCCIomhYFg+T1i+ei0h4RoE2Y5N8GobzhPC7iSueY13H6+N72Y4t3ObcW4LBO7lPcfszcs-Js2Lfb5mkZCVGy4hWFg-5NXHa31OEKg5I+84ziADoz5EhR-kD5su0M+7++js3h-z0fFaDsflqr9aa44-S+8bp+rcR4yw7u-ASn8J7VzDjrT6mcKD3Dmv5fcKBFgf3-LvSBEEt5cW2stXan8pLZTkmdfK2hCrCGKtdOOt074kFrGmAgyDFDtRevgehN4mEcQ+o+Tk6gFBMPcFoC2-lsExQgFDMS-gLoUKulpYWGgyG0PaJibEz1OqmXwBiFEQxuEOTcAAORCMI9Ct5yCcSUaws809xpwG+DsPOHA1DGIThg8B6DAJf0gvwNWElRFmPhLQEI-xDEQWcbbIgmV4r-nwXhfal9DqEJOsQjWpDVIyIkFQ+RNCqq2zUSYDRCdSINCaJgMAYBgTtGADAAA7sAMIgw2gYBOF0DA2AsRTHSFsZYmcohDDWJsVAEcUJRFFFES4GcnxxwWJw4cxt14WH+BbJhR4VgMjwA2F4LY2zzNXLiJE2iLRLMPMeNZGzFxmH2ViIYuz4Ryl5IsqZyyTmnm8QLS0Dz5HTPuFsysXZPQW34d81sU4uy4mjLGI0HyqJQCeas08nhvDpgDDGW0-gzD0DMCQAAZAIOASZ-jsLwACzhrY1Srn0G85oUKUKwrKWsokJI3kImpa+WlJ48AMoZGuR0xSUxlIqbgGpdSBizEYIMZpcw2moGmF0jAPTBjDAGXAIZr4ohRPxGMq4utJmfIUPbGZBZ4TLlhKTBcCwlw7NBfCS52JTWNnNRclR1yrWfDuYgf43iwUsoZHqviJKKzdn+VM31y1-UgrBciiF7qPBeB8OC1F5gMXYtxfilMdYiXBv1UCswZKez6FxFS2k9JGSfGZUWkk9prFwLdQCvAjsmFvCTheP1nIV6lzgACrNKDWxusDeQTtLbu2yh5AqPNhrPjKlVDAaMyYF7Euzbm-wXbgD+HrfcN5Bo4zGlNMi2dUyM26v9fGrd3Yl2DpXXANdKBuUTM5GqWtV7UDkCbcu4uq8O2ZvPVs3NbwB2hoXeS8dcBhQquAEwsSCC440QDZ6C5Zgz3-pQKu7KTCb3arvZG20D6UOcmfbQd+r621oz-f+I9mGT1-P7Z+xDihSXkfjGO94iY92fLwIS+dQ7c0RObTR5DJ1UO4mFKZARWhkx8JE845daHYF+maNh-juGFUEfPW+9tJH8T+t+b+6jpHs2-PPPjDALHoVsbnAe6FgKh3Gs7D2BDumkOXpw9ewTgphP3EEWJyzwBBGSfPdJnhbgETyYig2vDymaOqeIzpjT2aQXad1curZIKDPwhnN6087Hg3+us6uOzMWHOPreUJrzHn-jifc0IqZNEpOVpgQF1AwWQihaUyl11I7kw1uDXWpzwA3lqmTPe4NEbzRRoG-RxAjWIICfhM0ZMcmuuFb2cmILC2es3rYMUj4TQAACxQDQw2pMAcIW3LTXjgAAIgBed5VyJ4DiOtl9Wg4xUThBPl8RI8R6BwGqaZcQ6w4AWCqRd9QV3-AYHCGsc7oybTAC0BwEAZXrsTDgJ93Yx04cWBPltrVMneGTZgM1wOSFVsKec46Y64xlXBvS-vfGbqPXwgneAFU6R1TIv+OYqq+NPiCyqfQKAAwACMAAGFgcBai1G+9AaIChGeczl5uo0Jpowc6UdznnuEDgC6Yzz3X9B-gi7l58Zk4vJfVOl7L3Xeh4RAXhMeyFOvEyq650bqnWuhei7l7b43TIgA)


@darkbasic can you please create a reproduction in a codesandbox? we have a template here: https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template

**Comment by darkbasic** [comment] 2020-06-11 10:05
@dotansimha unfortunately the codesandbox gives me 502, so I uploaded a repro on github: https://github.com/darkbasic/codegen-gh3979

Try to comment out the following (https://github.com/darkbasic/codegen-gh3979/blob/master/codegen.yml#L14) and `paginated` will error out because of typings (https://github.com/darkbasic/codegen-gh3979/blob/master/src/resolvers.ts#L18)

**Comment by dotansimha** [comment] 2020-08-13 14:23
@darkbasic I think this PR also fixes your issue: https://github.com/dotansimha/graphql-code-generator/pull/4531 (since it changes the order of mapper checking, so I think it should work for unions as well).

**Comment by dotansimha** [comment] 2020-08-21 07:56
Fixed in `@graphql-codegen/typescript-resolvers@1.17.9`.

**Closed by dotansimha** 2020-08-21 07:56 UTC
Labels: bug, plugins, waiting-for-release

**Comment by maclockard** [comment] 2023-05-08 18:25
I think there was a regression since I'm now seeing this in `@graphql-codegen/typescript-resolvers@3.2.0`
