### ISSUE TITLE
`pluckConfig` doesn't work with multiple tags

### ISSUE THREAD

**Issue by sarink** [dotansimha/graphql-code-generator#3858] opened 2020-04-11 18:16 UTC
**Describe the bug**
`config.pluckConfig` options set in `codegen.yml` are not being utilized by `graphql-tag-pluck`.

**To Reproduce**
Codesandbox link: https://codesandbox.io/s/quizzical-curie-mwbfn?file=/codegen.yml

(this example illustrates `modules` not working, but `magicComment` appears to be broken also)

**Comment by ardatan** [comment] 2020-04-11 19:04
```yml
schema: schema.graphql
documents: document.js
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
pluckConfig:
  modules:
    - name: ./foo
```
`pluckConfig` should be on root. It is listed together with `schema` and `documents` here;
https://graphql-code-generator.com/docs/getting-started/codegen-config
And `identifier` means export name.
https://codesandbox.io/s/goofy-https-vefyz?file=/codegen.yml:0-173

**Comment by sarink** [comment] 2020-04-11 19:09
Hey @ardatan thanks for your quick response. Can you also explain why this doesn't work?

https://codesandbox.io/s/quizzical-curie-mwbfn?file=/codegen.yml

I've set `magicComment:  __never__`, but  codegen is still parsing the `/* GraphQL */` comment tag, and thus throwing a  "duplicate query" error

**Comment by ardatan** [comment] 2020-04-11 19:12
It should be `gqlMagicComment`, docs needs to be updated. 
https://github.com/ardatan/graphql-toolkit/blob/master/packages/graphql-tag-pluck/src/index.ts#L8

**Comment by sarink** [comment] 2020-04-11 19:12
🎊 thank you!

**Comment by ardatan** [comment] 2020-04-11 19:14
Updated 👍 https://github.com/dotansimha/graphql-code-generator/commit/711b4e925b5177b3da4319c7cb067ba377020af5 Thank you

**Comment by sarink** [comment] 2020-04-11 23:07
@ardatan I am still having trouble with this... Can you tell me what configuration I would need to make this work? 

https://codesandbox.io/s/quizzical-curie-mwbfn

I'm in a unique situation of needing to query multiple schemas within the same module. I can't seem to understand why none of the graphql-code-generator options work for this 🤔

**Comment by ardatan** [comment] 2020-04-11 23:18
https://codesandbox.io/s/cocky-leaf-hrmge?file=/document.js
Using default export can be tricky because default export has no identifier so you cannot use it but you can override "gql" which is default identifier with yours.
Check the example, see how I did that.

**Comment by sarink** [comment] 2020-04-11 23:44
Hmm, I get an error when trying to use `import { gql as foo }` in my project, and using `import { default as foo }` yields the same error as before. How did you make it work?

**Comment by ardatan** [comment] 2020-04-12 01:48
You're right `gql as foo` gives an error but `{default as foo}` seems working

**Comment by sarink** [comment] 2020-04-12 03:58
I finally realized why it was working in codesandbox and not in my app... https://codesandbox.io/s/dank-flower-9vp0k?file=/codegen-foo.yml

`npm run codegen:foo` works, but `npm run codegen:bar` fails. Is it something to do with the `Gql` in the name? 🤯

**Comment by ardatan** [comment] 2020-04-12 11:05
You are exporting fooGql but importing foo without Gql. I changed/fixed it in the reproduction but it is still not working.
https://codesandbox.io/s/headless-dawn-e0tdv?file=/schema-bar.graphql

Let's reopen this issue until it is fixed.

**Comment by sarink** [comment] 2020-04-12 13:45
I've been digging through your source and gql tag pluck's source but I'm pretty lost. Any ideas?

**Comment by dotansimha** [comment] 2020-05-19 09:06
@sarink is it still relevant? can you please open an new issue for that?

**Comment by ardatan** [comment] 2020-05-27 15:59
Feel free to open the issue again if it is still relevant.

**Comment by sarink** [comment] 2020-05-28 14:37
The issue still exists. There's a codesandbox repo listed above. What more do you need?

**Comment by joshjg** [comment] 2020-06-08 17:49
```
import { default as foo } from 'graphql-tag';
```

I checked `graphql-tag-pluck` and saw that it won't work for this case because it compares against the original import name (`default`), not the aliased name.

https://github.com/ardatan/graphql-tools/blob/8f01f468303d9b2bf822ca4d1449d84f9a2b73bd/packages/graphql-tag-pluck/src/visitor.ts#L212

**Comment by dotansimha** [comment] 2020-06-09 07:43
That makes sense, thanks @joshjg ! 
@ardatan can you please take a look? I think we should check for the alias as well.

**Comment by dotansimha** [comment] 2020-06-10 06:46
@joshjg I checked it again and added tests for it. 

If you are using `import { default as foo } from 'graphql-tag';`, your configuration should be:

```
pluckConfig:
  modules:
    - name: graphql-tag
      identifier: default
```

The logic of graphql-tag-pluck seems correct, because [it looks for the identifier](https://github.com/ardatan/graphql-tools/blob/ae7c968deb2e6f51024a385abfc6455c0db5a5df/packages/graphql-tag-pluck/src/visitor.ts#L212), but then [uses the local alias](https://github.com/ardatan/graphql-tools/blob/ae7c968deb2e6f51024a385abfc6455c0db5a5df/packages/graphql-tag-pluck/src/visitor.ts#L223). 

I added a test here: https://github.com/ardatan/graphql-tools/blob/a91db791a15c908bf8aa59545731abdd7ab743f3/packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts#L44

**Comment by dotansimha** [comment] 2020-06-18 11:55
@joshjg Closing. Let me know if it's still relevant.

**Closed by dotansimha** 2020-06-18 11:55 UTC
Labels: dependencies, waiting-for-answer
