### ISSUE TITLE
Inconsistent behavior when configuring via codegen.yml and graphqlrc

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-code-generator#5013] opened 2020-11-02 13:09 UTC
**Describe the bug**
Hi. I was on my move from `codegen.yml` to using `.graphqlrc.yml` for all config for codegen, VSCode graphql and so on.

While doing so, I noticed that the same config behaved differently when using `codegen.yml` and when using `graphql-config`

eg:

**This works:** (codegen.yml)

```yml
schema:
  - './packages/modules/**/schema/**/*.gql'
generates:
  ./packages/core/src/generated/global.gql.types.generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
      - add:
          placement: prepend
          content: "import { DeepPartial } from 'utility-types';"
    config:
      defaultMapper: DeepPartial<{T}>
      federation: true
watch: true
overwrite: true
```

**This does not** (graphqlrc)

```yml
projects:
  globalgql:
    config:
      federation: true
    schema:
      - "./packages/modules/**/schema/**/*.gql"
    extensions:
      codegen:
        generates:
          ./packages/core/src/generated/global.gql.types.generated.ts:
            plugins:
              - typescript
              - typescript-operations
              - typescript-resolvers
              - add:
                  placement: prepend
                  content: "import { DeepPartial } from 'utility-types';"
            config:
              federation: true
              defaultMapper: DeepPartial<{T}>
```

I get schema validation error:

```
Error: Cannot extend type "AccountSchema" because it is not defined.

    Unknown directive "@key".

    Unknown directive "@external".

    Unknown directive "@key".

    Unknown type "AccountSchema".

    Cannot extend type "Mutation" because it is not defined.

    Cannot extend type "Query" because it is not defined.

    Unknown directive "@key".

    Unknown directive "@key".

    Unknown type "Query".

    Unknown type "Mutation".
        at assertValidSDL (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/graphql@15.4.0/node_modules/graphql/validation/validate.js:107:
11)
        at Object.buildASTSchema (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/graphql@15.4.0/node_modules/graphql/utilities/buildASTSc
hema.js:45:34)
        at makeSchema (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-tools/merge@6.2.5_graphql@15.4.0/node_modules/@graphql-too
ls/merge/index.cjs.js:976:99)
        at Object.mergeSchemasAsync (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-tools/merge@6.2.5_graphql@15.4.0/node_module
s/@graphql-tools/merge/index.cjs.js:967:12)
        at async Object.loadSchema (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-tools/load@6.2.5_graphql@15.4.0/node_modules/
@graphql-tools/load/index.cjs.js:650:20)
        at async /data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-codegen/cli@1.19.0_graphql@15.4.0/node_modules/@graphql-codegen/
cli/bin.js:845:55
        at async Task.task (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-codegen/cli@1.19.0_graphql@15.4.0/node_modules/@graph
ql-codegen/cli/bin.js:698:17)
```

After discussing with @ardatan I also tried adding `assumeValid: true` and `assumeValidSDL: true` and still had the same issue.

**Environment:**

- OS: Windows 10 Home host, Ubuntu 20.04 remote

```
"@graphql-codegen/add": "^2.0.1",
"@graphql-codegen/cli": "^1.19.0",
"@graphql-codegen/typed-document-node": "^1.17.9",
"@graphql-codegen/typescript": "^1.17.10",
"@graphql-codegen/typescript-operations": "^1.17.8",
"@graphql-codegen/typescript-resolvers": "^1.17.10",
```
- NodeJS: v14.14.0

**Additional context**

This might also be somewhat related to https://github.com/graphql/vscode-graphql/issues/250 since VSCode GraphQL also uses `graphql-config` and I have the same error there with `graphqlrc` file

**Comment by dotansimha** [comment] 2020-11-04 10:17
@kamilkisiela  what do you think?

**Comment by kamilkisiela** [comment] 2020-12-02 13:44
@tvvignesh could you check if you're using latest versions of `graphql-config`, `@graphql-tools/*` and `@graphql-codegen/*`? Please check it in your `yarn.lock` or `package-lock.json`.

**Comment by tvvignesh** [comment] 2020-12-02 14:35
@kamilkisiela Hi. I actually moved away from federation to stitching and hence this is no longer a problem for me. This problem might exist for others though.

And to your question, I have been using the latest versions of all of them (I update my deps once every 2 days). Also, I neither use NPM nor YARN but PNPM 😅 and while I did not check `pnpm-lock` before when this happened, I did check `package.json` and had all the latest versions of the deps (I might have to rollback so many commits and integrate back with federation if I have to test this again 😢)

Actually I had faced similar issues related to deps in `graphql-mesh` as well which was reported and fixed here: https://github.com/Urigo/graphql-mesh/issues/1131

**Comment by tvvignesh** [comment] 2020-12-02 14:46
And these were the deps I had when I posted this issue:

```json
  "devDependencies": {
    "@graphql-codegen/add": "^2.0.1",
    "@graphql-codegen/cli": "^1.19.0",
    "@graphql-codegen/typescript": "^1.17.10",
    "@graphql-codegen/typescript-operations": "^1.17.8",
    "@graphql-codegen/typescript-resolvers": "^1.17.10",
    "@graphql-eslint/eslint-plugin": "^0.4.1",
    "@graphql-typed-document-node/core": "^3.1.0",
    "@types/body-parser": "^1.19.0",
    "@types/express": "^4.17.8",
    "typedoc": "^0.19.2",
    "typescript": "4.0.3",
    "utility-types": "^3.10.0"
  },
  "dependencies": {
    "@graphql-codegen/typed-document-node": "^1.17.10",
    "@graphql-mesh/cache-file": "^0.4.17",
    "@graphql-mesh/cli": "^0.11.6",
    "@graphql-mesh/config": "^0.10.12",
    "@graphql-mesh/graphql": "^0.7.5",
    "@graphql-mesh/runtime": "^0.7.11",
    "@graphql-mesh/transform-prefix": "^0.5.15",
    "graphql": "^15.4.0",
    "graphql-modules": "^1.0.0-alpha.2",
    "graphql-tools": "^7.0.1"
  }
}
```

**Comment by gilgardosh** [comment] 2020-12-02 16:38
Closing due to not being reproducible. 
If someone's having a similar issue, open a new issue with a reproduction.

**Closed by gilgardosh** 2020-12-02 16:38 UTC
Labels: bug, dependencies
