### ISSUE TITLE
Different typing for input and output scalar

### ISSUE THREAD

**Issue by Sytten** [dotansimha/graphql-code-generator#6097] opened 2021-06-07 21:08 UTC
Currently when mapping a scalar for server side typing, there is only a one-to-one relation. But in reality the scalar are usually more permissive in what they accept. For exemple, the `ID` scalar can serialize basically integers and even objects.
So it would be nice to be able to set a different type for input and output.

**Describe the solution you'd like**
Using the scalar map:
```yaml
config:
  scalars:
    ID: 
      input: string
      output: string | number
```

**Describe alternatives you've considered**
None at the moment, you have to cast it in the resolver.

**Comment by n1ru4l** [comment] 2021-06-11 09:19
This is a duplicate of https://github.com/dotansimha/graphql-code-generator/issues/6097

**Comment by dotansimha** [comment] 2021-06-20 09:34
Duplicate: https://github.com/dotansimha/graphql-code-generator/issues/2588 https://github.com/dotansimha/graphql-code-generator/issues/2684

**Closed by dotansimha** 2021-06-20 09:34 UTC
