### ISSUE TITLE
preResolveTypes probably shouldn't touch enums

### ISSUE THREAD

**Issue by MarkKahn** [dotansimha/graphql-code-generator#2356] opened 2019-08-12 21:35 UTC
**Describe the bug**
`preResolveTypes` is resolving enums which is causing type errors because you can't assign a string literal back to an enum easily without casting it.

See this minimal [TS playground](http://www.typescriptlang.org/play/#code/KYOwrgtgBAZg9nKBvAUFKBBKBeKByDPAGjSgCEd8zjSBhSvWmgXxRQGM4QBnAFygAeALnyEoAHyp4J+Jg2oBuNjDAh2vAJZcoAIwCGAJwAUAB0N6II+HACUyNqxT7jAmwqA) showing the issue.

3. My `codegen.yml` config file:

```yml
preResolveTypes: true
```

**Expected behavior**

Instead of resolving to `field: 'A' | 'B' | 'C'`, resolve to `field: enumName`

**Environment:**

- `@graphql-codegen/1.5.0`: 
- NodeJS: 10.16.0

**Additional context**

**Comment by dotansimha** [comment] 2019-08-14 07:50
@MarkKahn duplicate of: https://github.com/dotansimha/graphql-code-generator/issues/2326

**Closed by dotansimha** 2019-08-14 07:50 UTC
Labels: bug, templates
