### ISSUE TITLE
Generated typescript recursive query types are wrong

### ISSUE THREAD

**Issue by freshollie** [dotansimha/graphql-code-generator#2631] opened 2019-09-25 01:39 UTC
**Describe the bug**
 

Because codegen relies heavily on Intersection types, typescript does not correctly check query fields which are optional, and allows nulls to go unchecked in code.

An example query:

```gql
type Query {
    categories(id: ID!): [Category!]!
}

type Category {
    id: ID!
    name: String!
    children: [Category!]
}
```

```gql
query GetCategories {
    categories(id: 1) {
        id
        name
        children {
            id
            name
            children {
                id
                name
            }
        }
    }
}

```

**To Reproduce**

Use the code sandbox:

https://codesandbox.io/s/graphql-codegen-issue-template-563vy

`yarn generate` will generate the query types for the nested query on `Category`

`test.ts` shows how these types provide no protection for null fields in typescript.

We generate some query response data which is a valid structure for the `GetCategoriesQuery` and then use that data in a function which uses the `Category` type as if it's children are not null (should throw an error)

`yarn build` will show how no type errors are generated from the types.

`yarn test` will show how a runtime error exists when the .length property is queried on the `children` field.

**Expected result**

`GetCategoriesQuery` should not be compatible with `Category` as `children` is not expected to be a `null` type in `Category`.

**Environment:**

- OS: MacOS
- `@graphql-codegen/...@1.7.0`: 
- NodeJS: 10

**Additional context**

Typescript has issues with intersections being tracked https://github.com/microsoft/TypeScript/issues/33243. Using them for generating these types seems to be the issue here, as manually generating the type without intersections correctly picks up the errors.

**Comment by dotansimha** [comment] 2019-09-25 04:51
@freshollie Maybe I'm missing something, not sure. 

In your use case, you are using:
```
children: [Category!]
```

Which means that `children` field could be `null`, but the array values must be set. If you wish to have a nullable type, you need to use `children: [Category!]!`.

With your schema, it seems to work for me in TS Playground:

![image](https://user-images.githubusercontent.com/3680083/65570040-7be97100-df68-11e9-85ae-74a35d5325e6.png)

And if I'm changing it to force a value there and make the field as non-nullable, it allow me to access it directly: 

![image](https://user-images.githubusercontent.com/3680083/65570148-ccf96500-df68-11e9-85e9-553133bf7804.png)

You shouldn't use `Category` type (generated by `typescript`) directly - it's a base type that contains all fields of the type, and then queries types can just `Pick` from it.  GraphQL let you choose the fields and it means that always there is a base type and a selection set based on that type.

If you wish to have a dedicated type for `Category` of your query, use GraphQL fragments and then you'll get a type per each fragment type and it will represent the actual representation of `Category` based on your fragment selection set.

**Comment by freshollie** [comment] 2019-09-25 07:29
Hey, thanks for the reply.

Firstly, the schema is correct for my requirements. I am using `[Category!]` as a `Category` may not have children, but when it does the children will not be null values.

Secondly, in my playground I am using the generated schema types directly, only to imitate the datatypes which would have come out of `useGetCategoriesQuery` etc. Notice I do not use the values of the data directly, as you have shown in your playground:

```typescript
import { GetCategoriesQuery } from "./types";

// This is the Category object I want to use with the data
// Notice that it doesn't accept null as a category value
interface Category {
  id: string;
  name: string;
  children?: Category[];
}

const printChildren = (children?: Category[]) => {
  if (children !== undefined) {
    console.log(children.length);
  }
};

// This function accepts only the Category type, so it
// shouldn't allow objects with nullable `children` to be provided
const handleCategories = (categories: Category[]) => {
  categories.forEach(category => printChildren(category.children));
};

const result: GetCategoriesQuery = {
  categories: [
    {
      id: "id",
      name: "name",
      children: null
    }
  ]
};

// No error when nullable children are provided
handleCategories(result.categories);
```

**Comment by freshollie** [comment] 2019-09-25 07:33
Also, for more info on the way Typescript treats intersection type, see this example.

```typescript
type Category = {
  id: string;
  children?: Category[];
};

type Maybe<T> = T | null;

type FetchedCategory = {
  id: string;

  children: Maybe<Array<FetchedCategory>>;
};

const a: FetchedCategory[] = [
  {
    id: "a",
    children: null,
  },
];

// No error, because what?
const b: Category[] = a;

// Error, children cannot be null
const c: Category[] = [
  {
    id: "a",
    children: null,
  },
];
```

**Comment by n1ru4l** [comment] 2019-09-25 07:45
I think a code sandbox reproduction would be helpful. Please also include your typescript config.

**Comment by freshollie** [comment] 2019-09-25 07:49
My original comment: 

> 
> Use the code sandbox:
> 
> https://codesandbox.io/s/graphql-codegen-issue-template-563vy
> 
> `yarn generate` will generate the query types for the nested query on `Category`
> 
> `test.ts` shows how these types provide no protection for null fields in typescript.
> 
> We generate some query response data which is a valid structure for the `GetCategoriesQuery` and then use that data in a function which uses the `Category` type as if it's children are not null (should throw an error)
> 
> `yarn build` will show how no type errors are generated from the types.
> 
> `yarn test` will show how a runtime error exists when the .length property is queried on the `children` field.
> 
> **Expected result**
> 
> `GetCategoriesQuery` should not be compatible with `Category` as `children` is not expected to be a `null` type in `Category`.

**Comment by n1ru4l** [comment] 2019-09-25 08:40
@freshollie Sorry!

```diff
type Category = {
  id: string;
-  children?: Category[];
+  children: Category[] | null;
};
```

https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAwghsCBzA9gJxFAvFA3gKCigEsATALigGdg1iA7JAbkKgGMALYgG1LQnqV4iVBgDaAXSgAfKPQCu3biwC+LfKEhQAsnBAAjCAB4AKgD5sUEzLmLl+DeGgAxCME4RSw5Okw5cJBTUtAxIUCpQAGR4rJw8fAKUugbGAIJoaHpGru4cnt6iIGZmqupsKPQ0UHCUOR5eCD7iUjhirARERGSUAERwPQA0rERxvPyCtkpDRCpDEuoA9AtQAHIoUBAZ6ANQhmxw8lTQAO4cCAD8+OWVwLtCjYWSlnCLywCiW2g7own07HD0egoW6GSbcK4VKpse4iXxPVrtYaBXr9aadH7jSgKKasWb4eZAA

I am having a hard time understanding your issue.

**Comment by freshollie** [comment] 2019-09-25 08:49
@n1ru4l notice the first assignment `b = a` in my example is valid, even though the data in `c` is exactly the same. Typescript doesn't highlight `b = a` as bad because it sees the intersection type in `a` wrongly.

Yes, I followed the examples in there to generate my query. 

Your changes to the test.ts file do not solve the issue. Run `test.ts` with `yarn test` and see how even though typescript highlighted no issues with the file there is a runtime null exception.

**Comment by freshollie** [comment] 2019-09-25 08:52
I will point out what I am trying to show with the example source with typescript intersections:

```typescript
const a: FetchedCategory[] = [
  {
    id: "a",
    children: null,
  },
];

// No error, because what? (THIS IS WRONG THERE SHOULD BE AN ERROR HERE)
const b: Category[] = a;

// Error, children cannot be null (THIS IS CORRECT, NULL IS NOT ASSIGNABLE TO CHILDREN)
const c: Category[] = [
  {
    id: "a",
    children: null,
  },
];
```

**Comment by n1ru4l** [comment] 2019-09-25 08:54
> Your changes to the test.ts file do not solve the issue. Run test.ts with yarn test and see how even though typescript highlighted no issues with the file there is a runtime null exception.

```
sandbox@sse-sandbox-ldmhy:/sandbox$ yarn test
yarn run v1.16.0
$ ts-node test.ts
0
Done in 3.72s.
```

**Comment by freshollie** [comment] 2019-09-25 08:59
Oops, didn't see your logic change.

```typescript
const printChildren = <T extends {}>(children: T[]) => {
  if (children) {
    console.log(children.length);
  }
};
```

Yes, you are correct this solves the issue with the code, but is not the point in typescript and codegen to highlight issues with code before they show at runtime? 

Yes, I could fix my code by changing `children?: Category[]` to `children?: Category[] | null` but this isn't the point. 

The point is that I had to find this by mistake by accident, my types should have picked this up when assigning the output of the graphql query to my funciton which uses `Category[]`

**Comment by n1ru4l** [comment] 2019-09-25 09:10
What is the point of redeclaring types you already generated? 

What exactly could graphql-codegen change to solve your problem?

**Comment by freshollie** [comment] 2019-09-25 09:41
Ignore the crudeness of the example I provide. The idea is that obviously I might want to use the GraphQL query data in a function which has an interface expecting a type. For example a React Component.

In this case, I should transform the data from the query response to remove the null types as the interface doesn't accept them. However, this was not highlighted. The point in the graphql types is it is supposed to highlight these issues and require the developers to make the correct data transformations in order to conform to the interface.

In the examples I have given this is not happening, due to the way codegen generates the types.

**Comment by n1ru4l** [comment] 2019-09-25 10:09
The idea of GraphQL is to generate a schema that is consumed by the client without the need for transformation. Ideally, your Schema should represent the UI structure of your application. Of course, I can understand that this is not always possible.

> In the examples I have given this is not happening, due to the way codegen generates the types.

Sorry for repeating my question: What exactly could graphql-codegen change to solve your problem?

**Comment by freshollie** [comment] 2019-09-25 10:59
The type generated for the query is:

```typescript
export type GetCategoriesQuery = (
  { __typename?: 'Query' }
  & { categories: Array<(
    { __typename?: 'Category' }
    & Pick<Category, 'id' | 'name'>
    & { children: Maybe<Array<(
      { __typename?: 'Category' }
      & Pick<Category, 'id' | 'name'>
      & { children: Maybe<Array<(
        { __typename?: 'Category' }
        & Pick<Category, 'id' | 'name'>
      )>> }
    )>> }
  )> }
);
```

Which should be equal to

```typescript
export type FixedGetCategoriesQuery = {
  __typename?: "Query";
  categories: Array<{
    id: string;
    name: string;
    __typename?: "Category";
    children?: Maybe<
      Array<{
        id: string;
        name: string;
        __typename?: "Category";
        children?: Maybe<
          Array<{
            id: string;
            name: string;
            __typename?: "Category";
            children?: Maybe<
              Array<{
                id: string;
                name: string;
                __typename?: "Category";
              }>
            >;
          }>
        >;
      }>
    >;
  }>;
};
```

When using this fixed query, typescript correctly highlights the type issues: 

```

**Comment by freshollie** [comment] 2019-09-25 11:01
Does this makes sense? I understand Pick is useful for being able to use the base type, but using intersection in typescript does not behave as expected.

**Comment by n1ru4l** [comment] 2019-09-25 11:24
@freshollie https://graphql-code-generator.com/docs/plugins/typescript-operations#preresolvetypes-boolean-default-value-false

**Comment by freshollie** [comment] 2019-09-25 11:32
@n1ru4l yes! This creates the create types for the query!

Do you see the issue though? By default this query is not type checked correctly, so why even generate it?

**Comment by n1ru4l** [comment] 2019-09-25 12:13
@freshollie Shouldn't this be fixed once typescript 3.7 is out? (https://github.com/microsoft/TypeScript/issues/33243)

**Comment by freshollie** [comment] 2019-09-25 12:23
I testing with `typescript@next`(3.7) and it didn't fix the issue.

**Comment by n1ru4l** [comment] 2019-09-25 12:25
@freshollie I think it will take a while until it is done... (https://github.com/microsoft/TypeScript/milestone/98)

@dotansimha How do you feel about this?

**Comment by freshollie** [comment] 2019-09-25 12:30
Yeah, advice I got was it's not 100% likely this issue gets fixed with 3.7 as the goals of the milestone change. Why is the generation with Pick the default if it doesn't work as intended?

**Comment by n1ru4l** [comment] 2019-09-25 12:37
> Why is the generation with Pick the default if it doesn't work as intended?

Because you are the first person that experienced this issue and you reported it today 😉

**Comment by freshollie** [comment] 2019-09-25 12:38
Oh, I didn't mean to be so abrupt. I meant to mean, why does the option exist :P

**Comment by freshollie** [comment] 2019-09-30 10:36
@dotansimha @n1ru4l any conclusions on this? To summaries: `preResolveTypes: true` fixes our issue, so I am fine to close. 

Other people may encounter this and `preResolveTypes: true` is not enabled by default, so documenting this behaviour might be the solution?

**Comment by n1ru4l** [comment] 2019-09-30 11:28
I still think this is an issue with typescript that should be documented.

**Comment by dotansimha** [comment] 2019-10-02 05:09
@freshollie Thanks, closing for now. The current default is using `Pick` but I think maybe we can change it in a future version, we just need to make sure preResolveTypes is stable and has no issues.

**Closed by dotansimha** 2019-10-02 05:09 UTC
Labels: waiting-for-answer
