### ISSUE TITLE
 → Must provide Source. Received: {}

### ISSUE THREAD

**Issue by jerlam06** [dotansimha/graphql-code-generator#1387] opened 2019-03-01 09:58 UTC
**Describe the bug**
I get this error when I run gql-gen: "Must provide Source. Received: {}"

```
> Generate src/generated/graphql.ts
      × Load GraphQL schemas
        → Must provide Source. Received: {}
```

Here is my codegen.yml:

````
schema: './src/graphql/schema.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript-react-apollo'
````

What does "Must provide Source" mean?

**Comment by dotansimha** [comment] 2019-03-01 10:17
Hi @jerlam06 !
Can you please share your schema file? It looks like it's not being loaded correctly.

**Comment by jerlam06** [comment] 2019-03-01 10:26
Hi @dotansimha, thanks for the answer.
Well it is really huge, about 10k lines. It was extracted from hasura. So I guess some syntax in the file isn't rigth?

**Comment by dotansimha** [comment] 2019-03-01 10:48
Yeah, I think so. Can you please try to copy/paste it into https://astexplorer.net and see if you are getting an error?

**Comment by dotansimha** [comment] 2019-03-01 10:48
And also, any chance you can create a repo with a minimal reproduction? This way I'll be able to test it locally. Thanks!

**Comment by dotansimha** [comment] 2019-03-01 10:54
@jerlam06 can you also try this config?
```yml
schema: src/graphql/schema.graphql
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript-react-apollo
```

**Comment by ardatan** [comment] 2019-03-02 17:03
@jerlam06 Do you have `documents` field in your configuration? Because if you don't, `react-apollo` generator won't work properly.

**Comment by dotansimha** [comment] 2019-03-18 08:38
@jerlam06 Closing for now. Feel free to open a new issue if it's still relevant.

**Closed by dotansimha** 2019-03-18 08:38 UTC
Labels: waiting-for-answer
