### ISSUE TITLE
Incorrect error "Unable to find parent type! Please make sure you operation passes validation" when using near-operation-file and @include

### ISSUE THREAD

**Issue by asfernandes** [dotansimha/graphql-code-generator#5002] opened 2020-10-29 19:03 UTC
**Describe the bug**
Incorrect validation error when using `near-operation-file`.

**To Reproduce**
Easy way to reproduce: go to https://graphql-code-generator.com/ and set "Operations types (near-operation-file)".

With "Operations types" it works.

Use this `operation.graphql`:

```graphql
query chats {
  myChats {
    ...ChatFields
  }
}

fragment ChatFields on Chat {
  id
  ...@include(if: true) {
      id
      messages {
          id
      }
  }
}
```

**Environment:**

- OS: Windows

- package.json
```
    "@graphql-codegen/add": "^2.0.1",
    "@graphql-codegen/cli": "1.19.0",
    "@graphql-codegen/introspection": "1.18.0",
    "@graphql-codegen/near-operation-file-preset": "^1.17.11",
    "@graphql-codegen/typed-document-node": "^1.17.9",
    "@graphql-codegen/typescript": "1.17.11",
    "@graphql-codegen/typescript-operations": "1.17.8",
    "@graphql-codegen/typescript-react-apollo": "2.0.7",
```

- NodeJS: 10.18.1

**Comment by dotansimha** [comment] 2020-11-04 10:26
Hi @asfernandes ,
We are currently working on adding support for `@skip` / `@include` directives, see: https://github.com/dotansimha/graphql-code-generator/pull/5017 
Closing (duplicate of https://github.com/dotansimha/graphql-code-generator/issues/3836)

**Comment by asfernandes** [comment] 2020-11-04 10:56
> Hi @asfernandes ,
> We are currently working on adding support for `@skip` / `@include` directives, see: #5017
> Closing (duplicate of #3836)

The issue I have here (specific with near-operation-file) seems broad than what is described in #3836 which talks only about the types. Is this issue tracked there as well?

**Comment by dotansimha** [comment] 2020-11-04 10:58
I see. Let me give this a look. I this your actual error is coming from the fact that the inline fragment you are using isn't named, while codegen assumes it must be.

Changing the fragment to this:

```graphql

fragment ChatFields on Chat {
  id
  ... on Chat @include(if: true) {
      id
      messages {
          id
      }
  }
}
```

Should fix that.

**Comment by dotansimha** [comment] 2020-11-04 15:10
@asfernandes I think I managed to fix it in: https://github.com/dotansimha/graphql-code-generator/pull/5036 

The actual error was really related to the preset. In this preset we ignore documents validation because we want to support partial documents. The code there assumes that every inline-fragment has typeCondition defined. I fixed that to support fragments without typeCondition (by using the parent selection-set type). 

Can you please give it a try? we have an alpha version for this PR: `@graphql-codegen/near-operation-file-preset@1.17.12-alpha-ec31a5e1.0`

**Comment by dotansimha** [comment] 2020-11-05 08:30
Fixed in `@graphql-codegen/near-operation-file-preset@1.17.12`.

**Closed by dotansimha** 2020-11-05 08:30 UTC
Labels: bug, plugins

**Comment by asfernandes** [comment] 2020-11-05 11:31
It worked for me. Thanks!

Not related with this ticket, I have a doubt about near-operation-file.

I created two `.graphql` files. It generates the modular `.ts` files. That's ok.

But my `.graphql` can not have duplicate names (for example fragments). Does it make sense in all cases?

I would like to have local names too, valid only in that specific `.graphql` file.

**Comment by dotansimha** [comment] 2020-11-16 21:16
@asfernandes i'm not sure i fully understood, can you please share an example?

**Comment by asfernandes** [comment] 2020-11-17 11:15
In the system I'm working, I have (in the frontend) a service layer doing graphql calls. This IMO is something like the API (client) of the API (graphql) and seems very burocratic.

In this service layer we prefix fragments and query names which something to make them not ambiguous over the project. This is currently being done with apollo client and generator.

I do want to switch to graphql-code-generator but eliminating this service layer so components can have a specific `.graphql` file with their queries.

From the point of generated files, that's ok, the files are modular and do not clash with another ones.

But fragments and queries names still need to have unique names which is very difficult in this context. Some components may have slight similar queries which may have (in the context of the component) a name equal to another one in another component.

The problem turns to be more difficult because the whole ecosystem. The apollo graphql extension I use in VSCode also thinks query/fragment names must be unique over the entire project.

I like how sass does it. You can have local styles:

```scss
:local(.component) {
	min-width: 33em;
	max-width: 90em;
}
```

**Comment by dotansimha** [comment] 2021-01-21 12:42
@asfernandes If you have some kind of separation, you can have it in codegen as well. 
With presets, You can either use `near-operation-file` preset (that allow you to have duplicate names), or,  you can generate a single `types.ts` for your base types (based on `typescript` plugin), and then have separate sections that allow you to generate group of operations into a single file. 

Most tools in the GraphQL ecosystem (Apollo, Relay for example) does require you to have unique fragment names and operations, and graphql-js validation also checks that. That's the reason we decided to go with this direction.
