### ISSUE TITLE
Invalid operation types when using nested fragment and skipTypename

### ISSUE THREAD

**Issue by Kcazer** [dotansimha/graphql-code-generator#3950] opened 2020-04-29 19:37 UTC
**Describe the bug**

The generated types for operations references non-existing types when using nested fragment and `skipTypename: true` 

**To Reproduce**

https://codesandbox.io/s/sleepy-chebyshev-tqgrh?file=/types.ts

1. My GraphQL schema:

```graphql
schema {
  query: Query
}

type Query {
  animals: [Animal!]!
}

interface Animal { id: ID! }
type Duck implements Animal { id: ID! }
type Lion implements Animal { id: ID! }
type Puma implements Animal { id: ID! }
type Wolf implements Animal { id: ID! }
```

2. My GraphQL operations:

```graphql
fragment CatFragment on Animal {
  ... on Lion { id }
  ... on Puma { id }
}

query kitty {
  animals { ...CatFragment }
}
```

3. My `codegen.yml` config file:

```yml
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      skipTypename: true
```

**Generated types**

```ts
type CatFragment_Lion_Fragment = Pick<Lion, "id">;
type CatFragment_Puma_Fragment = Pick<Puma, "id">;

export type CatFragmentFragment =
  | CatFragment_Lion_Fragment
  | CatFragment_Puma_Fragment;

export type KittyQuery = {
  animals: Array<
    | CatFragment_Duck_Fragment
    | CatFragment_Lion_Fragment
    | CatFragment_Puma_Fragment
    | CatFragment_Wolf_Fragment
  >;
};
```

**Expected behavior**

It should use the generated fragment type in the query

```ts
type CatFragment_Lion_Fragment = Pick<Lion, "id">;
type CatFragment_Puma_Fragment = Pick<Puma, "id">;

export type CatFragmentFragment =
  | CatFragment_Lion_Fragment
  | CatFragment_Puma_Fragment;

export type KittyQuery = {
  animals: Array<CatFragmentFragment>;
};
```

**Environment:**

- `@graphql-codegen/typescript`: 1.13.3
- `@graphql-codegen/typescript-operations`: 1.13.3
- NodeJS: 10.20

**Comment by ericbiewener** [comment] 2021-06-18 22:55
Looks like this bug still exists with the following versions:

```
    "@graphql-codegen/cli": "1.21.5",
    "@graphql-codegen/core": "1.17.10",
    "@graphql-codegen/import-types-preset": "1.18.2",
    "@graphql-codegen/introspection": "1.18.2",
    "@graphql-codegen/schema-ast": "1.18.3",
    "@graphql-codegen/typescript": "1.22.1",
    "@graphql-codegen/typescript-operations": "1.18.0",
```

**Comment by dotansimha** [comment] 2021-06-20 14:22
> Looks like this bug still exists with the following versions:
> 
> ```
>     "@graphql-codegen/core": "1.17.10",
>     "@graphql-codegen/typescript": "1.22.1",
>     "@graphql-codegen/typescript-operations": "1.18.0",
> ```

Just as a side-note: You don't have to use `core` explicitly (unless you use programmatic API).

**Comment by dotansimha** [comment] 2021-06-20 15:05
Just writing this here because some developers asked that, and it seems related to the topic here.

If you have `interface Animal` and you have 4 `type`s that implements this interface, it means that the fields that are defined as `Animal` in their return type, can return all 4 options of that type. 

```graphql
type Query {
  animals: [Animal!]! # This field can return Duck/Lion/Puma/Wolf
}

interface Animal { id: ID! }
type Duck implements Animal { id: ID! }
type Lion implements Animal { id: ID! }
type Puma implements Animal { id: ID! }
type Wolf implements Animal { id: ID! }

```

And that's regardless of the fragments or queries that you are asking for. 

For example, if you are querying for the `animals` field, and you have fragments from `Duck` and `Lion` - that means that you ask for specific fields in case of a Duck/Lion, but you'll get an empty object in case of `Puma` and `Wolf` are returned. **It doesn't apply a filter, it's just a selection set**.

For the specific point on that issue: 

Seems like we have a real issue here with the missing fragments that codegen generates. I managed to reproduce that in:  https://github.com/dotansimha/graphql-code-generator/pull/6161

Seems like we skip generation of fragment sub-types when `skipTypename: true`. So actually, the result of the generation should still be: 

```ts
export type KittyQuery = {
  animals: Array<
    | CatFragment_Duck_Fragment
    | CatFragment_Lion_Fragment
    | CatFragment_Puma_Fragment
    | CatFragment_Wolf_Fragment
  >;
};
```

But the references fragments like `CatFragment_Duck_Fragment` should be defined as:

```
type CatFragment_Duck_Fragment = {}
```

**Comment by dotansimha** [comment] 2021-06-30 10:43
Fixed in `@graphql-codegen/typescript-operations@1.18.3`

**Closed by dotansimha** 2021-06-30 10:43 UTC
Labels: bug/2-confirmed, stage/5-alpha-release-testing
