### ISSUE TITLE
Types are not correct for federated extended types

### ISSUE THREAD

**Issue by lgandecki** [dotansimha/graphql-code-generator#4291] opened 2020-06-25 12:52 UTC
**Describe the bug**
The field resolvers types generated for federated types have too many things available on the parent object.

**To Reproduce**
I've shown some examples here:

https://codesandbox.io/s/fancy-wave-74cxh?file=/ProductResolvers.ts

Basically, for this schema:

```graphql
extend type Product @key(fields: "sku") {
    sku: ID! @external
    size: Int @external
    weight: Int @external
    shippingEstimate: Int @requires(fields: "size weight")
    simpleShippingEstimate: Int
}
```

`shippingEstimate` should have `size`, `weight` and `sku`
and `simpleShippingEstimate` should only have `sku` available to it.
Unfortunately, they both get everything. This way programmers can make mistakes that can't be caught with types, unit tests, and would force us to write higher level graphql tests - but the problem is that I don't really want to test the connection between type definition in the schema and it's implementation through queries. In this service I might not even have a query that returns a Product - I might only want to extend a Product that's defined and exposed somewhere else. 

I've actually made a tool for that - https://github.com/xolvio/federation-testing-tool , (which would dynamically create a _getProduct query for testing environment, among other things) but I really would rather not use it :-) it's useful for things like workshops, libraries, or more low level code, but for just making resolvers and testing them, I'd prefer to stick with types and unit tests. The way your fantastic tooling allows me to do with pretty much everything else :) 

Is this on the roadmap? Do you guys agree that this is a problem? I could try to work on this, maybe with little help. 

Thanks!

**Comment by dotansimha** [comment] 2020-06-30 09:53
Hi @lgandecki ! It seems like a duplicate of https://github.com/dotansimha/graphql-code-generator/issues/4089 

There is a WIP PR here: https://github.com/dotansimha/graphql-code-generator/pull/4232

**Closed by dotansimha** 2020-06-30 09:53 UTC
