### ISSUE TITLE
gql-tag preset: Issue with indention

### ISSUE THREAD

**Issue by tobiasdiez** [dotansimha/graphql-code-generator#6449] opened 2021-08-09 10:39 UTC
**Describe the bug**
 

The graphql query passed to the generated `gql` function is not recognized due a mismatch in the indention.

**To Reproduce**
1. Define a graphql query as
```ts
    const checkLoggedIn = gql(/* GraphQL */ `
      query CheckLoggedIn {
        me {
          id
        }
      }
    `)
```
2. Run the code generation using the `gql-tag preset`
3. Observe that `checkLoggedIn` has type unknown.

The problem is the indention. The generated gql file has the following signature
```
export function gql(source: "query CheckLoggedIn {\n  me {\n    id\n  }\n}"): (typeof documents)["query CheckLoggedIn {\n  me {\n    id\n  }\n}"];
```
but the argument has additional indention. Indeed, if I remove the fallback to `unknown` in the generated gql method, then I get the following error:
```
Argument of type '"\n      query CheckLoggedIn {\n        me {\n          id\n        }\n      }\n    "' is not assignable to parameter of type '"query CheckLoggedIn {\n  me {\n    id\n  }\n}"'
```
Note the additional newline at the start, and the different amount of whitespace.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
documents:  - 'src/**/*.ts'  - '!src/gql/**/*'generates:  ./src/gql/:    preset: gql-tag-operations-preset
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: 
- `@graphql-codegen/...`: latest
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by ardatan** [comment] 2021-08-09 10:48
Could you share a reproduction on CodeSandbox? Thanks!

**Comment by tobiasdiez** [comment] 2021-08-09 11:18
I tried, but only leads to another error: https://codesandbox.io/s/vibrant-haibt-qogmm?file=/codegen.yml
```
  ✖ Parse configuration
    → Cannot read property 'length' of undefined
    Generate outputs
  Cannot read property 'length' of undefined
```

**Comment by n1ru4l** [comment] 2021-08-10 07:32
@tobiasdiez There were some dependencies such as `graphql` missing. I added missing dependencies and added a tsconfig.json, I was able to run codegen successfully.

https://codesandbox.io/s/objective-platform-qg90m?file=/src/gql/index.ts

I could observer the following two issues:

## CLRF Line endings 

The test.ts used those and because of that the string type could not be correctly inferred. By changing all files line endings to `LF` everything worked fine.

## Invalid document references

This is the generated output:

```ts
const documents = {
    "\n  query user {\n    user(id: 1) {\n      id\n      username\n      email\n    }\n  }\n": graphql.userDocument,
};
```

However, It should be:

```ts
const documents = {
    "\n  query user {\n    user(id: 1) {\n      id\n      username\n      email\n    }\n  }\n": graphql.UserDocument,
};
```

It seems like this is caused because you wrote the operation name with a lower-case letter. Seems like this is an edge case that is not addressed and we should fix.

After changing `query user` to `query User` everything worked as expected.

```ts
const Test = gql(/* GraphQL */ `
  query User {
    user(id: 1) {
      id
      username
      email
    }
  }
`);
```

**Comment by n1ru4l** [comment] 2021-08-10 07:40
@tobiasdiez https://github.com/dotansimha/graphql-code-generator/blob/19e8768f9d43bfc5e69b7b1e05eafccca0400e6f/packages/plugins/typescript/gql-tag-operations/src/index.ts#L54 here something must go wrong - if you could have a look that would be highly appreciated! Otherwise, I will try to have a look at this later this week!

**Comment by tobiasdiez** [comment] 2021-08-10 09:21
Thanks @n1ru4l for fixing the codesandbox. 

In the meantime, I was able to debug the problem a bit and could trace it the following location in the graphql-tag-pluck package:
https://github.com/ardatan/graphql-tools/blob/2fd7432829a729bfcabc53379168145d27818344/packages/graphql-tag-pluck/src/visitor.ts#L194

For me locally, `options` is an empty object and hence `freeText` is called with the second argument `skipIndentation = false`, which erases the indention. If I pass `skipIndentation = true` then the indention is preserved. What I was not yet able to figure out is where `options` is originally defined, and why it is empty in my case while in the codesandbox it is not.

**Comment by n1ru4l** [comment] 2021-08-10 09:48
@tobiasdiez Maybe you have something overriding dependencies? You might wanna check your lock file

**Comment by tobiasdiez** [comment] 2021-08-10 10:40
I thought so as well, but after further debugging I think it is an issue in the code-generator.

The only place I could find where the pluckConfig is specified is this one here:
https://github.com/dotansimha/graphql-code-generator/blob/b0cb13df418632b2b82c24129770f2b2a281e849/packages/graphql-codegen-cli/src/load.ts#L81-L84
However, for me this code is never executed. Instead, the code flow is as follows:

- Load GraphQL documents: https://github.com/dotansimha/graphql-code-generator/blob/440172cfe7a5df79c491f14442ab8fa47714b5da/packages/graphql-codegen-cli/src/codegen.ts#L223
- LoadDocuments: https://github.com/dotansimha/graphql-code-generator/blob/440172cfe7a5df79c491f14442ab8fa47714b5da/packages/graphql-codegen-cli/src/config.ts#L305
- LoadDocuments in graphql-config: https://github.com/kamilkisiela/graphql-config/blob/89767c8b3dc56a930f42e5e96bcbc43bd5644f41/src/project-config.ts#L208

There `this._extensionsRegistry.loaders.documents` contains a code-loader, but with an empty config as it is defined here:
https://github.com/dotansimha/graphql-code-generator/blob/6734c58055d283f051bf32f115f2308000e56431/packages/graphql-codegen-cli/src/graphql-config.ts#L16

In fact, after adding the pluckConfig there as well, everything is working. 

Still don't know how to reproduce this...

**Comment by n1ru4l** [comment] 2021-08-10 11:53
@tobiasdiez Could it be possible that your documents are loaded via graphql-config config files?

**Comment by tobiasdiez** [comment] 2021-08-10 12:02
Yes, this is indeed the case! This is the configuration I'm using https://github.com/JabRef/JabRefOnline/blob/5433703234b7484813c1e66f5c2735ed827db2ad/graphql.config.js#L32-L44

**Comment by n1ru4l** [comment] 2021-08-10 12:17
Then I think resolving this issue is a s easy as adding the config here: https://github.com/dotansimha/graphql-code-generator/blob/6734c58055d283f051bf32f115f2308000e56431/packages/graphql-codegen-cli/src/graphql-config.ts#L16

**Comment by padorang684** [comment] 2021-08-14 02:22
I had the exact same issue, I was able to resolve it by setting the version of `@graphql-tools/code-file-loader` to `7.0.1` using `resolutions` in `package.json`. `@graphql-tools/code-file-loader@7.0.3` seems to have introduced a breaking change, causing this issue

**Comment by n1ru4l** [comment] 2021-08-17 20:09
@tobiasdiez Can you please double confirm that https://github.com/dotansimha/graphql-code-generator/pull/6494 does resolve this issue for you?

**Comment by n1ru4l** [comment] 2021-08-19 06:55
@tobiasdiez @padorang684 A fix is now on master.

**Closed by n1ru4l** 2021-08-19 06:55 UTC
Labels: stage/5-alpha-release-testing

**Comment by n1ru4l** [comment] 2021-08-19 15:52
I also pushed a fix for https://github.com/dotansimha/graphql-code-generator/issues/6449#issuecomment-895799151 `Invalid document references`  over here https://github.com/dotansimha/graphql-code-generator/pull/6513

Will release all that stuff later!

**Comment by tobiasdiez** [comment] 2021-08-19 16:44
@n1ru4l Thanks for the quick fixes. I tried it with what I found to be the latest versions
```
    "@graphql-codegen/cli": "2.1.0-alpha-ae01a8c41.0",
    "@graphql-codegen/fragment-matcher": "^3.1.0",
    "@graphql-codegen/gql-tag-operations-preset": "1.0.2-alpha-59f86a621.0",
    "@graphql-codegen/typed-document-node": "2.0.1-alpha-59f86a621.0",
    "@graphql-codegen/typescript": "2.0.1-alpha-59f86a621.0",
    "@graphql-codegen/typescript-operations": "2.0.2-alpha-59f86a621.0",
    "@graphql-codegen/typescript-resolvers": "2.0.1-alpha-59f86a621.0",
```
However, this reults in the following error when running codegen:
```
TypeError: pluginHelpers.getCachedDocumentNodeFromSchema is not a function
        at transformSchemaAST (D:\Programming\JabRefOnline\node_modules\@graphql-codegen\typescript\index.js:336:35)
        at Object.plugin (D:\Programming\JabRefOnline\node_modules\@graphql-codegen\typescript\index.js:353:38)
        at executePlugin (D:\Programming\JabRefOnline\node_modules\@graphql-codegen\core\index.js:38:35)
        at D:\Programming\JabRefOnline\node_modules\@graphql-codegen\core\index.js:116:30
        at Array.map (<anonymous>)
        at Object.codegen (D:\Programming\JabRefOnline\node_modules\@graphql-codegen\core\index.js:106:54)
        at process (D:\Programming\JabRefOnline\node_modules\@graphql-codegen\cli\bin.js:999:67)
        at Array.map (<anonymous>)
        at D:\Programming\JabRefOnline\node_modules\@graphql-codegen\cli\bin.js:1006:63
        at async Task.task (D:\Programming\JabRefOnline\node_modules\@graphql-codegen\cli\bin.js:785:17)
```
I'm not sure, but maybe the reason is that `@graphql-codegen/gql-tag-operations` still depends on `"@graphql-codegen/plugin-helpers" "^2.0.0"`?

**Comment by n1ru4l** [comment] 2021-08-19 16:54
https://github.com/dotansimha/graphql-code-generator/pull/6441 those are the latest versions

**Comment by tobiasdiez** [comment] 2021-08-19 17:26
Oh, I missed this. I can confirm that the capitalization problem is fixed. Sadly, however, the indention problem is still the same...the generated code still doesn't contain the leading indention. I think the issue is that #6494 added the pluckConfig for the schema loader, but not for documents. If I change
https://github.com/dotansimha/graphql-code-generator/blob/1928848d6f1df0c07828026e260caf0933a8bc05/packages/graphql-codegen-cli/src/graphql-config.ts#L22
to include the same changes, then it works.

**Comment by n1ru4l** [comment] 2021-08-19 17:37
@tobiasdiez Can you send a PR?
