### ISSUE TITLE
Optional query input array variable can accept non-array values

### ISSUE THREAD

**Issue by csandanov** [dotansimha/graphql-code-generator#7480] opened 2022-02-07 06:59 UTC
**Describe the bug**
Optional query array variable can accept non-array value

**To Reproduce**

[Steps to reproduce the behavior:](https://codesandbox.io/s/autumn-sun-i4sq8?file=/types.ts)

1. My GraphQL schema:

```graphql
type Query {
    users(ids: [ID!]): [User!]!
}

type User {
    id: ID!
    username: String!
    email: String!
}

```

2. My GraphQL operations:

```graphql
query users($ids: [ID!]) {
    users(ids: $ids) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

4. See `types.ts`: type of `id` field in `UsersQueryVariables` generated as `InputMaybe<Array<Scalars['ID']> | Scalars['ID']>;` despite it being defined as optional array. Before I updated to the latest version it worked fine – generated as `InputMaybe<Array<Scalars['ID']>>`;.

**Expected behavior**

`id` field in `UsersQueryVariables` should have type `InputMaybe<Array<Scalars['ID']>>;`

**Environment:**

- OS: macOS 12.1
- `@graphql-codegen/cli`: 2.5.0
- NodeJS: 17.4.0

**Comment by csandanov** [comment] 2022-02-07 07:03
I guess that's by design, for convenience when you have just one value, but that's kind of annoying when you read/write from cache and want to use types – you have to additionally check if it's array or not

**Comment by vigie** [comment] 2022-04-11 19:05
This is happening because the latest version of `@graphql-codegen/typescript-operation` offers the option `arrayInputCoercion` with the default value of true.

That is, by default, any input array types can also accept a singular value.

It is correct to add this behavior per [GQL spec](https://spec.graphql.org/draft/#sel-FAHjBJFCAACE_Gh7d)

The bug to fix is that there is no corresponding behavior in `@graphql-codegen/typescript` to generate the input types to allow for the singular value. There should be similar `arrayInputCoercion` option added here with the same default behavior so that these plugins align.

For now we need to do disallow `arrayInputCoercion` in `@graphql-codegen/typescript-operation`

**Comment by charlypoly** [comment] 2022-05-18 08:30
Hi @csandanov,

this issue is a duplicate of https://github.com/dotansimha/graphql-code-generator/issues/5352 which can be solved by using the `arrayInputCoercion` config mentioned by @vigie

**Closed by charlypoly** 2022-05-18 08:30 UTC
Labels: stage/1-reproduction
