### ISSUE TITLE
object fields order in constom plugin schema

### ISSUE THREAD

**Issue by doukai** [dotansimha/graphql-code-generator#8826] opened 2023-01-17 00:46 UTC
### Is your feature request related to a problem? Please describe.

This is my User object define:
`
type User {
    login: String
    passworld: String
    name: String
    age: Integer
}
`

but the fields order in plugin function schema parmater is:
`
type User {
    age: Integer
    login: String
    name: String
    passworld: String
}
`

The order of fields  has changed (alphabetically),
Is there any way to keep the original order?
thanks~

### Describe the solution you'd like
`
type User {
    login: String
    passworld: String
    name: String
    age: Integer
}
`

**Comment by saihaj** [comment] 2023-01-17 18:08
what is the use case for this?

**Comment by saihaj** [comment] 2023-01-17 18:54
duplicate of https://github.com/dotansimha/graphql-code-generator/discussions/8823. Let's first finalize discussion there and then create an issue

**Closed by saihaj** 2023-01-17 18:54 UTC
Labels: waiting-for-answer
