### ISSUE TITLE
More specific error messages when a problem is encountered with the configuration.

### ISSUE THREAD

**Issue by Mossop** [dotansimha/graphql-code-generator#6355] opened 2021-07-22 07:50 UTC
**Is your feature request related to a problem? Please describe.**

I have a quite large `codegen.js` file and just made a number of changes to it and clearly got something wrong. When I run `graphql-codegen` though it simply prints:
```
Invalid "generates" config!
Invalid "generates" config!
```
This doesn't give me a lot to go on for tracking down the issue.

**Describe the solution you'd like**

I would like it if the error message printed could be a bit more specific about what was actually invalid about the config.

**Describe alternatives you've considered**

I checked that I can load the config as a node module so there is no syntax error. I looked for a verbose command line argument and found none.

**Comment by Mossop** [comment] 2021-07-22 08:11
Another good example:
```
$ graphql-codegen
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Failed to load schema
Something went wrong
```

**Comment by dotansimha** [comment] 2021-08-03 12:11
Hi @Mossop , can you please share a reproduction of that issue? You can also try to set `DEBUG=1 VERBOSE=1` in your env, and you'll get more details.

**Comment by aboveyunhai** [comment] 2021-08-12 01:07
@Mossop  I just found one. 
![image](https://user-images.githubusercontent.com/35160613/129122714-2fd309e9-b16d-4ec5-a646-7580198482ae.png)
![image](https://user-images.githubusercontent.com/35160613/129122725-4c01a9af-b36f-4b77-a630-f6c206b2ce05.png)

The problem is because I did not capitalize the `type`
![image](https://user-images.githubusercontent.com/35160613/129122796-199f3380-ca29-43bd-906f-c672f66febe2.png)

Sometimes it's just really hard to realized the issue.

**Comment by ardatan** [comment] 2021-08-12 17:45
Fixed in `@graphql-tools/utils` with this commit;
https://github.com/ardatan/graphql-tools/commit/b968463124cd2e397852d4e57ebe36acf3602462

It'll be available soon in GraphQL Codegen cc @dotansimha

**Comment by n1ru4l** [comment] 2021-08-20 05:44
The fic has been published 😇

**Closed by n1ru4l** 2021-08-20 05:44 UTC
Labels: stage/0-issue-prerequisites
