### ISSUE TITLE
Can't return `null` from nullable filed resolver

### ISSUE THREAD

**Issue by kamilchm** [dotansimha/graphql-code-generator#3174] opened 2019-12-27 14:34 UTC
**To Reproduce**

1. My GraphQL schema:

```graphql
type Query {
  optional: Result
}
type Result {
  mandatory: String!
}
```

2. My GraphQL operations:

```typescript
const resolvers: Resolvers = {
  Query: {
    optional: () => Promise.resolve("x").then(r => (r ? {} : null))
  }
};
```

**Expected behavior**
`null` is a valid result type, but I get:
```
src/resolvers.ts(4,3): error TS2322: Type '{ optional: () => Promise<Result | Promise<Result> | {} | null>; }' is not assignable to type 'QueryResolvers<MyContext, {}>'.
      Types of property 'optional' are incompatible.
        Type '() => Promise<Result | Promise<Result> | {} | null>' is not assignable to type 'ResolverFn<Maybe<ResolverTypeWrapper<Result>>, {}, MyContext, {}> | StitchingResolver<Maybe<ResolverTypeWrapper<Result>>, {}, MyContext, {}> | undefined'.
          Type '() => Promise<Result | Promise<Result> | {} | null>' is not assignable to type 'ResolverFn<Maybe<ResolverTypeWrapper<Result>>, {}, MyContext, {}>'.
            Type 'Promise<Result | Promise<Result> | {} | null>' is not assignable to type 'Result | Promise<Result> | Promise<Maybe<ResolverTypeWrapper<Result>>> | null'.
              Type 'Promise<Result | Promise<Result> | {} | null>' is not assignable to type 'Promise<Result>'.
                Type 'Result | Promise<Result> | {} | null' is not assignable to type 'Result'.
                  Type 'null' is not assignable to type 'Result'.
```

**Environment:**

- OS: Linux
- `@graphql-codegen/...`:  1.9.1
- NodeJS: 12

**Comment by dotansimha** [comment] 2019-12-31 11:14
@kamilkisiela can you please take a look?

**Comment by kamilchm** [comment] 2019-12-31 12:31
To be fair, I don't know if it a valid issue here. The produced error comes from TS compiler. In encountered it on a pretty big schema with complex types (tens of fields) and it wasn't easy to spot the real error.
I wonder if there is a place for improvement for generated types, to make compile errors more direct, like it was before introducing `ResolverTypeWrapper`.

**Comment by dotansimha** [comment] 2020-01-28 08:16
@kamilchm I'm closing for now. If you have an idea for improvement feel free to share with us :)

**Closed by dotansimha** 2020-01-28 08:16 UTC
Labels: enhancement, templates

**Comment by andrerpena** [comment] 2020-02-15 22:47
I think this issue should be reopened. Currently,  as @kamilchm stated, you cannot return `Promise<undefined>` to a resolver of a nullable type.

**Comment by freshollie** [comment] 2020-02-15 23:06
@dotansimha @kamilchm This issue is related to the way `Maybe` wraps the `ResolverType`, instead of the `ResolverTypeWapper` wrapping the Maybe:

Example: 

Schema:
```graphql
type Query {
  getDraft(id: ID!): Draft,
}
```

Generated code

```typescript
export type Maybe<T> = T | null;

export type ResolversTypes = {
  Draft: ResolverTypeWrapper<Draft>,
  ...
}
export type QueryResolvers<...> = {
  getDraft?: Resolver<Maybe<ResolversTypes['Draft']>, ParentType, ContextType, RequireFields<QueryGetDraftArgs, 'id'>>
}
```

This causes `Maybe` to wrap `Promise<Draft> | Draft` and wrongly make the type  `Promise<Draft> | Draft | null`

I think the generated code should instead be 

```typescript
export type ResolversTypes = {
  Draft: ResolverTypeWrapper<Maybe<Draft>>,
  ...
}
export type QueryResolvers<...> = {
  getDraft?: Resolver<ResolversTypes['Draft']>, ParentType, ContextType, RequireFields<QueryGetDraftArgs, 'id'>>
}
```

This would correctly resolve `getDraft` to be `Promise<Draft | null> |  Draft | null`

This obviously doesn't work here. As it would mean `Draft` would always be a maybe, but you can see the real issue in the types generated here right? This has nothing to do with the typescript compiler but the way `Maybe` is used.

For us right now, the only solution is to resolve the promise before returning the value, but it's a workaround which doesn't seem like it needs to exist.

**Comment by freshollie** [comment] 2020-02-16 08:52
Another solution to this could be to change Maybe to better extend Promise types: 

```typescript
export type Maybe<T> = T extends PromiseLike<infer U> ? Promise<U | null> : T | null;
```

**Comment by wallzero** [comment] 2020-03-05 19:13
@dotansimha I think this should be left open. Promises should be able to return null in case of issue.

@freshollie could you share how you are resolving the promise as a work around? I am trying to figure out a solution while keeping type safety.

**Comment by freshollie** [comment] 2020-03-05 19:15
@wallzero Added my solution as the Maybe value fixes this issue.

```ymal
    plugins:
      - typescript
      - typescript-resolvers
    config:
      ....
      scalars:
        StringOrInt: string | number
        Date: Date
      contextType: ../context#Context
      maybeValue: 'T extends PromiseLike<infer U> ? Promise<U | null> : T | null'
```

**Comment by lecstor** [comment] 2020-06-10 22:46
> maybeValue: 'T extends PromiseLike<infer U> ? Promise<U | null> : T | null'
So this didn't fix the issue I was having, but it did make it obvious where the issue was which I was unable to decipher before that.
After I fixed the issue I was able to remove it again.

**Comment by magicmark** [comment] 2020-09-03 09:57
Hmm, I'm also running into this issue.

It's not super clear how to resolve this. (`maybeValue: 'T extends PromiseLike<infer U> ? Promise<U | null> : T | null'` did not work for me, I still get the same stack trace)

**Comment by dotansimha** [comment] 2020-09-29 08:22
@magicmark @lecstor if it's still relevant, can please open a new issue?

**Comment by jardakotesovec** [comment] 2020-12-22 17:35
@dotansimha Sorry to be pain - but just run into this as well. Its clearly still issue - why this can't be reopened since it has all the details it needs?

**Comment by dotansimha** [comment] 2021-01-21 12:53
@jardakotesovec There are several workarounds for this, for me, in most cases, just using the default configuration with `async` function works and I can safely return `null`s. Do you have a reproduction for this?

**Comment by kirschem** [comment] 2021-03-29 11:51
For me, that problem was a different one, however the error message is very misleading.
I also got the error `null is not assignable to type XXX`. It turned out, that returning `null` was not the problem. The actual type that I returned from the resolver did not match the expected type for one property.
=> Make sure the object you return matches the expected return type of the resolver.

**Comment by henrymgarrett** [comment] 2021-11-23 17:03
> For me, the problem was a different one, however the error message is very misleading.
I also got the error null is not assignable to type XXX. It turned out, that returning null was not the problem. The actual type that I returned from the resolver did not match the expected type for one property.
=> Make sure the object you return matches the expected return type of the resolver.

I ran into this issue too and thought it was a problem with the generated types, but like @kirschem , the issue was with my returned internal type not matching the graphql type exactly.

**Comment by Strato** [comment] 2022-04-06 13:33
I had this very problem today and was going to use @freshollie [solution](https://github.com/dotansimha/graphql-code-generator/issues/3174#issuecomment-595398571) until I found that I also had a mismatch between my generated type and my returned internal type.

So if you stumble upon this issue, look twice if your types are matching before blaming `Maybe<>`.

Updating all my `@graphql-codegen` packages and re-generating my API types helped TypeScript to show the real problem.

**Comment by freshollie** [comment] 2022-04-06 15:36
@Strato 100% correct, I’ve also noticed this years later. However I did find that using the maybe type did help make the typescript error easier to understand and helped me solve my problem

**Comment by RemyMachado** [comment] 2022-05-12 19:09
I had a similar problem. I couldn't return undefined from my resolvers, even if apollo-server (I think it's him) is replacing undefined values with null.
I ended up adding `maybeValue: "T | null | undefined"` to the config.
