### ISSUE TITLE
Add some way to tell which source file contains the syntax error.

### ISSUE THREAD

**Issue by brandonbloom** [dotansimha/graphql-code-generator#2776] opened 2019-10-16 20:17 UTC
Look at this output:

```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./services/apollo/fragments.generated.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unexpected token (35:0)
        Generate
    ❯ Generate ./services/apollo/hooks.generated.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unexpected token (35:0)
        Generate


 Found 2 errors

  ✖ ./services/apollo/fragments.generated.ts
    SyntaxError: Unexpected token (35:0)

  ✖ ./services/apollo/hooks.generated.ts
    SyntaxError: Unexpected token (35:0)
```

Which source file has the syntax error? There is no way to tell!

**Describe the solution you'd like**

```
 Found 2 errors

  ✖ ./services/apollo/fragments.generated.ts
    Error loading GraphQL documents from "./foo/bar.tsx": SyntaxError: Unexpected token (35:0)

  ✖ ./services/apollo/hooks.generated.ts
    Error loading GraphQL documents from "./foo/bar.tsx": SyntaxError: Unexpected token (35:0)
```

**Comment by dotansimha** [comment] 2019-10-22 06:01
@brandonbloom which version of the codegen and graphql do you use?

**Comment by dotansimha** [comment] 2019-11-03 07:11
Closing, @brandonbloom feel free to contact if it's still relevant.

**Closed by dotansimha** 2019-11-03 07:11 UTC
Labels: waiting-for-answer

**Comment by captaincole** [comment] 2019-12-24 05:17
@dotansimha I have reproduced this issue with codegen v1.9 and graphql v14.5.8

```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unexpected token (57:30)
        Generate
    ❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unexpected token (57:30)
        Generate


 Found 2 errors

  ✖ src/generated/graphql.tsx
    SyntaxError: Unexpected token (57:30)

```

There is a stack trace, but it is wholly unusable as far as I can tell... 

```
at Object.parseConditional (/Users/andrew/misfit/MisfitAthletics2/node_modules/@graphql-toolkit
/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:9043:30)```

**Comment by ardatan** [comment] 2019-12-24 05:20
@captaincole Could you please create a reproduction in a repo or codesandbox?

**Comment by captaincole** [comment] 2019-12-24 06:03
Trying too, I've found the culprit in my code finally after many guess and checks.

```
  commentList = (comments: TcmCommentsQueryResult['data']) => {
    return comments?.deepComments.map((comment: any) => {
      return (
        comment && (
          <Fragment>
            <CommentComponent key={comment?.comment_ID} comment={comment!} />
            {comment?.children &&
              comment.children.map((child: any) => {
                return (
                  <CommentComponent
                    isChild={true}
                    key={child!.comment_ID}
                    comment={child}
                  />
                );
              })}
          </Fragment>
        )
      );
    });
  };
```

I will update when I figure out what the issue is with this code...

**Comment by captaincole** [comment] 2019-12-24 06:05
@ardatan 
Update: Figured it out. Turns out the underlying issue is option chaining in TS 3.7

Example. The code above did not generate correctly, but this did...

```
  commentList = (comments: TcmCommentsQueryResult['data']) => {
    return comments!.deepComments.map((comment: any) => {
      return (
        comment && (
          <Fragment>
            <CommentComponent key={comment!.comment_ID} comment={comment!} />
            {comment!.children &&
              comment.children.map((child: any) => {
                return (
                  <CommentComponent
                    isChild={true}
                    key={child!.comment_ID}
                    comment={child}
                  />
                );
              })}
          </Fragment>
        )
      );
    });
  };
```

All that is changed is that there is no option chaingin here (only !)

**Comment by bkniffler** [comment] 2020-02-15 16:03
This is still an issue. I'm on the latest version and I'm not getting any clues about where the issue is. Using optional chaining excessively. Shouldn't this be open? The answers I can see in this thread all refer to solving the underlying problems, not to the actual fact that graphql codegen will not always show what files causes issues and that, if that happens, it is a big pain to find the issue.

**Comment by dotansimha** [comment] 2020-03-08 15:26
@bkniffler It seems like there are multiple causes for this issue. If it's still happens, can you please share a reproduction?

**Comment by bkniffler** [comment] 2020-03-08 22:12
Its not been happening to me for some time, just tried to add a mistake on purpose and I got useful info ("unexpected name xy" + file that contains the error GraphQL code).

**Comment by captaincole** [comment] 2020-03-23 03:52
+1 My earlier issue was incredibly difficult to diagnose because I had no reference. I had to go backwards through each commit and figure out the culprit.

**Comment by ardatan** [comment] 2020-03-23 04:06
@captaincole If you still have the issue, please share a reproduction. Thanks!

**Comment by captaincole** [comment] 2020-03-23 04:35
Man it would be tough, because the issue is in my personal project. 

I know it makes your life way easier when there is a repro case, so hopefully I can help out.
