### ISSUE TITLE
ExperimentalWarning since upgrade to >=1.8.0

### ISSUE THREAD

**Issue by levrik** [dotansimha/graphql-code-generator#2701] opened 2019-10-07 13:41 UTC
**Describe the bug**

Since upgrading to >=1.8.0 of `@graphql-codegen/cli`, `@graphql-codegen/typescript-operations` and `@graphql-codegen/typescript-react-apollo`, I'm getting this warning displayed: `(node:73362) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time`

I'm using the latest Node LTS (v10.16.3) and the following configuration:

```yaml
schema: schema.graphql
documents: src/queries/**/*.graphql
generates:
  src/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      scalars:
        Upload: File
      declarationKind: interface
      noGraphQLTag: true
      withHOC: false
      withComponent: false
      withHooks: true
      skipTypename: true
```

**Expected behavior**

I wouldn't expect warnings for experimental features popping up. Maybe the feature is stable in latest Node (v12.x) but I would expect a package to work without problems and warnings also on the latest Node LTS.

**Comment by dotansimha** [comment] 2019-10-13 08:29
I can confirm that it happens only with Node 10. With 12 it doesn't show it. 
I'm not sure what piece of our codebase causing it, because we are not really using `asyncIterator` feature. 

@kamilkisiela @ardatan any idea?

**Comment by ardatan** [comment] 2019-10-14 17:18
@dotansimha It's related to `for await`. So transpilation would fix that as well.
https://github.com/ardatan/graphql-toolkit/issues/259

**Comment by dotansimha** [comment] 2019-10-15 05:47
Should be fixed in `graphql-toolkit@v0.5.17`

**Comment by n1ru4l** [comment] 2019-10-15 06:47
@dotansimha Are you sure?

```
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "graphql-toolkit"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "graphql@14.4.2" is incompatible with requested version "graphql@^0.7.0"
warning Resolution field "graphql-toolkit@0.5.17" is incompatible with requested version "graphql-toolkit@0.5.16"
warning Resolution field "react@16.9.0" is incompatible with requested version "react@16.10.2"
warning Resolution field "react-dom@16.9.0" is incompatible with requested version "react-dom@16.10.2"
warning Resolution field "graphql@14.4.2" is incompatible with requested version "graphql@^14.5.3"
warning Resolution field "graphql@14.4.2" is incompatible with requested version "graphql@^14.5.3"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "graphql-toolkit@0.5.17"
info Reasons this module exists
   - "_project_#@graphql-codegen#cli" depends on it
   - Hoisted from "_project_#@graphql-codegen#cli#graphql-toolkit"
   - Hoisted from "_project_#@graphql-inspector#cli#@graphql-inspector#load#graphql-toolkit"
   - Hoisted from "_project_#@graphql-codegen#cli#@graphql-codegen#core#graphql-toolkit"
info Disk size without dependencies: "6.22MB"
info Disk size with unique dependencies: "14.78MB"
info Disk size with transitive dependencies: "23.59MB"
info Number of shared dependencies: 78
✨  Done in 1.42s.
```

```
yarn run v1.17.3
$ gql-gen --config codegen.yml
(node:4853) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
  ✔ Parse configuration
  ✔ Generate outputs
✨  Done in 1.41s.
```

**Comment by dotansimha** [comment] 2019-10-15 07:52
@ardatan ^

**Comment by ardatan** [comment] 2019-10-15 16:39
@dotansimha I don't use old version of Node. Someone said targetting `es2017` works then we changed it to that in here
https://github.com/ardatan/graphql-toolkit/blob/master/tsconfig.json
And we released the new version. See here people says it is working on the versions `for await` isn't even supported :) Are you sure you have correct setup?
https://github.com/ardatan/graphql-toolkit/issues/259

**Comment by n1ru4l** [comment] 2019-10-16 06:12
>  I don't use old version of Node

I certainly do not think that the version that is recommended on the Node.js website is an old version 😅


```
laurin@scoop:/somewhere$ node  --trace-warnings node_modules/.bin/graphql-codegen --config codegen.yml
(node:9559) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (internal/util.js:160:11)
    at UniqueStream.Readable.(anonymous function) (_stream_readable.js:1043:3)
    at Object.__asyncValues (/somewhere/node_modules/tslib/tslib.js:202:22)
    at Object.loadTypedefs (/somewhere/node_modules/graphql-toolkit/dist/commonjs/loaders/load-typedefs.js:112:35)
    at Object.loadDocuments (/somewhere/cyanite-app/node_modules/graphql-toolkit/dist/commonjs/loaders/documents.js:10:34)
    at Object.exports.loadDocuments (/somewhere/cyanite-app/node_modules/@graphql-codegen/cli/dist/commonjs/load.js:129:59)
    at Listr.task.wrapTask (/somewhere/cyanite-app/node_modules/@graphql-codegen/cli/dist/commonjs/codegen.js:160:68)
    at Promise.resolve.then (/somewhere/cyanite-app/node_modules/@graphql-codegen/cli/dist/commonjs/codegen.js:18:52)
  ✔ Parse configuration
  ✔ Generate outputs
laurin@scoop:/somewhere$ cat node_modules/graphql-toolkit/package.json 
{
  "name": "graphql-toolkit",
  "version": "0.5.17",
 [......]
```

**Comment by dotansimha** [comment] 2019-10-23 16:24
@ardatan can you please make sure it's fixed?

**Comment by ardatan** [comment] 2019-10-23 20:31
@dotansimha We don't use asyncc interators anymore. So this warning supposed to be gone.

**Comment by n1ru4l** [comment] 2019-10-23 20:52
I updated to 12 on Monday 😎 It is not LTS, however 10 is still in maintenance mode for another half year.

**Closed** 2019-10-29 09:06 UTC
Labels: bug, core, waiting-for-release
