### ISSUE TITLE
    Unable to find template plugin matching 'typescript-resolvers'   

### ISSUE THREAD

**Issue by EthanSK** [dotansimha/graphql-code-generator#4272] opened 2020-06-22 18:25 UTC
Unable to find template plugin matching 'typescript-resolvers'
    Install one of the following packages:

Literally do the setup wizard with npm in a blank slate project. Yes I installed the npm modules. I've seen lots of other issues about this same thing, and none helped.

**Comment by dotansimha** [comment] 2020-06-25 07:16
@EthanSK We have a template for issues, which includes a codesandbox template (https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
). 
Please provide a reproduction of the issue, otherwise we won't be able to investigate and fix that.

**Comment by dotansimha** [comment] 2020-06-30 11:14
@EthanSK ?

**Comment by EthanSK** [comment] 2020-06-30 11:25
I cannot provide a meaningful repro because it is just what I said in the description, a blank slate project in a blank slate folder that is not in a monorepo. I have other lerna (monorepo) projects on my machine, and I don't know how npm works behind the scenes with global module caching, so maybe it's that? But the project i'm testing this on is definitely not in a monorepo

**Comment by dotansimha** [comment] 2020-06-30 11:31
I see, but I suggested a few things to check. Especially regarding `node_modules` structure. Try `yarn why` to see if you are able to find duplications.  Maybe do you have one of the codegen packages installed globally? 

If it's not something you can share or reproduce, I'll have to close this issue, because we won't be able to assist.

**Closed** 2020-07-06 21:21 UTC
Labels: needs reproduction
