### ISSUE TITLE
Nested object in fragment unexpectedly not optional

### ISSUE THREAD

**Issue by KieranHarper** [dotansimha/graphql-code-generator#3060] opened 2019-12-02 05:46 UTC
**Describe the bug**
I have an entity that has optional entities as fields, and this is reflected in the type generated for that entity. However if I use a fragment to query, then the type generated for the fragment loses the ? and no longer matches.

Unless I'm misunderstanding something, I would expect a fragment that fully specifies all the fields of an entity to exactly match the type generated for the field itself.

**To Reproduce**

1. My GraphQL schema:

```graphql
type Address {
  street: String!
  suburb: String!
}

type User {
  id: String!
  address: Address # <-- optional
}

type Query {
  user(id: String!): User
}

schema {
  query: Query
}
```

2. My GraphQL operations:

```graphql
fragment AddressFields on Address {
  street
  suburb
}

fragment UserFields on User {
  id
  address {
    ...AddressFields
  }
}

query getUser($id: String!) {
  user(id: $id) {
    ...UserFields
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: "schema.graphql"
documents: "operations.graphql"
generates:
  types.ts:
    - typescript
    - typescript-operations:
        preResolveTypes: true
        dedupeOperationSuffix: true
    - typescript-react-apollo:
        reactApolloVersion: 2
        withHooks: true
        withHOC: false
        withComponent: false
```

4. Minimal example that will complain because of type mismatching:
```typescript
import { User, UserFieldsFragment } from "./types";

const userMapper = (user: User): UserFieldsFragment => {
  return user;
};
```

tsc says:
```
error TS2322: Type 'User' is not assignable to type 'UserFieldsFragment'.
Property 'address' is optional in type 'User' but required in type 'UserFieldsFragment'.
```

**Expected behavior**
For `UserFieldsFragment` to declare `address` as ?

**Environment:**

- OS: MacOS Mojave
- `@graphql-codegen/...`: 1.9.1
- NodeJS: 11.13.0

**Comment by ebenoist** [comment] 2019-12-31 20:18
Running into this one as well. Any clue where the regression was? Happy to help fix this up.

**Comment by dotansimha** [comment] 2020-01-01 20:01
I think it's an issue with `preResolveTypes`, can you please try to set it to `false` and let us know if it works?

**Comment by KieranHarper** [comment] 2020-01-02 02:52
`preResolveTypes: false` has the same issue, just with a little more output
```
example.ts:4:3 - error TS2322: Type 'User' is not assignable to type '{ __typename?: "User"; } & Pick<User, "id"> & { address: { __typename?: "Address"; } & { __typename?: "Address"; } & Pick<Address, "street" | "suburb">; }'.
  Type 'User' is not assignable to type '{ address: { __typename?: "Address"; } & { __typename?: "Address"; } & Pick<Address, "street" | "suburb">; }'.
    Property 'address' is optional in type 'User' but required in type '{ address: { __typename?: "Address"; } & { __typename?: "Address"; } & Pick<Address, "street" | "suburb">; }'.

4   return user;
    ~~~~~~~~~~~~
```

**Comment by dotansimha** [comment] 2020-01-02 10:55
Ok I checked that, and it actually makes sense. 

The `type User` is being transformed into:
```
    export type User = {
       __typename?: 'User',
      id: Scalars['String'],
      address?: Maybe<Address>,
    };
```

And it represents the way the type could be structured in your API implementation. it means that it can be there, or not (marked as `?`), and it could be null as well (marked as `Maybe`). 

In GraphQL operations, if you ask for a field - it will be there - there is no such thing optional, so it might have a value, or it will be `null`. That's why the generated operation types doesn't use optionals. 

Also, trying to convert the generated TypeScript `User` into `UserFragment` might be wrong, because `User` is a representation of all fields, and `UserFragment` is only part of it (selection set). 

 
If you wish to have more "similar" types, you can set `avoidOptionals: true` and it will make sure that you generated `User` type will not use `?` to mark nullable types, and it will use only `Maybe` - which is similar to what operations are generating. But still - note that this might not work because of selection sets. You client-side implementation should use only the generated `UserFragment` only. The `User` type is there only to be a base type.

**Closed by dotansimha** 2020-01-02 10:55 UTC
