### ISSUE TITLE
react-query + customFetcher generates invalid TypeScript (`TS6133: 'RequestInit' is declared but its value is never read.`)

### ISSUE THREAD

**Issue by sampi** [dotansimha/graphql-code-generator#7444] opened 2022-01-31 15:12 UTC
**Describe the bug**
`import { RequestInit } from 'graphql-request/dist/types.dom';` is added to generated output even when using a custom fetcher. This is never used, so I'm getting the following error from `tsc`:
```
TS6133: 'RequestInit' is declared but its value is never read.
```

**To Reproduce**

Check the first line of the generated file:
https://codesandbox.io/s/romantic-mirzakhani-57us1?file=/types.ts:0-62

1. use `typescript-react-query`
2. use custom fetcher, like `func: '../fetcher#useFetchData'
3. generate code
4. try to build app

1. My GraphQL schema:

no schema, this is a compile-time error

2. My GraphQL operations:

no operations, this is a compile-time error

3. My `codegen.yml` config file:

```yml
schema:
  - ${REACT_APP_GRAPHQL_ENDPOINT}
documents:
  - './src/**/*.graphql'
overwrite: true
generates:
  src/gql/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        func: '../fetcher#useFetchData'
        isReactHook: true
        exposeQueryKeys: true
```

**Expected behavior**

**Environment:**

- OS: macOS `12.2` on Apple Silicon
  - `@graphql-codegen/cli`: `2.4.0`
  - `@graphql-codegen/introspection`: `2.1.1`
  - `@graphql-codegen/typescript`: `2.4.2`
  - `@graphql-codegen/typescript-operations`: `2.2.3`
  - `@graphql-codegen/typescript-react-query`: `3.5.0`
- NodeJS: `14.18.3`
- Typescript: `4.5.5`

**Additional context**

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "sourceMap": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "downlevelIteration": true
  },
  "include": ["src", "types"]
}

```

**Comment by sampi** [comment] 2022-01-31 15:17
I figured out that I can make a codesandbox for this, don't close the issue yet, I'll update the description in a few minutes when it's ready.

**Comment by ristomatti** [comment] 2022-02-01 02:51
Just ran into this after upgrading @graphql-codegen/typescript-react-query to version 3.5.0. Version 3.4.0 does not include the `options?: RequestInit['headers']` type. I don't think we'll need to pass options, so reverting back fixed the issue for now.

Side note - the type seems to be almost the same as in standard `lib.dom.d.ts`. Only the order of the types varies.

In `graphql-request/dist/types.dom.d.ts`:

```ts
declare type HeadersInit = Headers | string[][] | Record<string, string>;
```
In `typescript/lib/lib.dom.d.ts`:

```ts
type HeadersInit = string[][] | Record<string, string> | Headers;
```

**Comment by charlypoly** [comment] 2022-02-04 15:07
Hi @sampi!

Thank you for your complete bug report!

A fix is on the way: https://github.com/dotansimha/graphql-code-generator/pull/7474 ⚡ 

I'll keep you updated here.

**Comment by sampi** [comment] 2022-02-07 10:15
`@graphql-codegen/typescript-react-query@3.5.2-alpha-d4ba9b078.0` seems to have fixed it, thank you!

**Comment by dominikx96** [comment] 2022-02-07 15:55
Is there any option to pass custom headers in the generated hook?

**Comment by charlypoly** [comment] 2022-02-08 08:53
> Is there any option to pass custom headers in the generated hook?

if you have a custom fetcher, it would be possible yes

➡️ https://www.graphql-code-generator.com/plugins/typescript-react-query#using-custom-fetcher

**Comment by charlypoly** [comment] 2022-02-09 15:32
This issue is fixed in `@graphql-codegen/typescript-react-query@3.5.2`

**Comment by ristomatti** [comment] 2022-02-10 00:57
@charlypoly I've configured a custom fetcher but `RequestInit` is still imported from`graphql-request` as [I mentioned](https://github.com/dotansimha/graphql-code-generator/issues/7444#issuecomment-1026427495) above:

```ts
import { RequestInit } from 'graphql-request/dist/types.dom';
```

Since `typescript/lib/lib.dom.d.ts` provides basically the same type. If I remove the import it makes no difference as it's then picked up from TypeScript's default types.

I understand this is technically a different issue, should I report this separately? This causes a TS compilation failure as the custom fetcher does not import `RequestInit` from `graphql-request` as Axios is used, hence the custom fetcher.

**Comment by ristomatti** [comment] 2022-02-14 09:23
@charlypoly Any estimate when the next npm release will be? I just happen to be finalising my PR which sets up graphql-codegen. I'm just thinking if I should wait a bit to get the fix included, no tthat there's any hurry as such.

**Comment by ardatan** [comment] 2022-02-14 09:24
You can use the alpha version here until we release it;
https://github.com/dotansimha/graphql-code-generator/pull/7508#issuecomment-1034956025

**Comment by ristomatti** [comment] 2022-02-14 09:25
Ah, I didn't spot that, thanks! I'll test it right away so I can confirm if it's fixed. :+1:

**Comment by charlypoly** [comment] 2022-02-14 10:10
@ristomatti it is now available in `@graphql-codegen/typescript-react-query@3.5.3` 📦

**Closed by charlypoly** 2022-02-14 10:10 UTC

**Comment by ristomatti** [comment] 2022-02-14 12:54
Thanks! For the record: I can confirm it fixed.

**Comment by makinde** [comment] 2022-10-04 20:11
> > Is there any option to pass custom headers in the generated hook?
> 
> @dominikx96 if you have a custom fetcher, it would be possible yes
> 
> ➡️ https://www.graphql-code-generator.com/plugins/typescript-react-query#using-custom-fetcher

FWIW, I don't believe this currently works. mutation hooks are generated by only passing one param to the custom fetcher in v3.6.2. My code example from my generate file below:

```ts
export const useCreateConnectedUser = <
      TError = unknown,
      TContext = unknown
    >(options?: UseMutationOptions<CreateConnectedUser, TError, CreateConnectedUserVariables, TContext>) =>
    useMutation<CreateConnectedUser, TError, CreateConnectedUserVariables, TContext>(
      ['CreateConnectedUser'],
      useFetchData<CreateConnectedUser, CreateConnectedUserVariables>(CreateConnectedUserDocument),
      options
    );
```

**Comment by makinde** [comment] 2022-10-04 20:16
@charlypoly https://github.com/dotansimha/graphql-code-generator/issues/7444#issuecomment-1267523373

**Comment by charlypoly** [comment] 2022-10-12 09:28
> FWIW, I don't believe this currently works. mutation hooks are generated by only passing one param to the custom fetcher in v3.6.2. My code example from my generate file below:

Hi @makinde,

You are right, the `headers` argument is only preset if `graphql-request` is selected as `fetcher` option.
Each `fetcher` configuration leads to different hooks signature, which is not ideal.
This comes from fixing specific use cases over time, with not standarization.

For this reason, we now recommend to avoid using the generated hooks approach in favor if the new `preset: 'client'`, as showcased here: https://www.the-guild.dev/graphql/codegen/docs/guides/react-vue#installation

**Comment by makinde** [comment] 2022-10-12 14:15
Thanks for the reply, @charlypoly . Interesting, I hadn't seen this new preset method. One first glance it looks a lot more verbose than the generated hooks :( Perhaps I'll get used to it. I'll look for blog posts explaining the change. For now will probably shift over to `graphql-quest` to not have to refactor my codebase.
