### ISSUE TITLE
Can we make flow resolver plugin support es6 classes?

### ISSUE THREAD

**Issue by gyDBD** [dotansimha/graphql-code-generator#4623] opened 2020-08-25 00:39 UTC
graphql-js documents that we can use ES6 classes to represent GraphQL types and add resolver methods on.
https://graphql.org/graphql-js/object-types/
Our resolvers are something like this:  (example taken from the docs linked above)
```
// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type RandomDie {
    numSides: Int!
    rollOnce: Int!
    roll(numRolls: Int!): [Int]
  }

  type Query {
    getDie(numSides: Int): RandomDie
  }
`);

// This class implements the RandomDie GraphQL type
class RandomDie {
  constructor(numSides) {
    this.numSides = numSides;
  }

  rollOnce() {
    return 1 + Math.floor(Math.random() * this.numSides);
  }

  roll({numRolls}) {
    var output = [];
    for (var i = 0; i < numRolls; i++) {
      output.push(this.rollOnce());
    }
    return output;
  }
}

// The root provides the top-level API endpoints
var root = {
  getDie: function ({numSides}) {
    return new RandomDie(numSides || 6);
  }
}
```
And we tried to use `graphql-codegen` to auto generated flow type for our resolvers. 
Here's the codegen.yml looks like:
```
overwrite: true
schema: "schema.graphql"
documents: null
generates:
    src/generated/types.js:
        plugins:
            - "flow"
            - "flow-resolvers"
        config:
            contextType: Context
```
However the auto generated flow type only works for object literal, cannot apply those types to es6 classes. To flow type a es6 classes, we need interface instead and make the es6 classes implements it.  see a small demo [here](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKBjAhgGy1AZzgF44BvAHwCg44BJAEQC44CYoBLAOwHMAaGunbceLNp14DaAIQgQcwLFxYAjOQqVT6XGCy4BXALYrgULQDEcELLrgHjpgRQC+AbiqhIsBMlQAlYAJ5ADdTABVfAHUoLDAUKAAeMIA+EjgABSgIQw4CYCTUijgw9wB6ACpyuABZWLAROBMYAHdgYC44XBxO4KwOPBUFVgwAC2BDLB8UIiUAEwQxuChAkNMiJGm4ctKPcGh4Df8VnFDCCM3SMkEARX1TRBYAoJPwqJi40wSyZ2StNGFeI9jqdzsBonVPgASACiCkM7RgoISmFw+AIfDgAHJ-hIeJjkr9BIwgc8QW8IYkYXCEUiUXhCBjMYx8YTaABVMBWLCzEmrKCg8EfSmw8Y03zI7D09FYjlc2YsrSyeSKZRwJ58gXveIJKminS0yVoxlKjRcBVUNxUKgVKq1OINJqtdqdHDdLC9fpYQaoAijcaTQ4zLjzGCLZaktZwMD4BFEba7LwHXxq4FrdIx-W+IiXG53KAPcjOP4A0RwXXwzMoCWohlYnEifFaAAy3AA1iwW1xW1piWWRRXEeK6UasczWXBZdYeX3qZX8sPa5jJ9zG4ITSqWOWxVWF9LMeulKvLVRDnAMBg0pCAtyAPJcHCIL7UWi0DjTgD84hETh+7gT+ymI4I0SJ59BwGAMXTZYdDSb4MQAYQgHRQHgUhzwxABBKAeGzQtUlIAAKa1SloaNoNsKCES0fAcJYLCcK0DAkJgFCWEQ5CQAgqgAEoSFSTJslyfJQPAwoUwIMCYD-TwANPTtW1g584AAfWUw4uCweF3xYTF5MxLQ303ftt3nQ1FzHLRZkCDBODAGAOCQozZ0HHczL3eteFXWh9CgHAnL1FzTJrdyS1XFw-1KEiJgMLpEDPEYlB4VAuiWVNCDgAAzLJDEAhAIE6DpuBYqAMqwDBgGIuAZO8OS23VF5CASdiWM40E0iURBIIzQLL2MucEnq04CEouc9z0glYKoIrTFK8q4Hkwa1ia5iULa0gOq68i1pnAKkUWwgRsCsa2xZchBAAais31bPspDtPEvkdT6wKBrSghQRC3FGwybrQQQlbWt8QljwwPACCIaQOAALzZPIoDgDhDE5AKiAWt6EmSK5aCumyODshyuAImiCBYDazwB3Rz24rGX2WGAfI6AAiDKWcZ9xaGcC0qCAA)
Do you think we can make the  flow resolver plugin generate interfaces instead of types so that it supports resolvers that are written with es6 classes? Any suggestions will be helpful here, thanks!!

**Comment by gyDBD** [comment] 2020-08-25 05:12
I can work on it and submit a PR to support this if that's okay.

**Comment by dotansimha** [comment] 2020-08-25 06:13
Hi @gyDBD ! 
PRs are always welcome. 

In that specific use case- can you please share a reproduction of that? I didn't fully understand the limitation of Flow. Is it because we are using `type` instead of `interface`?

**Comment by gyDBD** [comment] 2020-08-25 16:49
Thanks for the reply, here's the doc about how to flow type a class, and I made two small demo: see [Try Flow](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKBjAhgGy1AZzgF44BvAHwCg44BJAEQC44CYoBLAOwHMAaGunbceLNp14DaAIQgQcwLFxYAjOQqVT6XGCy4BXALYrgULQDEcELLrgHjpgRQC+AbiqhIsBMlQAlYAJ5ADdTABVfAHUoLDAUKAAeMIA+EjgABSgIQw4CYCTUijgw9wB6ACpyuABZWLAROBMYAHdgYC44XBxO4KwOPBUFVgwAC2BDLB8UIiUAEwQxuChAkNMiJGm4ctKPcGh4Df8VnFDCCM3SMkEARX1TRBYAoJPwqJi40wSyZ2StNGFeI9jqdzsBonVPgASACiCkM7RgoISmFw+AIfDgAHJ-hIeJjkr9BIwgc8QW8IYkYXCEUiUXhCBjMYx8YTaABVMBWLCzEmrKCg8EfSmw8Y03zI7D09FYjlc2YsrSyeSKZRwJ58gXveIJKminS0yVoxlKjRcBVUNxUKgVKq1OINJqtdqdHDdLC9fpYQaoAijcaTQ4zLjzGCLZaktZwMD4BFEba7LwHXxq4FrdIx-W+IiXG53KAPcjOP4A0RwXXwzMoCWohlYnEifFaAAy3AA1iwW1xW1piWWRRXEeK6UasczWXBZdYeX3qZX8sPa5jJ9zG4ITSqWOWxVWF9LMeulKvLVRDnAMBg0pCAtyAPJcHCIL7UWi0DjTgD84hETh+7gT+ymI4I0SJ59BwGAMXTZYdDSb4MQAYQgHRQHgUhzwxABBKAeGzQtUlIAAKa1SloaNoNsKCES0fAcJYLCcK0DAkJgFCWEQ5CQAgqgAEoSFSTJslyfJQPAwoUwIMCYD-TwANPTtW1g584AAfWUw4uCweF3xYTF5MxLQ303ftt3nQ1FzHLRZkCDBODAGAOCQozZ0HHczL3eteFXWh9CgHAnL1FzTJrdyS1XFw-1KEiJgMLpEDPEYlB4VAuiWVNCDgAAzLJDEAhAIE6DpuBYqAMqwDBgH-bw5LbdUXkIBJ2JYzjQTSJREEgjNAsvYy5wSWrTgISi5z3PSCVgwQrN9Wz7KQ7TxL5HUesCvq0oIUEQtxRsMk60EEOYlDQUJY8MDwAgiGkDgAC82TyKA4A4QxOQCoh5P6tYEmSK5aEmmyODshyuAImiCBYNqMSYjjdHPbivpfZYYB8joACIMtRpH3FoZwLSoIA) vs [Try Flow ](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKBjAhgGy1AZzgF44BvAHwCg44BJAEQC44CYoBLAOwHMAaGunbceLNp14DaAIQgQcwLFxYAjOQqVT6XGCy4BXALYrgULQDEcELLrgHjpgRQC+AbiqhIsBMlQAlYAJ5ADdTABVfAHUoLDAUKAAeMIA+EjgABSgIQw4CYCTUijgw9wB6ACpyuABZWLAROBMYAHdgYC44XBxO4KwOPBUFVgwAC2BDLB8UIiUAEwQxuChAkNMiJGm4ctKPcGh4Df8VnFDCCM3SMkEARX1TRBYAoJPwqJi40wSyZ2StNGFeI9jqdzsBonVPgASACiCkM7RgoISmFw+AIfDgAHJ-hIeJjkr9BIwgc8QW8IYkYXCEUiUXhCBjMYx8YTaABVMBWLCzEmrKCg8EfSmw8Y03zI7D09FYjlc2YsrSyeSKZRwJ58gXveIJKminS0yVoxlKjRcBVUNxUKgVKq1OINJqtdqdHDdLC9fpYQaoAijcaTQ4zLjzGCLZaktZwMD4BFEba7LwHXxq4FrdIx-W+IiXG53KAPcjOP4A0RwXXwzMoCWohlYnEifFaAAy3AA1iwW1xW1piWWRRXEeK6UasczWXBZdYeX3qZX8sPa5jJ9zG4ITSqWOWxVWF9LMeulKvLVRDnAMBg0pCAtyAPJcHCIL7UWi0DjTgD84hETh+7gT+ymI4I0SJ59BwGAMXTZYdDSb4MQAYQgHRQHgUhzwxABBKAeGzQtUlIAAKa1SloaNoNsKCES0fAcJYLCcK0DAkJgFCWEQ5CQAgqgAEoSFSTJslyfJQPAwoUwIMCYD-TwANPTtW1g584AAfWUw4uCweF3xYTF5MxLQ303ftt3nQ1FzHLRZkCDBODAGAOCQozZ0HHczL3eteFXWh9CgHAnL1FzTJrdyS1XFw-1KEiJgMLpEDPEYlB4VAuiWVNCDgAAzLJDEAhAIE6DpuBYqAMqwDBgGIuAZO8OS23VF5CASdiWM40E0iURBIIzQLL2MucEnq04CEouc9z0glYKoIrTFK8q4Hkwa1ia5iULa0gOq68i1pnAKkUWwgRsCsa2xZchBAAais31bPspDtPEvkdT6wKBrSghQRC3FGwybrQQQlbWt8QljwwPACCIaQOAALzZPIoDgDhDE5AKiAWt6EmSK5aCumyODshyuAImiCBYDazwB3Rz24rGX2WGAfI6AAiDKWcZ9xaGcC0qCAA) (If you would like to reproduce the whole thing yourself, you could use the code I copied and pasted from https://graphql.org/graphql-js/object-types/. And use my `codegem.yml`.) 
Currently, we don't have `declarationKind` config for flow resolvers plugin. I would like to have one so that resolvers can also be `interface` not `type`.

**Comment by dotansimha** [comment] 2020-09-29 09:13
@gyDBD thank you for the PR and sorry for the late reply. 
I saw you closed the PR, so I'm closing the issue for now. Let me know if it's still relevant for you.

**Closed by dotansimha** 2020-09-29 09:13 UTC
Labels: enhancement, plugins
