### ISSUE TITLE
Cannot read property 'finish' of undefined

### ISSUE THREAD

**Issue by FedeBev** [dotansimha/graphql-code-generator#5145] opened 2020-11-29 16:34 UTC
**Describe the bug**
Code generation fails with the following error when a remote schema is specified, it works as expected when using a local schema file:
```
graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/gql-generated/operations.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ src/gql-generated/operations.ts
    Failed to load schema from http://my.server/graphql:

    Cannot read property 'finish' of undefined

    
    GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
    
    Try to use one of above options and run codegen again.
    Error: Failed to load schema
        at loadSchema (/home/me/projects/myproject/dashboard/node_modules/@graphql-codegen/cli/bin.js:453:15)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async /home/me/projects/myproject/dashboard/node_modules/@graphql-codegen/cli/bin.js:858:55
        at async Task.task (/home/me/projects/myproject/dashboard/node_modules/@graphql-codegen/cli/bin.js:711:17)
    Error: Failed to load schema
        at loadSchema (/home/me/projects/myproject/dashboard/node_modules/@graphql-codegen/cli/bin.js:453:15)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async /home/me/projects/myproject/dashboard/node_modules/@graphql-codegen/cli/bin.js:858:55
        at async Task.task (/home/me/projects/myproject/dashboard/node_modules/@graphql-codegen/cli/bin.js:711:17)
```

**To Reproduce**

1. My GraphQL schema (generated with schema-ast):

```graphql
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
type Query {
  book(id: Int!): Book
  books: [Book]
}
type Book {
  title: String
  author: String
}
type Mutation {
  authenticate(authentication: UserAuthentication!): Authentication!
}
input UserAuthentication {
  credentials: UserAuthenticationCredentials
}
input UserAuthenticationCredentials {
  username: String!
  password: String!
}
type Authentication {
  context: AuthenticationContext!
  user: User!
}
type AuthenticationContext {
  token: String!
  expireAt: String!
}
type User {
  id: String!
  firstName: String!
  lastName: String!
}
type Subscription {
  test: Book
}
```

2. My GraphQL operations:

fragments.graphql
```graphql
fragment authUser on User {
  id
  firstName
  lastName
}

fragment authContext on AuthenticationContext {
  token
  expireAt
}

fragment auth on Authentication {
  context {
    ...authContext
  }
  user {
    ...authUser
  }
}
```

mutations.graphql
```graphql
mutation authenticate($authentication: UserAuthentication!) {
    authenticate(authentication: $authentication) {
        ...auth
    }
}

mutation createUser($userData: UserCreation!) {
    createUser(userData: $userData) {
        ...auth
    }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
# schema: "schema.graphql"
schema: "http://my.server/graphql"
documents: "src/gql-documents/**/*.graphql"
hooks:
  afterAllFileWrite:
    - prettier --write
generates:
  src/gql-generated/operations.ts:
    plugins:
      - add:
          content: /* eslint-disable */
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withResultType: true

```

**Expected behavior**

**Environment:**
- OS: Ubuntu 18.04
- `@graphql-codegen/add`: "^2.0.2"
- `@graphql-codegen/cli`: "^1.19.4"
- `@graphql-codegen/typescript`: "^1.19.0"
- `@graphql-codegen/typescript-operations`: "^1.17.12"
- `@graphql-codegen/typescript-react-apollo`: "^2.2.1"
- NodeJS: v14.15.0

**Additional context**
Schema is exposed by apollo-server (2.19.0) with introspection enabled, the schema pasted above is generated with `@graphql-codegen/schema-ast: "1.18.1"`

**Comment by FedeBev** [comment] 2020-11-30 15:07
I found out the issue and it was related to the server, in some cases there was an undefined variable.
The shown error was server side, I'd suggest to make the error a bit more clear when there is some kind of network/fetch error in order to make easier to understand how is failing.

Thanks

**Comment by dotansimha** [comment] 2020-12-01 07:34
I think your server just returned a HTTP 200 with a string error, right? and then it failed because codegen can't parse it...

**Comment by FedeBev** [comment] 2020-12-03 15:36
Hi @dotansimha, my server returned a string error but with 500 as http code.

**Comment by dotansimha** [comment] 2020-12-23 15:10
I see. Is it possible to share a reproduction of the issue? I didn't manage to get the same error...

**Comment by dotansimha** [comment] 2021-01-21 12:51
Closing. I was not able to reproduce this issue. Tried with latest version of codegen, and multiple types of error codes (500, 500 with JSON, 500 with HTML) - all of those gave me different errors, that are detailed, and not this specific one. 
If someone has a reproduction, feel free to report this again or comment here and we'll reopen.

**Closed by dotansimha** 2021-01-21 12:51 UTC
Labels: needs reproduction

**Comment by hamza-amin-tx** [comment] 2021-06-10 14:23
yes i am facing the same issue if i remove my query file then i get this issue and if adds the query file the code generater works fine and parse the data 


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
awais-ror@awaisror-Latitude-E5540:~/graphql_react$ 
awais-ror@awaisror-Latitude-E5540:~/graphql_react$ yarn generate
yarn run v1.22.5
$ graphql-codegen --config codegen.js
  ✔ Parse configuration
  ✔ Generate outputs
Done in 1.20s.
awais-ror@awaisror-Latitude-E5540:~/graphql_react$ yarn generate
yarn run v1.22.5
$ graphql-codegen --config codegen.js
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/generated/graphql.json
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ ./src/generated/graphql.json
    Failed to load schema from http://localhost:4000/graphql:

**Comment by ardatan** [comment] 2021-06-10 15:37
This issue was created a long time ago. Please create a new issue with a clear and minimal reproduction.
