### ISSUE TITLE
gql import

### ISSUE THREAD

**Issue by elge70** [dotansimha/graphql-code-generator#4530] opened 2020-08-06 14:06 UTC
When typescript code is generated, there is a duplicate defn of gql which is giving me compilation error

My config file is attached.

```ts
import { GraphQLResolveInfo } from 'graphql';
import * as Apollo from '@apollo/client';
**import gql from 'graphql-tag';**
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type RequireFields<T, K extends keyof T> = { [X in Exclude<keyof T, K>]?: T[X] } &
    { [P in K]-?: NonNullable<T[P]> };
**const gql = Apollo.gql;**
/** All built-in and custom scalars, mapped to their actual values */
```

`codegen.yml`
```yml
overwrite: true
schema: 'src/Views/Schema/*.graphql'
documents: 'src/**/*.gql'
generates:
    src/Views/Gql/graphql.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-react-apollo'
            - 'typescript-resolvers'
            - 'typescript-document-nodes'

config:
    namePrefix: 'gql'
    typesPrefix: I
    withMutation: true
    withHOC: false
    withHooks: true
    withRefetchFn: true
    withComponent: false
    reactApolloVersion: 3
    withResultType: true
    withMutationOptionsType: true
    useIndexSignature: true
    namingConvention:
        typeNames: pascal-case#pascalCase
        enumValues: upper-case#upperCase

hooks:
    afterOneFileWrite:
        - prettier --write
```

**Comment by ddehghan** [comment] 2020-08-06 19:29
seems that new version of apollo-angualr has a built in gql that should be used.

    import {gql} from 'apollo-angular';

**Comment by dotansimha** [comment] 2020-08-11 12:58
Working on it. Which plugins version do you use?

**Comment by dotansimha** [comment] 2020-08-11 14:04
Hi @ddehghan ! 

`typescript-react-apollo` and `typescript-document-nodes` doesn't play nice together, since they are conflicting and generates similar output. 
The `typescript-document-nodes` already generated the pre-compiled documents for you.
The v2 of `typescript-react-apollo` should take care of the `gql` import, and you can use `documentMode: documentNode` to have a pre-compiled `DocumentNode` just like  `typescript-document-nodes` outputs. 

Closing. Please add more information (exact packages versions, **reproduction** in codesandbox) if you think it's still relevant.

**Closed by dotansimha** 2020-08-11 14:04 UTC
Labels: waiting-for-answer

**Comment by elge70** [comment] 2020-08-12 05:26
I was using the following packages
        "@graphql-codegen/cli": "^1.17.7",
        "@graphql-codegen/typescript": "^1.17.7",
        "@graphql-codegen/typescript-document-nodes": "^1.17.7",
        "@graphql-codegen/typescript-operations": "^1.17.7",
        "@graphql-codegen/typescript-react-apollo": "^2.0.5",
        "@graphql-codegen/typescript-resolvers": "^1.17.7",

But the latest version 1.17.8 have solved the problem.

**Comment by dotansimha** [comment] 2020-08-12 07:23
It should be fixed by `@graphql-codegen/typescript-react-apollo@2.0.6`
