### ISSUE TITLE
Types are not generated for introspection query

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#643] opened 2018-09-24 13:12 UTC
**Describe the bug**
I have a query like this which reads introspection in runtime to figure user permissions. Unfortunately, the generated types do not include the `GUserPermissions` type at all. But if I add something else to that query, it appears there, but without the introspection part.

```js
export const UserPermissionsQuery = gql`
  query GUserPermissions {
    __schema {
      queryType { fields { name } }
      mutationType { fields { name } }
    }
  }
`
```

**To Reproduce**
I am using API approach and call it like this. Full introspection is generated in JSON file. I've checked and it includes types for `__schema`, so that should be a problem.

```js
  generate({
    schema: jsonPath,
    out: './src/graph/types.ts',
    template: 'graphql-codegen-typescript-template',
    args: ['./src/**/*graphql.ts'],
    skipSchema: true,
    overwrite: true,
  })
```

**Expected behavior**
To have TypeScript types based on introspection query.

**Environment:**
 - OS: Windows 10 x64
 - Codegen: 0.9.2
 - Node: 10.11.0

**Comment by dotansimha** [comment] 2018-10-02 11:10
Interesting. Thanks @FredyC ! 

I think we might ignore fields that starts with `__`. I'll check.

**Comment by dotansimha** [comment] 2018-10-02 14:51
@FredyC We are ignoring the internal fields of GraphQL because otherwise it will bloat the results (see https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-core/src/schema/schema-to-template-context.ts#L27) .

I can make this filtering an option, and then it will solve your issue.

**Comment by patricknazar** [comment] 2018-10-10 07:16
I've noticed that when I use simply a `__typename` in fragment, I get similar issues:

    fragment MyFragment on MyType {
        ... on TypeOne {
            __typename
        }
    }

gives me:


    export namespace MyFragment {

        export type TypeOneInlineFragment =

    }

Notice the trailing `=`. Will this resolve this problem too? It's not an introspection query really is it? It is an internal field, right?

**Comment by Jonatthu** [comment] 2019-02-05 19:58
@dotansimha I am having the same issues on the latest version, I really need to do some internal types queries

**Comment by kamilkisiela** [comment] 2019-02-28 19:46
I tried to fix it in #1380, could you guys check if that works in your projects? A canary release under `0.18.0-alpha.d365409c`, make sure you bump all packages from codegen group.

**Comment by dotansimha** [comment] 2019-03-01 10:27
Fixed in 0.18.0 🎉

**Closed by dotansimha** 2019-03-01 10:27 UTC
Labels: bug, core, templates, waiting-for-release

**Comment by Jonatthu** [comment] 2019-03-14 20:38
@dotansimha 0.19.0-alpha.e87c7ccf in this version the services are being generated like this:

```
@Injectable({
	providedIn: "root"
})
export class LoadEntityDetailsQueryGQL extends Apollo.Query<
	LoadEntityDetailsQueryQuery,
	LoadEntityDetailsQueryQueryVariables
> {
```
They should be like this:

```
@Injectable({
	providedIn: "root"
})
export class LoadEntityDetailsQueryGQL extends Apollo.Query<
	LoadEntityDetailsQuery.Query,
	LoadEntityDetailsQuery.Variables
> {
```

**Comment by dotansimha** [comment] 2019-03-16 08:18
@Jonatthu the alpha version you are using is the latest refactor, and it should output without any namespaces at all.

**Comment by Jonatthu** [comment] 2019-03-16 14:05
@dotansimha Well it is having typescript issues or bugs like this, this is giving me a compilation error

**Comment by FredyC** [comment] 2019-03-16 14:29
@Jonatthu You shouldn't be probably using alpha version if you look for stability ;) Either way, namespaces are going to be dropped, so you will either have to adapt or stick to a current version for a while.

**Comment by Jonatthu** [comment] 2019-05-09 18:10
@FredyC I think namespaces was a really good solution to the types, I do not understand why the change...

**Comment by FredyC** [comment] 2019-05-09 18:30
@Jonatthu Well, ask the Microsoft, they have deprecated namespaces from TypeScript. For the same reason, they are not supported by Babel TypeScript implementation, so it's a kinda wrong path to follow altogether.

**Comment by Jonatthu** [comment] 2019-05-09 18:34
@FredyC  So what's the workaround now? 
I would like to pick sub types from a query to be able to create computed properties like this:

```
public get subProperty(): MyQuery.__Field
{
    return this.myQueryResult.Items[0].SomeType.SomeProperty;
}
```

**Comment by Jonatthu** [comment] 2019-05-09 18:43
@FredyC  https://github.com/microsoft/TypeScript/issues/30994
Maybe they are not deprecated...

**Comment by FredyC** [comment] 2019-05-09 18:52
Ok, that's certainly new information, but I don't really miss namespaces. I don't follow why do you need them for your use case. You can as well namespace with a custom delimiter of yours (or none), eg. `MyQuery__Field`.

**Comment by Jonatthu** [comment] 2019-05-09 19:02
First now I am only able to define the type of my query but not of a selection of a section of the query

![image](https://user-images.githubusercontent.com/3742176/57479070-72799980-7251-11e9-9d5c-54eb07c938a9.png)

Second on hover the definition of my second property, this definition is really not dev friendly, specially if is really big type

![image](https://user-images.githubusercontent.com/3742176/57479138-9ccb5700-7251-11e9-9863-da4dd5f0e9ed.png)

And finally, if I wanna strong type this property my only option is to put the base type if this

![image](https://user-images.githubusercontent.com/3742176/57479262-e320b600-7251-11e9-9980-311ed70ac13f.png)

and this tooltip is showing a good definition of my selection BUT this will not match if on my query I only selected one of the properties.

**Comment by FredyC** [comment] 2019-05-09 19:05
Well, sorry, I don't have any viable workarounds here. Since I started using generators, I don't bother with types that much to be bothered by it.

**Comment by Jonatthu** [comment] 2019-05-09 19:06
@FredyC, @dotansimha 
Would be hard to create a namespace plugin for those that miss this feature?

**Comment by dotansimha** [comment] 2019-05-09 19:30
@Jonatthu you can use https://graphql-code-generator.com/docs/plugins/typescript-compatibility

**Comment by Jonatthu** [comment] 2019-05-09 19:47
@dotansimha 

The problem is that each section of the query is defines on this way...
So if I wanna let's say create a property of `rolePermissions`
I need to define this one on this way:

```
const rolePermissions: Maybe<
									{
										__typename?: "GenRolePermissionConnection";
									} & {
										items: Maybe<
											Array<
												Maybe< ...
   = myQuery.pathTo.rolePermissions;

```

Before was way easier to match exactly what my query was selecting on this property.
`const rolePermissions: MyQueryNamespace._RolePermissions = myQuery.pathTo.rolePermissions;`

```
export type LoadPropertyPermissionsQuery = { __typename?: "Query" } & {
	genPermission: Maybe<
		{ __typename?: "GenPermissionConnection" } & {
			items: Maybe<
				Array<
					Maybe<
						{ __typename?: "GenPermissionGraphType" } & Pick<
							GenPermissionGraphType,
							"description" | "guid" | "id" | "key" | "value"
						> & {
								rolePermissions: Maybe<
									{
										__typename?: "GenRolePermissionConnection";
									} & {
										items: Maybe<
											Array<
												Maybe<
													{
														__typename?: "GenRolePermissionGraphType";
													} & Pick<
														GenRolePermissionGraphType,
														"roleId"
													> & {
															role: Maybe<
																{
																	__typename?: "RoleGraphType";
																} & Pick<
																	RoleGraphType,
																	| "id"
																	| "name"
																>
															>;
														}
												>
											>
										>;
									}
								>;
								clientPermissions: Maybe<
									{
										__typename?: "GenClientPermissionConnection";
									} & {
										items: Maybe<
											Array<
												Maybe<
													{
														__typename?: "GenClientPermissionGraphType";
													} & Pick<
														GenClientPermissionGraphType,
														"clientId"
													>
												>
											>
										>;
									}
								>;
								userPermissions: Maybe<
									{
										__typename?: "GenUserPermissionConnection";
									} & {
										items: Maybe<
											Array<
												Maybe<
													{
														__typename?: "GenUserPermissionGraphType";
													} & {
														user: Maybe<
															{
																__typename?: "UserGraphType";
															} & Pick<
																UserGraphType,
																| "username"
																| "email"
															>
														>;
													}
												>
											>
										>;
									}
								>;
							}
					>
				>
			>;
		}
	>;
};
```

**Comment by Jonatthu** [comment] 2019-05-09 19:53
@dotansimha after I used the plugin this keeps not generating the namespaces

this is my config

```
{
	"schema": "http://localhost:5000/graphql",
	"overwrite": true,
	"documents": "src/app/**/*.graphql",
	"generates": {
		"./src/app/generated/graphql.ts": {
			"config": {
				"noNamespaces": false,
				"strict": true
			},
			"plugins": [
				"typescript",
				"typescript-operations",
				"typescript-apollo-angular",
				"typescript-compatibility"
			]
		}
	}
}
```

**Comment by Jonatthu** [comment] 2019-05-09 19:55
@dotansimha My bad the namespaces were being created on the bottom of the generated of the page, i will give it a try

**Comment by Jonatthu** [comment] 2019-05-09 19:59
@dotansimha Looks like introspection namespaces are not being created, is there a flag that we are missing on the docs?
`graphql-codegen --include-introspection-types` I tried this but did not work

**Comment by Jonatthu** [comment] 2019-05-09 22:44
@dotansimha Looks like introspection namespaces are not being created, is there a flag that we are missing on the docs?
`graphql-codegen --include-introspection-types` I tried this but did not work

**Comment by dotansimha** [comment] 2019-05-12 07:54
@Jonatthu actually, the internal introspection types was not included in 0.18, so it's not an issue with backward compatibility. 
We have a solution for it in >1.0, so at the moment you can only get the introspection types with that.

**Comment by Jonatthu** [comment] 2019-05-12 13:51
@dotansimha What’s the solution? Is it something on development or something that I can use now?

**Comment by dotansimha** [comment] 2019-05-12 14:15
@Jonatthu They are generated only if one of your documents asks for it. 
See here: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/typescript/src/index.ts#L112

So if your operations are querying for fields that are declared as internal introspection fields, it will generate those fields as part of your `typescript` plugin output. 

@kamilkisiela implemented this a while ago.

**Comment by RyanCavanaugh** [comment] 2019-05-13 21:40
@FredyC 

> Btw namespaces are legacy and being removed from TypeScript (sadl

This is **not** correct.

**Comment by Jonatthu** [comment] 2019-05-13 21:56
@dotansimha @FredyC  I know could be hard but based on this...
Could be bring back the namespace convention that we used to have?
The plugin compatibility generates some models but still really hard to read by example:

```
export namespace LoadPropertyPermissions {
	export type Variables = LoadPropertyPermissionsQueryVariables;
	export type Query = LoadPropertyPermissionsQuery;
	export type GenPermission = LoadPropertyPermissionsQuery["genPermission"];
	export type Items = LoadPropertyPermissionsQuery["genPermission"]["items"][0];
	export type RolePermissions = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["rolePermissions"];
	export type _Items = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["rolePermissions"]["items"][0];
	export type Role = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["rolePermissions"]["items"][0]["role"];
	export type ClientPermissions = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["clientPermissions"];
	export type __Items = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["clientPermissions"]["items"][0];
	export type UserPermissions = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["userPermissions"];
	export type ___Items = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["userPermissions"]["items"][0];
	export type User = LoadPropertyPermissionsQuery["genPermission"]["items"][0]["userPermissions"]["items"][0]["user"];
}
```

Would be nice to keep the old behavior creating interfaces instead of grabbing parts of a type this way 

`export type UserPermissions = LoadPropertyPermissionsQuery["genPermission"]["items"][0]`

Anyways this is an amazing project and it is doing a great job, but sometimes old features are still totally fine to keep. Specially if helps to devs to maintain and understand the code generated right away.

**Comment by dotansimha** [comment] 2019-05-16 09:18
@Jonatthu we choose this path because we would to be able to create base package and use it.
I know it's a bit harder to read, but in most cases it just fulfil the need for auto-complete from a query response. 
We decided to remove the intermediate types because it caused a lot of issues with the generated output, and the `typescript-compatibility` is there only to make it easier to migrate. 

I think, maybe, in the future, we can add a configuration for resolving the type and not using `Pick<>` and this way you'll have the primitive type directly there, instead of picking it. (but that depends on our time and resources)

**Comment by Jonatthu** [comment] 2019-05-22 17:27
@dotansimha I think for the future would be a great investment, but thanks for all the current work, the cli is looking awesome and feeling professional.

**Comment by dotansimha** [comment] 2019-05-28 16:24
@Jonatthu I opened a new issue for that: https://github.com/dotansimha/graphql-code-generator/issues/1925
