### ISSUE TITLE
Type 'undefined' is not assignable to baseOptions

### ISSUE THREAD

**Issue by quentinus95** [dotansimha/graphql-code-generator#3679] opened 2020-03-19 13:04 UTC
**Describe the bug**

When trying to update `@vue/apollo-composable` from `4.0.0-alpha.4` to `4.0.0-alpha.7`, I'm getting the following type errors with `graphql-code-generator` (on argument `baseOptions`) for all my mutations:

```
Argument of type 'UseMutationOptions<DoSomethingMutation, DoSomethingMutationVariables> | undefined' is not assignable to parameter of type 'UseMutationOptionsWithVariables<DoSomethingMutation, DoSomethingMutationVariables> | ReactiveFunction<...>'.
       Type 'undefined' is not assignable to type 'UseMutationOptionsWithVariables<DoSomethingMutation, DoSomethingMutationVariables> | ReactiveFunction<...>'.
                  return VueApolloComposable.useMutation<DoSomethingMutation, DoSomethingMutationVariables>(DoSomethingDocument, baseOptions);
```
**To Reproduce**

Use the latest version of `graphql-code-generator` with `@vue/apollo-composable` `4.0.0-alpha.7` and any kind of mutation.

Config:

```yaml
# ...
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
```

**Expected behavior**

Generated code triggers no compiler error.

**Environment:**

- OS: Docker
- `@graphql-codegen/*`: `1.13.1`
- NodeJS: 13.1.0

**Comment by dotansimha** [comment] 2020-03-22 10:10
It think it might be some changes to the API of `@vue/apollo-composable`? 

I'm not familiar with it, so it might be difficult for us to reproduce. 

@quentinus95 can you please create a repo / codesandbox that reproduces it? thank you!

**Comment by quentinus95** [comment] 2020-03-22 12:08
@dotansimha here you go: https://github.com/quentinus95/graphql-code-generator-3679

**Comment by quentinus95** [comment] 2020-03-27 08:06
@dotansimha do you need me to provide you any other piece of information?

**Comment by JoeSchr** [comment] 2020-03-29 15:28
I got it too.

Funnily enough not inside my docker (on a windows host), only when used natively on gallium-os/ubuntu-bionic. both tsc are on 3.8.3, I really don't get it...

**Comment by rebolyte** [comment] 2020-04-02 19:38
@dotansimha @iskanderbroere Any updates here? This seems to have been introduced with the overloads added in @vue/apollo-composable v4.0.0-alpha.5 in vuejs/vue-apollo#895.

**Comment by iskanderbroere** [comment] 2020-04-04 14:13
You're right it only work with alpha.4, i'll take a look making it compatible with alpha.8

**Comment by iskanderbroere** [comment] 2020-04-12 08:25
@bbugh Do you have any ideas on what the generated code could look like? Would you suggest introducing overloads here as well? (like in [vuejs/vue-apollo#895](https://github.com/vuejs/vue-apollo/commit/32d1f7568e1a4b72fbe2de4ada6985c65675a84b#diff-983e3b01b3ccac2d3c517340aa8ee99e))

**Comment by Dodobibi** [comment] 2020-04-12 10:41
This workaround work for me :

For **query**, no need to implement all overloads. just replace 
```js
return `type ${reactiveFunctionTypeName} = () => ${operationVariablesTypes}\nexport function use${operationName}(variables${
          operationHasNonNullableVariable ? '' : '?'
        }: ${operationVariablesTypes} | VueCompositionApi.Ref<${operationVariablesTypes}> | ${reactiveFunctionTypeName}, baseOptions?: VueApolloComposable.Use${operationType}Options<${operationResultType}, ${operationVariablesTypes}>) {
          return VueApolloComposable.use${operationType}<${operationResultType}, ${operationVariablesTypes}>(${documentNodeVariable}, variables, baseOptions);
        }`;
```
by

```js
return `export function use${operationName}(variables: ${operationVariablesTypes} | VueCompositionApi.Ref<${operationVariablesTypes}> | ${reactiveFunctionTypeName}${
          operationHasNonNullableVariable ? "" : "={}"
        }, baseOptions: VueApolloComposable.Use${operationType}Options<${operationResultType}, ${operationVariablesTypes}>=\{\}) {
            return VueApolloComposable.use${operationType}<${operationResultType}, ${operationVariablesTypes}>(${documentNodeVariable}, variables, baseOptions);
          }

type ${reactiveFunctionTypeName} = () => ${operationVariablesTypes}`;
```

I move `type ${reactiveFunctionTypeName} = () => ${operationVariablesTypes}` under the useXXXQuery, else, JSDoc for useXXXQuery won't work...

then, "variables" is optional only if they have non-nullable variables, and baseOptions is always optional.
Generated function like this (look at the default initializer of "variables"):
```ts
export function useAutocompleteCommunesQuery(
  variables:
    | AutocompleteCommunesQueryVariables
    | VueCompositionApi.Ref<AutocompleteCommunesQueryVariables>
    | ReactiveFunctionAutocompleteCommunesQuery = {},
  baseOptions: VueApolloComposable.UseQueryOptions<
    AutocompleteCommunesQuery,
    AutocompleteCommunesQueryVariables
  > = {}
) {
  return VueApolloComposable.useQuery<
    AutocompleteCommunesQuery,
    AutocompleteCommunesQueryVariables
  >(AutocompleteCommunesDocument, variables, baseOptions);
}
```
or (if operationHasNonNullableVariable, default variables is not set because it's not optional):

```ts
export function useAdministrationsCommuneQuery(
  variables:
    | AdministrationsCommuneQueryVariables
    | VueCompositionApi.Ref<AdministrationsCommuneQueryVariables>
    | ReactiveFunctionAdministrationsCommuneQuery,
  baseOptions: VueApolloComposable.UseQueryOptions<
    AdministrationsCommuneQuery,
    AdministrationsCommuneQueryVariables
  > = {}
) {
  return VueApolloComposable.useQuery<
    AdministrationsCommuneQuery,
    AdministrationsCommuneQueryVariables
  >(AdministrationsCommuneDocument, variables, baseOptions);
} 
```
I don't know if it's the good way...

For **mutation**, it's more complicated because we can't know if the user want to pass variables in options parameter of useMutation... Maybe we can test if there is variables and we return the good overload ?

**Comment by bbugh** [comment] 2020-04-13 15:39
> @bbugh Do you have any ideas on what the generated code could look like? Would you suggest introducing overloads here as well? (like in [vuejs/vue-apollo#895]([https://github.com/vuejs/vue-apollo/commit/32d1f7568e1a4b72fbe2de4ada6985c65675a84b#diff-983e3b01b3ccac2d3c517340aa8ee99e]))

Good question. I haven't worked on this for a while so I'm going from memory but I'll do my best to answer!

I don't expect that the generator will have to change much because the behavior (as far as I know, I'm still on alpha4) hasn't changed, the typing just got more specific and correct. I believe that @Dodobibi is on the right track by assigning defaults if something isn't specified. I think they should be optional and not defaulted, though, because vue-apollo maps undefined values to the correct default internally:

https://github.com/vuejs/vue-apollo/blob/35ea099209a36f4825988f9c0f4343441d9ff3f7/packages/vue-apollo-composable/src/useQuery.ts#L106-L107

I'm not sure if the generator checks if the type itself requires variables, that would be a useful enhancement to make `variables` required or not. Queries obviously don't always require variables or options, so either one can be undefined. 

I believe that to fix the issue reported by @quentinus95 , the `useQuery` generator signature should be:

```
useThing(variables?: <types>, baseOptions?: <types>)
                  ^ maybe whether this is optional is determined by the generator
```

I hope that helps! I'm happy to answer more questions if needed.

**Comment by bbugh** [comment] 2020-04-13 15:40
Personally, though, I think this presents an opportunity for the generator to offer a more developer-friendly API than the vue-apollo one. I would personally like to see the functions take in a single object that requires variables or not depending on the query. There are many times I want to call a query that has no variables but does have options (like for `fetchPolicy`) and that requires passing `useThing(undefined, { options })` which just seems so clunky and y2k. It could generate something like this: 

```typescript
export useThingThatRequiresVariables(baseOptions: RequiredVariablesQueryOptions<x>)

export useThingWithoutVariables(baseOptions?: QueryOptions<x>)
```

🔥

**Comment by dotansimha** [comment] 2020-04-19 08:56
Fixed in 1.13.3

**Closed by dotansimha** 2020-04-19 08:56 UTC
Labels: bug, templates, waiting-for-release

**Comment by Dodobibi** [comment] 2020-04-19 10:06
Work partially (when `operationHasNonNullableVariable`)

The operand `?` on variables must be set when `operationHasVariables` is True, instead of `operationHasNonNullableVariable`

Also, can you add  (when `operationHasVariables` is True) :
```js
* @variables ......
```
in JSDoc just upper :
```js
* @param options that will be passed into the query,
```

Else : all working 👍

**Comment by bbugh** [comment] 2020-04-21 12:43
@iskanderbroere I investigated this further this morning.

I believe the specific issue reported here by @quentinus95 was caused by https://github.com/vuejs/vue-apollo/commit/a9d950156d1f8e89cf8ba3532936b6a09e0b776a, but that incorrect behavior is the result of an underlying incorrect assumption on my part. I believe this will be resolved after the PR for https://github.com/vuejs/vue-apollo/issues/961.

**Comment by bbugh** [comment] 2020-04-21 15:10
I submitted a PR for this: https://github.com/vuejs/vue-apollo/pull/962

If y'all have time to check it out and make sure I have it right this time, that'd be really helpful.

**Comment by JoeSchr** [comment] 2020-04-21 16:24
what do we need to do to test this PR? update `graphql-code-generator@1.13.3` and `@vue/apollo-composable` to your branch?

**Comment by bbugh** [comment] 2020-05-08 22:20
I don't know very much about mono repos, unfortunately. I'm not sure how to get a version from the vue-apollo repo. `yarn link` maybe?

**Comment by NickBolles** [comment] 2020-05-20 04:06
I think the generator also needs to be updated to include the reactive function part of the useMutation defiintion too

apollo-composable
```ts
export declare function useMutation<TResult = any, TVariables extends OperationVariables = OperationVariables>(document: DocumentNode | ReactiveFunction<DocumentNode>, options?: UseMutationOptionsWithVariables<TResult, TVariables> | ReactiveFunction<UseMutationOptionsWithVariables<TResult, TVariables>>): UseMutationReturn<TResult, TVariables>;
```
Generated useMutation
```ts
export function useAddRecipeMutation(options: VueApolloComposable.UseMutationOptionsWithVariables<AddRecipeMutation, AddRecipeMutationVariables>) {
            return VueApolloComposable.useMutation<AddRecipeMutation, AddRecipeMutationVariables>(AddRecipeDocument, options);
          }
```
this part in particular
```ts
options: VueApolloComposable.UseMutationOptionsWithVariables<AddRecipeMutation, AddRecipeMutationVariables>
```
should probably be more like this:
```ts
options?: UseMutationOptionsWithVariables<AddRecipeMutation, AddRecipeMutationVariables> | ReactiveFunction<UseMutationOptionsWithVariables<AddRecipeMutation, AddRecipeMutationVariables>>
```

**Comment by bbugh** [comment] 2020-05-21 15:10
@NickBolles if I understand what you're suggesting, the patch in https://github.com/vuejs/vue-apollo/pull/962 should address it. The vue-apollo maintainer has been MIA for a while, which unfortunately happens pretty often. Hopefully this will get merged soon as vue-apollo alpha is currently borked for TypeScript users.
