### ISSUE TITLE
[typescript-operations] Arrays nested inside named fragments are not merged together

### ISSUE THREAD

**Issue by helios1138** [dotansimha/graphql-code-generator#4212] opened 2020-06-11 16:09 UTC
Arrays nested inside named fragments are not merged together

for example, given the schema
```gql
type Item {
  id: ID!
  name: String!
}

type Object {
  items: [Item!]!
}
```
and operations
```gql
fragment Object1 on Object {
  items {
    id
  }
}

fragment Object2 on Object {
  items {
    id
    name
  }
}

fragment CombinedObject on Object {
  ...Object1
  ...Object2
}

```
in the generated code
```ts
import { CombinedObjectFragment } from '../../generated/documents'

const object: CombinedObjectFragment = {} as any

for (const item of object.items) console.log(item.name) // Typescript Error
```
you get an error
> Error:(5, 51) TS2339: Property 'name' does not exist on type '{ __typename?: "Item" | undefined; id: string; }'.

Which is incorrect since both `Object1` and `Object2` fragments are on the same type `Object` and are merged together in the graphql, so the field `item.name` is present at runtime

I'm guessing the problem stems from the fact that combined fragment types are defined dynamically as
```ts
export type CombinedObjectFragment = (
  { __typename?: 'Object' }
  & Object1Fragment
  & Object2Fragment
);

```
and there are some typescripts-specific issues at play here.

I think it would be good to have an option to flatten the combined fragment types so that we still get `Object1Fragment` and `Object2Fragment` generated separately, but `CombinedObjectFragment` does not reference them dynamically, instead, it would be listing the fields inside explicitly. 

Something similar to how `preResolveTypes` eliminates dynamic `Pick` types, but for fragments as well.

**Comment by dotansimha** [comment] 2020-06-15 07:44
Thanks @helios1138 , I'm trying to fix it now :)

**Comment by helios1138** [comment] 2020-06-16 09:05
>I'm trying to fix it now :)

@dotansimha thank you very much! 

Regarding `flattenSelectionSet`: can't find this option in the documentation. Did you mean `flattenGeneratedTypes`? If yes, I've tried that and unfortunately, it would not work for me as it avoids generating fragment types altogether and my code relies on them. Also, it does not actually work in my project (I've only tried it on simple examples) as I'm getting an error
```
TypeError: parentType.isTypeOf is not a function
```
However, I did yet find the time to create a simple reproducible example for this error :)

**Comment by dotansimha** [comment] 2020-06-17 06:29
@helios1138 yeah you are right, it's `flattenGeneratedTypes`, and it does fields optimization, so it might simplify the output for your (but yeah, remove fragments...). Can you share a reproduction for that error?

@kamilkisiela tried to help me with a way to merge the fragment objects. It seems like `A & B` in TS doesn't merge array items correctly, so we might need some helpers for that.

**Comment by threehams** [comment] 2020-08-28 00:53
I'm not sure about viability here, but would you accept an PR with an additional option for `flattenGeneratedTypes` which preserves any documents containing only fragments? They would be used only for tests and types at that point.

That would be a fix this issue, be a nice runtime improvement, and prevent the need to include fragment documents in queries.

**Comment by kohlmannj** [comment] 2021-02-21 14:12
Would love to see a fix for this issue, as it potentially blocks us from adopting GraphQL Code Generator in one of our projects. (I will see if I can find time to look into it myself, but at least wanted to make a note of this.)

**Comment by dotansimha** [comment] 2021-03-07 11:04
@kohlmannj @helios1138 Can you please give it a try to TypeScript 4? 

I checked your given example with something like that:

```graphql
fragment Object1 on Object {
  items {
    id
  }
}

fragment Object2 on Object {
  items {
    name
  }
}

```

I got 2 fragments generated:

```ts
   export type Object1Fragment = (
      { __typename?: 'Object' }
      & { items: Array<(
        { __typename?: 'Item' }
        & Pick<Item, 'id'>
      )> }
    );
    
    export type Object2Fragment = (
      { __typename?: 'Object' }
      & { items: Array<(
        { __typename?: 'Item' }
        & Pick<Item, 'name'>
      )> }
    );
```

Which eventually getting merged like that:

```ts
    export type CombinedObjectFragment = (
      { __typename?: 'Object' }
      & Object1Fragment
      & Object2Fragment
    );
```

I wrote a small piece of code that uses the query result and tries to access both fields:

```ts
function test (t: TestQuery) {
    for (const item of t.obj!.items) {
      console.log(item.id, item.name, item.__typename);
    }
}
```

And it seems fine, no errors at all with TS v4, also the auto-complete seems to work nicely:

![image](https://user-images.githubusercontent.com/3680083/110236823-a8b4fc80-7f40-11eb-8fc1-a695996f70c1.png)

> Note that with TS 3, it does not work, and I get the `Property 'name' does not exist on type` error that @helios1138 mentioned. 

- [Here's the generated code with the example in TS 4.2.2](https://www.typescriptlang.org/play?ts=4.2.2#code/AQ4UwDwBwewJwC7AQTymYBZAhigRmADwAqAfMALzDHAA+wAdgK4A2LA3ALABQo408JKnTAAohGwBjBCX4IwDACYBnYAG9gAbQDWYFAC5gyhHACWDAOYBdQ0wbaGMAO4NgAX3JUNmgNLBzwLooMABm1DbUvlbuXLygkLCIyGgYOLoA8lAIpjAM2CwkADTAfpDySqpBodSewOkAtqYyxMU+5ABk6loAykx4Pnr+rj5WAPyGOPhExJq9-XpW5G6xfAmCySJpYJMERSVyCiqBetVklHWNza0dXbN9AyhDJRE703fzKIsxPHwA9ABU-2AAEE2MA8ExTCwEABaALYJTASRMYwwepGST5bBwZTFerYKDoRTIGDIAAWYFMcGAUgQTHywAAbvkmGBVP9fj94gIksIMN1MSxsaovFy+ABJAAihmMZksKz4wG6JnMFhlKvlYtAACEYDAWGAEYY8HqDQiFRKGAhDMx6gQ4BbQAAxFgwbDWxhMO1gB1a5ZarVrXkpYDi+To0VxPgAfWjfLy9TA42AAHIw2B6inHSBTIpDAKsTjNGnJSmrNnGNhE-nBcLi8q5RYy47-VHgIGeUIQ+k8AArMDSc5qLUgWPxqtJwwpnv96RZkf+cPKQzAuBwXCEdP1Ugtx0dxJdkQARVZcEekcVwDHKQTk9TJ59KHnbZAMD7ydehBnA4QO79jqDQ8MG-aQAEYnXXCxEytc4AAoFw0a90FvZNpz7H8U3cBdOg0JoM2XEE1w3eCX1ARC4xvCdUK3TC3AXEBOgABVMSRtE3cNihTXMU1IBcAEoli1Pi9zbQCNmA9DpAAJgg7AoIUJAqBIy9yPHRNUJAhBaOwro8PqAjV3XFBCGUy8uiQhQqKnGisNIhjgGY1j2IzTjbx4-jBLbYSA1EztxOAABhNE8HMMBFE02T5JgpSEKvCjkKs1NNO00jOk08DIOghAdM0mTMoUoSRNWPy+WoNkEAfM8ADVsVMbA8ANEUxAkaRCG8IJ1UbCIGDARkfXYdw-zbHzioPfziHKyrz2AUy+FUyj1KnKaUsvHDgDfXsP1wXZZsVeaEsWpLJK02yzOATogrtULwuOyKso807QG87geBCOxpByVx5GMGaPQm4wpr49QtRCeAZskXIfr09awgQAA6DaAEI4b05QgeHUiIYYZR9TAOHXQsWC9JRxRimJ28yfDOGLNvZ6+Do7g3CAA)
- [Here's the same with TS 3.9.7](https://www.typescriptlang.org/play?ts=3.9.7#code/AQ4UwDwBwewJwC7AQTymYBZAhigRmADwAqAfMALzDHAA+wAdgK4A2LA3ALABQo408JKnTAAohGwBjBCX4IwDACYBnYAG9gAbQDWYFAC5gyhHACWDAOYBdQ0wbaGMAO4NgAX3JUNmgNLBzwLooMABm1DbUvlbuXLygkLCIyGgYOLoA8lAIpjAM2CwkADTAfpDySqpBodSewOkAtqYyxMU+5ABk6loAykx4Pnr+rj5WAPyGOPhExJq9-XpW5G6xfAmCySJpYJMERSVyCiqBetVklHWNza0dXbN9AyhDJRE703fzKIsxPHwA9ABU-2AAEE2MA8ExTCwEABaALYJTASRMYwwepGST5bBwZTFerYKDoRTIGDIAAWYFMcGAUgQTHywAAbvkmGBVP9fj94gIksIMN1MSxsaovFy+ABJAAihmMZksKz4wG6JnMFhlKvlYtAACEYDAWGAEYY8HqDQiFRKGAhDMx6gQ4BbQAAxFgwbDWxhMO1gB1a5ZarVrXkpYDi+To0VxPgAfWjfLy9TA42AAHIw2B6inHSBTIpDAKsTjNGnJSmrNnGNhE-nBcLi8q5RYy47-VHgIGeUIQ+k8AArMDSc5qLUgWPxqtJwwpnv96RZkf+cPKQzAuBwXCEdP1Ugtx0dxJdkQARVZcEekcVwDHKQTk9TJ59KHnbZAMD7ydehBnA4QO79jqDQ8MG-aQAEYnXXCxEytc4AAoFw0a90FvZNpz7H8U3cBdOg0JoM2XEE1w3eCX1ARC4xvCdUK3TC3AXEBOgABVMSRtE3cNihTXMU1IBcAEoli1Pi9zbQCNmA9DpAAJgg7AoIUJAqBIy9yPHRNUJAhBaOwro8PqAjV3XFBCGUy8uiQhQqKnGisNIhjgGY1j2IzTjbx4-jBLbYSA1EztxOAABhNE8HMMBFE02T5JgpSEKvCjkKs1NNO00jOk08DIOghAdM0mTMoUoSRNWPy+WoNkEAfM8ADVsVMbA8ANEUxAkaRCG8IJ1UbCIGDARkfXYdw-zbHzioPfziHKyrz2AUy+FUyj1KnKaUsvHDgDfXsP1wXZZsVeaEsWpLJK02yzOATogrtULwuOyKso807QG87geBCOxpByVx5GMGaPQm4wpr49QtRCeAZskXIfr09awgQAA6DaAEI4b05QgeHUiIYYZR9TAOHXQsWC9JRxRimJ28yfDOGLNvZ6+Do7g3CAA)
- [Here's a minimal example for a working array union with TS4](https://www.typescriptlang.org/play?ts=4.2.2#code/C4TwDgpgBAglC8UDeBYAUFKA7CBnYEAJgFzLqaYCWBAtrqTAE6MCGIAPElJSVPo5SwBzKAF8AfAG5yY9KPTpQkKACEEZDNjwFeqTVVr1YzNp2wsaEUv0EiJ0zfLRPF4aAFV1cAGSqH6ADMAVywAY2BKAHssKAJ8AAog0ncASg1MAMjGKHjQ6PxuWihIgKgggDocfCJy6gg6NL0KKDysXEiAGwhyjsiheLqaWsIAGkL6yosIFJknUSA)

I created a test in the repo (which uses the latest TS 4) and the test passes compilation with no errors: https://github.com/dotansimha/graphql-code-generator/pull/5665

Can you please confirm the above and let me know if it works correctly?

**Comment by dotansimha** [comment] 2021-03-07 14:44
> > I'm trying to fix it now :)
> 
> @dotansimha thank you very much!
> 
> Regarding `flattenSelectionSet`: can't find this option in the documentation. Did you mean `flattenGeneratedTypes`? If yes, I've tried that and unfortunately, it would not work for me as it avoids generating fragment types altogether and my code relies on them. Also, it does not actually work in my project (I've only tried it on simple examples) as I'm getting an error
> 
> ```
> TypeError: parentType.isTypeOf is not a function
> ```
> 
> However, I have yet find the time to create a simple reproducible example for this error :)

The `TypeError: parentType.isTypeOf is not a function` was fixed a long time ago. so if you are dealing with that, just update the latest :)

**Comment by ardatan** [comment] 2021-04-16 16:53
Closed due to the lack of response. Feel free to create a new issue if the problem persists.

**Closed by ardatan** 2021-04-16 16:53 UTC
Labels: bug, plugins, waiting-for-answer
