### ISSUE TITLE
TypeScript - Bad syntax generated due to private interface

### ISSUE THREAD

**Issue by ArrayKnight** [dotansimha/graphql-code-generator#5074] opened 2020-11-12 02:08 UTC
**Describe the bug**
When a public query would return a private interface (due to a mistake in the public schema), the Codegen CLI "successfully" completes, but creates a type definition file with invalid (syntactically incorrect) types/interfaces (`Maybe<Array<Maybe<>>>`).

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Foo = { ... } # Private type which should be public but isn't (setting in CMSs public GraphQL schema)

type Query = {
    foos(id: String): [Foo]
}
```

2. My GraphQL operations:

```graphql
query Foos($id: String) {
    foos(id: $id) { ... }
}
```

3. My `codegen.yml` config file:

```yml
schema: ${GRAPHQL_SCHEMA_URL}
documents:
    - 'src/**/*.{ts,tsx}'
    - '!src/graphql/*'
generates:
    src/graphql/index.tsx:
        plugins:
            - typescript
            - typescript-operations
            - fragment-matcher
        config:
            avoidOptionals: true
            nonOptionalTypename: true

```

4. My `src/graphql/index.tsx`:

```typescript
export type FoosQuery = (
    { __typename: 'Query' } &
    { foos: Maybe<Array<Maybe<>>> } // <-- Missing interface due to private type, would be Pick<Foo, '...'> if it were public
)
```

**Expected behavior**
Codegen CLI should throw an error detailing that there is a missing/private type that it can't write and then not output a file

**Environment:**

- OS: Windows 10
- "@graphql-codegen/cli": "^1.19.1",
- "@graphql-codegen/fragment-matcher": "^2.0.0",
- "@graphql-codegen/schema-ast": "^1.18.0",
- "@graphql-codegen/typescript": "^1.17.11",
- "@graphql-codegen/typescript-operations": "^1.17.9",
- NodeJS: 13.11.0

**Comment by ArrayKnight** [comment] 2020-11-12 04:00
Another possibility would be to write `unknown` in place of the missing type. Though a warning in CLI would also be nice

**Comment by dotansimha** [comment] 2020-11-16 07:03
Thank you for reporting this @ArrayKnight . I'm not sure I fully understand this concept of private/public here. If an interface isn't being published as part of the schema, it should fail in codegen due to a missing type during the validation phase.
Can you please share a live reproduction of this issue?

**Comment by ArrayKnight** [comment] 2020-11-19 21:23
I don't have any immediate time to setup an environment, but I can describe it in a more specific example:

We're using Craft CMS as a headless CMS, so we bought a Pro license, enabled the GraphQL interface and got to modeling our data.

1. Create a top level Entry type (Page)
2. Go to the GraphQL Public Schema
3. Notice that Assets is unchecked (private, not part of the public schema)
4. Check Entries > Section - Page, hit Save
5. Add a field (images) to Page of the type Assets

Now, when you do a schema codegen you'll end up with something like:
```gql
type Query {
    entry(
        # ...removed for clarity
    ): EntryInterface

    entries(
        # ...
    ): [EntryInterface]
}

type AssetInterface { # Oddly present despite not being part of the public schema
    #...
}

type page_page_Entry implements ElementInterface & EntryInterface {
    images(
        # ...
    ): [AssetInterface]
}
```

So, then you would write a query:
```gql
query Page($uid: [String]){
    entry(uid: $uid) {
        ... on page_page_Entry {
            images {
                url
            }
        }
    }
}

fragment Section on section_BlockType {
    tiles {
        ... on tiles_BlockType {
            tileImage { # also an assets field
                uid
                url
            }
        }
    }
}
```

And what's interesting is that you will find AssetInterface as a top level type and you'll even find it referenced within top level types that have asset fields, but when you have a fragment that references that interface you get invalid syntax:
```typescript
export type AssetInterface = {
    // ...
}

export type Page_Page_Entry = ElementInterface & EntryInterface & {
    // ...

    images: Maybe<Array<Maybe<AssetInterface>>>;
}

export SectionFragment = (
    { __typename: 'section_BlockType ' } & 
    { tiles: Maybe<Array<Maybe<(
        { __typename: 'tiles_BlockType' } & 
        { tileImage: Maybe<Array<Maybe<>>> } // <-- Invalid syntax
    )}
)
```

**Comment by ArrayKnight** [comment] 2020-11-19 21:26
To remedy this, I had to go to the GraphQL Public Schema, check Assets, and hit save.

**Comment by dotansimha** [comment] 2020-11-29 12:22
Closing, @ArrayKnight . This was related to missing config right?

**Closed by dotansimha** 2020-11-29 12:22 UTC
Labels: needs reproduction

**Comment by ArrayKnight** [comment] 2020-11-30 18:52
@dotansimha I disagree that this should be closed.

I can see the argument that this is a setting in Craft CMS that causes this issue, however, I feel like the codegen tool should handle this case by either throwing an error in CLI or replacing the missing type with `unknown` and warning in the CLI.

**Comment by dotansimha** [comment] 2020-12-01 07:32
I see, but I'm not familiar with CraftCMS, or with the exact setup that you have, and you are not able to create a complete reproduction. I don't have any tools to reproduce or investigate it. 
I'm willing to try to solve that, but I will need your cooperation... 
Please share a reproduction and then I'll re-open this.
