### ISSUE TITLE
Yarn workspaces: Fix dependency resolution or document "nohoist"

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [dotansimha/graphql-code-generator#3118] opened 2019-12-14 18:59 UTC
**Describe the bug**
Dependency resolution doesn't seem to work correctly when using yarn workspaces:
```
 Found 1 error

  × generated/graphql.ts
    Unable to load template plugin matching 'typescript-resolvers'.
    Reason:
      Cannot find module '@graphql-codegen/core'
    Error: Unable to load template plugin matching typescript-resolvers
```

**To Reproduce**

- Clone the following minimal repro
- Install dependencies
- Run `yarn generate` in `packages/graphql`

https://github.com/s-h-a-d-o-w/repro-codegen-workspaces

**Expected behavior**
Can run the script without errors.

**Additional context**
It does work when adding this to `package.json`:
```
  "workspaces": {
    "nohoist": [
      "@graphql-codegen/**"
    ]
  },
```

Which is why I would recommend that if a solution can't be found to document this [here](https://graphql-code-generator.com/docs/getting-started/#installation).

**Comment by dotansimha** [comment] 2020-01-27 14:15
We had an issue with the dependencies mapping (one of the common packages was using `core`, it caused Yarn to install some of the deps twice). Thanks to @kamilkisiela, we found it. 

I fixed it in: https://github.com/dotansimha/graphql-code-generator/pull/3386

**Comment by dotansimha** [comment] 2020-01-27 15:03
@s-h-a-d-o-w Can you please try `1.11.3-alpha-48bfb197.95`? It should work (make sure to use it without `~` or `^`).
Also, change the package name in your reproduction to `graphql-test` or something, because it conflicts with the original `graphql`. 

I tested it now and it seems to work.

**Comment by s-h-a-d-o-w** [comment] 2020-01-27 15:37
Updated the repo - looks good to me too, thanks! 😃👍

**Comment by dotansimha** [comment] 2020-01-28 15:36
Fixed in `v1.12.0`

**Closed by dotansimha** 2020-01-28 15:36 UTC
Labels: bug, core, waiting-for-release

**Comment by bkiac** [comment] 2022-01-07 16:34
I think this should be documented on the website, `nohoist` is a better alternative than installing the generator in the root folder

**Comment by Urigo** [comment] 2022-01-12 17:35
@bkiac would you mind creating a PR for the docs? thanks!
