### ISSUE TITLE
Allow ability to define avoidOptionals or maybeValues against input or output types

### ISSUE THREAD

**Issue by ktsosno** [dotansimha/graphql-code-generator#1935] opened 2019-05-30 00:34 UTC
I'm having an issue with typescript + graphl code generator and reconciling mutation and query component input / output types.

We inherited this pattern from working with apollo codegen. We have input types that accept a more flexible scalar type than `Maybe<string>`. It gives us the ability to just not include a specific value in a mutation payload instead of passing it in as null. For example:

Given the generated typing (with graphql-code-generator):
```js
export type UpdateUserProfileInput = {
  userId: Maybe<Scalars['UserId']>
  firstName: Maybe<Scalars['String']>
  lastName: Maybe<Scalars['String']>
  phone: Maybe<Scalars['String']>
  email: Maybe<Scalars['String']>
}
```

And the generated typing with apollo-codegen:
```js
export interface UpdateUserProfileInput {
  userId?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  phone?: string | null,
  email?: string | null,
};
```

The former doesn't allow me to pass in a partial update like so:
```jsx
<UpdateUserComponent>
  variables={{
    input: {
      phone: '4155555555',
      firstName: 'Some Name'
    }
}}>
...
</UpdateUserComponent>
```

I'd instead need to pass all the values in as `lastName: null, userId: null` etc. to keep typescript from complaining, which isn't ideal.

**Describe the solution you'd like**
The ability to specify a maybeValue override for output and input types separately.

**Describe alternatives you've considered**
I've tried specifying my own maybeValue or enabled `avoidOptionals`, but this results in my output types more or less being incorrect as the nullable fields are now undefined. If I could specify the maybeValue input and output types independently, I could get around this.

**Comment by slikts** [comment] 2019-06-12 09:28
This is a duplicate of #1885

**Closed** 2019-06-18 07:20 UTC
Labels: enhancement, templates

**Comment by ljukas** [comment] 2020-03-18 10:33
I'd like to raise this issue. It is not a duplicate of #1885. That issue refers to setting the avoidOptionals indecently between input and output types. This issue wants the same functionallity for the maybeValue. 

My issue is that I want maybeValues for inputs to be T | undefined, and T | null for outputs. Or this possible? Maybe I'm misunderstanding something.

**Comment by zerkalica** [comment] 2020-06-16 09:19
> I'd like to raise this issue. It is not a duplicate of #1885. That issue refers to setting the avoidOptionals indecently between input and output types. This issue wants the same functionallity for the maybeValue.
> 
> My issue is that I want maybeValues for inputs to be T | undefined, and T | null for outputs. Or is this possible? Maybe I'm misunderstanding something.

I need place null-garbage in ts interfaces for gql query-generated types, need an optional non-nullable type in gql.

```
        landAreaMin?: number | null;
        landAreaMax?: number | null;
        landStatus?: LandStatusEnum[] | null;
```

**Comment by brahimmouhamou** [comment] 2021-03-18 16:55
@ljukas @ktsosno , did you find a solution for the use case @ljukas describes?
