### ISSUE TITLE
 Unable to find any GraphQL type definitions for the following pointers: -"src/**/*.graphql"

### ISSUE THREAD

**Issue by seyaobey** [dotansimha/graphql-code-generator#2979] opened 2019-11-18 02:23 UTC
**Describe the bug**
I have created a brand new react-native application and I, now, attempt to generate graphql schema from my backend `https://umoja-apps.herokuapp.com/graphql` where it is exposed.
I entered
```
$ graphql-codegen init
```
and followed the steps from the wizard, which produced the below `codegen.yml`:
```
overwrite: true
schema: "https://umoja-apps.herokuapp.com/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

This is the `package.json` script I should run to generate the schema:
```
"schema": "graphql-codegen --config codegen.yml"
```

But the above command fails with the following errors:
```
✖src/generated/graphql.tsx
    Error: Unable to find any GraphQL type definitions for the following pointers: -"src/**/*.graphql"

...

✖ ./graphql.schema.json
    Error: Unable to find any GraphQL type definitions for the following pointers: -"src/**/*.graphql"
```

My backend is a `nestjs` application which exposes a `graphql` interface. My `schema.gql` file has been generated by `type-graphql` which I paste below

1. My GraphQL schema:

```graphql
# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

"""Date custom scalar type"""
scalar Date

type Mutation {
  create_user(user: UserInput!): User!
  create_pofficer(pofficer: POfficerCreateInput!): POfficer!
  create_incident(incident: TIncidentInput!): TIncident!
  add_incident_type(incident_type: TIncidentTypeInput!): TIncidentType!
}

type POfficer {
  _id: ID!
  userid: ID!
  user: User!
}

input POfficerCreateInput {
  name: String!
  surname: String!
  phone: String!
}

type Query {
  users: [User!]!
  pofficers: [POfficer!]!
  incidents: [TIncident!]!
  incident_types: [TIncidentType!]!
}

type TIncident {
  _id: ID!
  createdAt: Date!
  incidenttype_id: ID!
  pofficer_id: ID!
  toffender_id: ID
  toffender_phone: String!
  carnumber: String!
  incident_status: String!
  pofficer: POfficer!
  toffender: User!
  incident_type: TIncidentType!
}

input TIncidentInput {
  incidenttype_id: ID!
  pofficer_id: ID!
  toffender_phone: String!
  carnumber: String!
}

type TIncidentType {
  _id: ID!
  name: String!
  description: String
}

input TIncidentTypeInput {
  name: String!
  description: String
}

type User {
  _id: ID!
  name: String!
  surname: String!
  email: String
  phone: String!
}

input UserInput {
  name: String!
  surname: String!
  email: String!
  phone: String!
}


```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "https://umoja-apps.herokuapp.com/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

**Expected behavior**
Should generate typescript types from remote schema

**Environment:**

- OS: Macbook pro high sierra
- `@graphql-codegen/cli`: 1.8.3 
- NodeJS: v12.10.0

**Comment by ardatan** [comment] 2019-11-19 14:20
Do you have client-side operations on `documents: "src/**/*.graphql"`?

**Comment by aldegoeij** [comment] 2019-11-20 13:57
I have the same problem, operations should be generated from schema right?

**Comment by ardatan** [comment] 2019-11-20 14:03
No you need to provide the operations against the schema.

**Comment by seyaobey** [comment] 2019-11-21 10:18
I have solved the issue by applying the answer from this [my (same) overflow question here](https://stackoverflow.com/questions/58904403/unable-to-find-any-graphql-type-definitions-for-the-following-pointers-src)
Basically I had to create a `.graphql` file with at least 1 operation (`query` or `mutation`). And now it works. I don't know whether this is the real solution to this problem or a hack. Maybe it should be mentioned in the tutorial.

**Comment by aldegoeij** [comment] 2019-11-23 10:04
Thanks @seyaobey !

I've used amplify-graphql-docs-generator (https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-graphql-docs-generator) to generate queries, mutations, etc directly from the type schema.

Is it possible to do this with graqhql-codegen?

**Comment by dotansimha** [comment] 2019-11-24 12:10
@aldegoeij we have an open issue for that: https://github.com/dotansimha/graphql-code-generator/issues/2349

Closing this for now. As mentioned before, either remove `typescript-operations` and `documents: ` section, or add an actual operation :)

**Closed by dotansimha** 2019-11-24 12:10 UTC

**Comment by syedahmedusman2** [comment] 2020-10-24 07:39
> I have the same problem, operations should be generated from schema right?

How to do it

**Comment by dotansimha** [comment] 2020-11-04 11:00
Operations are not generated from the schema. They should be written based on the components / client that needs them.
Generating GraphQL operations isn't different than using REST...

**Comment by ericwooley** [comment] 2023-03-23 20:08
It would be great if this were ignorable.

I have some new patterns to add, but they are in a new PR. Since this breaks for essentially no reason, I can't do this in 2 PR's. I have to add an unused query so that the CI doesn't break.

**Comment by mjstelly** [comment] 2023-05-22 19:33
Removing the line `documents: './app/**/*.graphql',` and rerunning the tool resolved my issue.

**Comment by fkaempfer** [comment] 2024-05-16 12:28
In my case the cause was that the generated client was in the parent directory of the **/*.graphql docs. Make sure you generate the client somewhere, where it does not overwrite your documents.

**Comment by henrybabbage** [comment] 2024-05-20 14:24
> In my case the cause was that the generated client was in the parent directory of the **/*.graphql docs. Make sure you generate the client somewhere, where it does not overwrite your documents.

Wowww I'm so glad I found this comment thank you! I was losing my mind trying to understand why I was getting "Unable to find any GraphQL type definitions for the following pointers:" even though the directory was correct.

Fixed by not generating the output + client in the parent directory where your .graphql documents are.

**Comment by baotpham** [comment] 2024-08-12 03:24
I was able to resolve this error by change the `documents` to this `apps/web/src/**/*.ts?(x)`. For some reason, having multiple documents' pattern did not work for me. 


```
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  watch: true,
  overwrite: true,
  // since this is a monorepo and we share the schema file, we can just map it to the file
  schema: 'graphql/schema.gql',
  documents: ['./src/**/*.ts?(x)'],
  generates: {
    './src/__generated__/': {
      preset: 'client',
      presetConfig: {
        gqlTagName: 'gql',
      },
    },
  },
};

export default config;
```
