### ISSUE TITLE
How to load TypeScript schema (.ts) with custom path imports defined in tsconfig.json?

### ISSUE THREAD

**Issue by fabis94** [dotansimha/graphql-code-generator#1874] opened 2019-05-15 20:09 UTC
I've got a schema.ts like this:
```ts
import { makeExecutableSchema } from "graphql-tools";
import typeDefs from "~/graphql/typeDefs/typeDefs";

/**
 * GraphQL Schema used by this server
 */
export default makeExecutableSchema({
  typeDefs
  // resolvers
});
```

For some reason the generator fails to load it. The default error outputted to the console tells me nothing of use - "Unable to find matching files for glob: packages/backend/src/graphql/schema.ts". I attached a debugger to the process and arrived at the real place where an error is thrown and found out the actual error: Cannot find module ~/graphql/typeDefs/typeDefs. 

I bet this is because of the custom path. Now, in my project TypeScript knows how to resolve these because of the tsconfig.json that defines these in the "paths" property, but how do I make  the codegen also read the same config so it understands the paths? I know of the "tsconfig-paths" package that could help me with this, but I'm not sure how to use it in this case. I added it to require and specified the --project argument, but it doesn't seem to work.

Here's my codegen.yml:
```yml
overwrite: true
schema: packages/backend/src/graphql/schema.ts
generates:
  packages/backend/src/graphql/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
```

**Comment by ardatan** [comment] 2019-05-15 20:45
```
overwrite: true
schema: packages/backend/src/graphql/schema.ts
generates:
  packages/backend/src/graphql/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
  - tsconfig-paths/register
```
Adding tsconfig-paths/register should work. Could you try that?

**Comment by fabis94** [comment] 2019-05-16 06:45
Didn't work, unfortunately, I had already tried that. Added the 'require' entry and added --project packages/backend/tsconfig.sjon to the command as well. I stepped through the debugger and saw it load in the config, but it doesn't work correctly for some reason. I think it's because it requires the absolute path of the schema.ts file, which might not be supported (it calls require("C:\Code\proj\packages\backend\src\graphql\schema.ts"), as none of the path rewrites apply to it obviously. I'm not sure what's the reason, but I'm fairly confident this could be replicated with any TypeScript repo that uses custom paths.

**Comment by dotansimha** [comment] 2019-05-16 08:26
@fabis94 I think the issue here is not the `require`, is the fact that you need to provide `--project`. 
The `tsconfig-paths` looks for `tsconfig.json` in `process.cwd`, and in this case it's your root directory, and not `packages/backend/`. 
Instead specifying `--project`, try to specify it using environment variables: `TS_NODE_PROJECT=packages/backend/tsconfig.json` (see https://www.npmjs.com/package/tsconfig-paths#with-ts-node).

**Comment by fabis94** [comment] 2019-05-16 08:27
@dotansimha The project file is definitely loaded in correctly, I saw it load the correct paths from my config while debugging.

**Comment by dotansimha** [comment] 2019-05-16 08:58
I see. @fabis94 . Any chance you can create a small reproduction repo? I will help us to fix it faster :)

**Comment by fabis94** [comment] 2019-05-16 19:14
@dotansimha I tried doing so and to my surprise I couldn't replicate this issue and the import worked fine w/ the same tsconfig.json being loaded. Unfortunately I can't share the original repo, but maybe someone with deep knowledge of inner TypeScript could help me here. I debugged deeper into the actual part where the .ts files get compiled into JS during runtime and noticed that the schema.ts file gets compiled differently in both projects. Here are the differences:

![image](https://user-images.githubusercontent.com/938316/57880360-39c85a00-7827-11e9-9c02-e9407972c434.png)

Basically, in the broken project, for some reason the var __importDefault function isn't generated at the beginning of the file and thus the require('~/graphql/typeDefs/typeDefs) import doesn't get wrapped with it and it can't find it using the custom path definition. The tsconfig.json is identical between both projects and I debugged them both the same way:

Broken proj:
 npx --node-arg=--inspect-brk graphql-codegen --config codegen.yml --project ./packages /backend/tsconfig.json

Working proj:
npx --node-arg=--inspect-brk graphql-codegen --config codegen.yml --project tsconfig.json

The tsconfig looks like this in the broken proj:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "module": "commonjs",
    "esModuleInterop": true,
    "baseUrl": "./src",
    "paths": {
      "~/*": ["*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./typings",
      "../../node_modules/@types"
    ],
    "lib": ["es2015", "es2016", "es2017", "es2018"],
    "outDir": "build"
  },
  "extends": "../../tsconfig.base.json"
}
```

And it looks like this in the working proj:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "module": "commonjs",
    "esModuleInterop": true,
    "baseUrl": "./src",
    "paths": {
      "~/*": ["*"],
      "@gql/*": ["subfolder/*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./typings",
      "../../node_modules/@types"
    ],
    "lib": ["es2015", "es2016", "es2017", "es2018"],
    "outDir": "build"
  },
  "extends": "../../went/tsconfig.base.json"
}
```

Both of them extend the  exact same tsconfig.base.json file:
```
{
  "compilerOptions": {
    // "noEmit": true,
    "strict": true,
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true
  }
}
```

Codegen.yml in the broken proj:
```
overwrite: true
schema: packages/backend/src/graphql/schema.ts
generates:
  packages/backend/src/graphql/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
  - tsconfig-paths/register
```

Codegen.yml in the working proj:
```
overwrite: true
schema: src/schema.ts
generates:
  src/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
  - tsconfig-paths/register
```

Hopefully you guys have any ideas cause I'm digging deep in the compiler and close to giving up

**Comment by fabis94** [comment] 2019-05-16 20:03
God damn...turns out the "Cannot find module" error was thrown, because my repo is a monorepo setup and the root directory with the codegen installation doesn't have a tsconfig.json file. And when I specified --project packages/backend/tsconfig.json for some reason it only applied to tsconfig-paths not to ts-node, which just used defaults and thus couldn't resolve what "~/graphql/typeDefs/typeDefs" meant. I had to create a duplicate tsconfig.json in the monorepo root with only the baseUrl changed to "./packages/backend/src" and now ts-node loads that config and it can resolve the paths. Pretty retarded if you ask me...The ts-node/register JS calls the register() function without any of the parameters passed to the command in the CLI, even though the function does accept custom options like '--project' etc.

Of course I couldn't get away that easy, because now while it can find the file and it compiles the JS the same way it does for the working project, I still get the " Error: All found files for glob expression "packages/backend/src/graphql/schema.ts" are not valid or empty, please check it and try again!" error.

**Comment by dotansimha** [comment] 2019-05-17 07:26
Hi @fabis94 ,
Sorry for the inconvenience, we know about that issue, it's reported in: https://github.com/dotansimha/graphql-code-generator/issues/1833, and already fixed in our canary release (try to use `1.1.4-alpha-83461d57.4`, it should print those errors).

**Comment by fabis94** [comment] 2019-05-17 07:32
@dotansimha I will try that, but even if it works, this setup with a duplicate tsconfig.json at the monorepo is far from optimal. Do you maybe have any ideas how I could make both ts-node and tsconfig-paths use the config in the ./packages/backend/ subdirectory?

**Comment by dotansimha** [comment] 2019-05-17 07:34
@fabis94 I'm not sure that you must copy your `tsconfig.json`. if there is an issue with your schema file and it caused by multiple instances of `graphql`, then it's not necessarily related to the `tsconfig.json` file. 
Let's try verify first that you have only one copy of `graphql` under your monorepo, and then it will reduce the chances for issues with schema loading. Also, try to use the latest alpha that I mentioned to get a better error reporting.

**Comment by fabis94** [comment] 2019-05-17 13:43
@dotansimha  The issue with the tsconfig.json is separate, as I described in the previous comment. tsconfig-paths loads the correct tsconfig.json( from the --project flag), ts-node doesn't and just loads the tsconfig.json that it can find in the folder from which the codegen is ran (monorepo root). Of course the monorepo root might not even have a tsconfig or if it does have one then obviously the paths/baseUrl in it isn't going to be configured to resolve ./packages/backend modules. The issue here is that I need to provide the same config to both tsconfig-paths and ts-node when running the codegen.

**Comment by fabis94** [comment] 2019-05-17 19:14
Alright, finally got it to work after doing these 2 things:
1. Making sure all monorepo packages use the same version of "graphql"
2. Passing the path to the correct tsconfig to both tsnode and tsconfig-paths using the TS_NODE_PROJECT env variable. The final script command looks like this:

` cross-env TS_NODE_PROJECT=packages/backend/tsconfig.json graphql-codegen --config codegen.yml`

**Comment by dotansimha** [comment] 2019-05-18 08:41
Thank you for the update @fabis94 👍

**Closed by dotansimha** 2019-05-18 08:41 UTC
Labels: question
