### ISSUE TITLE
Unable to generate types for gatsby-transformer-sharp 

### ISSUE THREAD

**Issue by jambonrose** [dotansimha/graphql-code-generator#1783] opened 2019-04-28 17:05 UTC
Thank you for this package. It has made my interactions with GraphQL and TypeScript much more pleasant.

**Describe the bug**
When attempting to generate types on a Gatsby site with `gatsby-transformer-sharp`, `graphql-codegen` raises errors about missing types.

**To Reproduce**
Using:
- macOS 10.14.4
- Node 11.14.0
- npm 6.9.0

```
npm i --save gatsby react react-dom gatsby-transformer-sharp gatsby-plugin-sharp graphql @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-operations
```

My `package.json` has: 

```json
  "dependencies": {
    "@graphql-codegen/cli": "1.1.1",
    "@graphql-codegen/typescript": "1.1.1",
    "@graphql-codegen/typescript-operations": "1.1.1",
    "gatsby": "2.3.32",
    "gatsby-plugin-sharp": "2.0.35",
    "gatsby-transformer-sharp": "2.1.18",
    "graphql": "14.2.1",
    "react": "16.8.6",
    "react-dom": "16.8.6"
  }
```

Follow the instructions for the [Gatsby integration](https://graphql-code-generator.com/docs/integrations/gatsby) and create a file named `codegen.yml`.

```yaml
overwrite: true
schema: "http://localhost:8000/___graphql"
documents:
  - "./node_modules/gatsby-*/**/*.js"
  - "./src/**/*.{ts,tsx}"
generates:
  src/graphqlTypes.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
```

In one terminal, run `gatsby develop` (or `./node_modules/.bin/gatsby develop`).

In a second terminal, run `graphql-codegen --config codegen.yml` or (or `./node_modules/.bin/graphql-codegen --config codegen.yml`)

The output I currently see:

```
$ ./node_modules/.bin/graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/graphqlTypes.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        →         at ./node_modules/gatsby-transformer-sharp/src/fragments.js:200:53


 Found 1 error

  ✖ src/graphqlTypes.ts
    AggregateError: 
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:1:35
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:9:45
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:17:44
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:27:54
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:37:44
        GraphQLDocumentError: Unknown type "ImageSharpFixed".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:44:53
        GraphQLDocumentError: Unknown type "ImageSharpFluid".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:53:35
        GraphQLDocumentError: Unknown type "ImageSharpFluid".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:61:45
        GraphQLDocumentError: Unknown type "ImageSharpFluid".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:69:44
        GraphQLDocumentError: Unknown type "ImageSharpFluid".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:79:54
        GraphQLDocumentError: Unknown type "ImageSharpFluid".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:89:44
        GraphQLDocumentError: Unknown type "ImageSharpFluid".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:96:53
        GraphQLDocumentError: Unknown type "ImageSharpResolutions".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:105:41
        GraphQLDocumentError: Unknown type "ImageSharpResolutions".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:113:51
        GraphQLDocumentError: Unknown type "ImageSharpResolutions".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:121:50
        GraphQLDocumentError: Unknown type "ImageSharpResolutions".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:131:60
        GraphQLDocumentError: Unknown type "ImageSharpResolutions".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:141:50
        GraphQLDocumentError: Unknown type "ImageSharpResolutions".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:148:59
        GraphQLDocumentError: Unknown type "ImageSharpSizes".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:157:35
        GraphQLDocumentError: Unknown type "ImageSharpSizes".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:165:45
        GraphQLDocumentError: Unknown type "ImageSharpSizes".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:173:44
        GraphQLDocumentError: Unknown type "ImageSharpSizes".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:183:54
        GraphQLDocumentError: Unknown type "ImageSharpSizes".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:193:44
        GraphQLDocumentError: Unknown type "ImageSharpSizes".
            at ./node_modules/gatsby-transformer-sharp/src/fragments.js:200:53


Something went wrong
```

**Expected behavior**

Given #1604, I would have expected to have no problems generating types.

**Comment by dotansimha** [comment] 2019-04-28 18:48
Hi @jambonrose ! 
Our current documentation regarding Gatsby integration refers to the missing fragments that Gastby declares internally. 
I'm actually not familiar enough with Gasby, but according to that error, I think that Gatsby declares internal GraphQL types behind the scenes, and they are required in order to create the complete schema for the codegen. 
I can only assume that they are declared somewhere inside `/node_modules/gatsby-*/`. 

Is there a chance you create create a small reproduction repository for this issue? Then it will be easier for me to test it locally and fix that.

**Comment by jambonrose** [comment] 2019-04-28 18:56
Hi @dotansimha !

Thanks for taking a look at this.

Does the project below have enough info?

https://github.com/jambonrose/gql-gen-error-gatsby-sharp-mve

I note that a quick search on Gatsby reveals that those types are created in only two places. The second may be the one you're looking for (but as I started using GraphQL for the first time _today_, I'm not sure.)

- [packages/gatsby-transformer-sharp/src/fragments.js](https://github.com/gatsbyjs/gatsby/blob/26582d31ab14f7bac6d5738e4245ceca2e6d411d/packages/gatsby-transformer-sharp/src/fragments.js)
- [packages/gatsby-transformer-sharp/src/extend-node-type.js](https://github.com/gatsbyjs/gatsby/blob/494ad071f0428b04d35f6e813a603bf8e3b78cac/packages/gatsby-transformer-sharp/src/extend-node-type.js)

Please let me know if I can help in any way.

**Comment by dotansimha** [comment] 2019-05-01 07:49
@jambonrose I'm taking a look now. 
I noticed that you load your schema from a local endpoint, which is great because it means that you are getting the schema directly from the Gatsby runtime. 
The error you see there related to the fact that your final schema does not include `type ImageSharpFixed` (and some others), and that's why the fragment is failing to compile and load. 

I think, if you are not using those fragments from `node_modules/gatsby-transformer-sharp/src/fragments.js`, just make sure not not load it (By changing the `documents:` part of the yml config, and load only the ones that are relevant to your schema). 
Or, you can make sure that your schema will actually contain those types. I think it comes form `gatsby-transformer-sharp`, and it should extend your schema somehow (but not sure why, because I'm not familiar with Gatsby).

**Comment by jambonrose** [comment] 2019-05-01 21:34
Hi @dotansimha ,

I would like to be able to use the fragments provided, as I would like to be able to use Gatsby to manipulate images via GraphQL. Does that answer your question? I see that you have added the "waiting-for-answer" tag, but I'm not sure what question to answer.

I agree that `gatsby-transformer-sharp` appears to be extending the schema. Gatsby usually plugs into files named `gatsby-node.js`, so I'm guessing that Gatsby uses [`gatsby-node.js`](https://github.com/gatsbyjs/gatsby/blob/26582d31ab14f7bac6d5738e4245ceca2e6d411d/packages/gatsby-transformer-sharp/src/gatsby-node.js) to run the scripts in [`packages/gatsby-transformer-sharp/src`](https://github.com/gatsbyjs/gatsby/tree/26582d31ab14f7bac6d5738e4245ceca2e6d411d/packages/gatsby-transformer-sharp/src) directory.

I took a quick look at this package to see how you're generating types from the GraphQL, but I'm a little tired after a long day. Does this package need static GraphQL definitions? Does it handle dynamic GraphQL generation like what `gatbsy-transformer-sharp` is doing?

**Comment by dotansimha** [comment] 2019-05-07 07:44
@jambonrose 
The codegen can load schemas from a lot of sources (static graphql files, code files and http endpoints). In your case, you are using http endpoint which is great, because it means that the codegen will load the schema in a ready-to-use state.
I'm not sure how `gatsby-transformer-sharp` works, but it definitely not extending your schema, because the `ImageSharpFixed` is missing during the runtime of your backend, even if you'll try to run a query with the those fragments, it will fail.
It's not an issue directly  with the codegen- it's related to Gatsby and `gatsby-transformer-sharp` - those `type`s are just not being added to the schema, and that's why the fragments validation is failing.

**Comment by dotansimha** [comment] 2019-05-19 12:55
Closing for now. @jambonrose feel free to contact if you have more issues or more information regarding this one.

**Closed by dotansimha** 2019-05-19 12:55 UTC

**Comment by jambonrose** [comment] 2019-05-26 21:23
Hi @dotansimha - Thank you very much for taking the time to walk me through how the tool works and where the problem lies. My apologies for the slow response (due to work) and for opening an issue in the wrong place. I will let you know what I find once I'm able to come back around to this issue.

Thanks again for a very helpful tool!
