### ISSUE TITLE
typescript-react-query doesn't respect `useTypeImports` from `react-query`

### ISSUE THREAD

**Issue by jonathanstanley** [dotansimha/graphql-code-generator#7666] opened 2022-03-19 04:03 UTC
### Issue workflow progress

- [ ] 1. The issue provides a reproduction available on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

- [ ] 2. A failing test has been provided

- [x] 3. A local solution has been provided

- [x] 4. A pull request is pending review

---

**Describe the bug**
when using `useTypeImports`, generated code is incorrect.  it should be:

```diff
- import { useQuery, UseQueryOptions, useMutation, UseMutationOptions } from 'react-query';
+ import { useQuery, useMutation } from 'react-query';
+ import type { UseQueryOptions, UseMutationOptions } from 'react-query';
```

**To Reproduce**
caused when config has the following:

- typescript-react-query plugin
- useTypeImports: true

1. My GraphQL schema:

```graphql
# any
```

2. My GraphQL operations:

```graphql
# any
```

3. My `codegen.yml` config file:

```yml
schema:
  - ${APIURL}
documents: "my-codegen-src/*.graphql"
generates:
  my-codegen-out/reactQuery.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
      useTypeImports: true
```

**Expected behavior**
Types need to be tracked separately and imports should respect the `useTypeImports` flag.

**Environment:**
-any

**Additional context**
Similar to #7661 (but not identical). Sending PR to fix this.

**Comment by charlypoly** [comment] 2022-03-21 15:08
Released in `@graphql-codegen/typescript-react-query@3.5.9` 📦

**Comment by solomon23** [comment] 2022-03-21 23:05
I have 3.5.9 installed and it's giving me the same error

**Comment by charlypoly** [comment] 2022-03-22 08:54
> I have 3.5.9 installed and it's giving me the same error

Hi @solomon23,

could you please provide a reproduction on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)?

Thank you!

**Comment by solomon23** [comment] 2022-03-24 23:49
> > I have 3.5.9 installed and it's giving me the same error
> 
> Hi @solomon23,
> 
> could you please provide a reproduction on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)?
> 
> Thank you!

Oh sorry - I should have left more info.  I went another way though so I don't have it repro'ing locally anymore.  If I run into it again I'll swing on back

**Comment by charlypoly** [comment] 2022-03-28 08:24
Hi @jonathanstanley, do you confirm that the issue is solved in `@graphql-codegen/typescript-react-query@3.5.9`?

**Comment by jonathanstanley** [comment] 2022-03-28 16:20
Tests are still green. 

> If I run into it again I'll swing on back

I think we could close until then.

**Closed** 2022-03-28 16:42 UTC
